import json
DI, FS, TU, HWS, NK = 'Devinterview', 'FullStack.Cafe', 'Turing', 'Hacking with Swift', 'Naukri Code360'
C = []
def c(id, topic, q, a, *src):
    C.append({'id': id, 'topic': topic, 'question': q, 'answer': a.strip(), 'sources': list(src), 'problemIds': []})

# ---------------- Basics
T='Basics'
c('let-vs-var',T,'What is the difference between `let` and `var`?',"""`let` declares a constant: it must be initialised exactly once and can't be reassigned. `var` declares a variable. For **value types**, `let` also freezes the whole value (you can't call `mutating` methods on it); for **class** references, `let` only freezes the *reference* — the object's `var` properties can still change. Prefer `let` by default; the compiler warns when a `var` is never mutated.""",DI,FS,TU,NK)
c('runtime-constants',T,'How do you define a constant whose value is only known at runtime?',"""A `let` doesn't need a compile-time value — it just needs to be assigned exactly once before use. `let start = Date()` or a `let` assigned in both branches of an `if` are fine; definite-initialisation analysis checks every path. `static let` properties are lazily initialised once, thread-safely.""",DI)
c('type-inference',T,'What is type inference?',"""The compiler deduces a type from context so you don't write it: `let n = 42` is `Int`, `let x = 3.0` is `Double`, `[1, 2]` is `[Int]`. Annotate when the default isn't what you want (`let f: Float = 3`), when there's no initial value, or to speed up complex expressions. Inference works bidirectionally, including closure parameter types from the function you pass them to.""",DI,TU,NK)
c('fundamental-types',T,'What fundamental data types does Swift have?',"""`Int` (64-bit on modern platforms) and sized variants (`Int8`…`UInt64`), `Double`/`Float`, `Bool`, `String`, `Character`, plus tuples and `Optional`. They're all **structs** in the standard library, which is why they have methods (`5.isMultiple(of: 5)`). There is no `char` primitive — `Character` is an extended grapheme cluster.""",TU,NK)
c('float-vs-double',T,'What is the difference between `Float`, `Double` (and `CGFloat`)?',"""`Float` is 32-bit (~6–7 significant digits), `Double` is 64-bit (~15–16 digits) and is what Swift infers for literals like `3.14`. `CGFloat` is Core Graphics' native float (64-bit on 64-bit platforms) and bridges implicitly with `Double` since Swift 5.5. Floating point is binary, so `0.1 + 0.2 != 0.3` — compare with a tolerance.""",HWS)
c('numeric-literals',T,'What kinds of literals does Swift support?',"""Integer literals in decimal (`17`), binary (`0b10001`), octal (`0o21`) and hex (`0x11`); floating-point literals incl. exponents (`1.25e2`, hex `0xFp2`); underscores for readability (`1_000_000`); string, multiline (`\"\"\"`) and raw (`#\"...\"#`) string literals; boolean, `nil`, array and dictionary literals. Types opt in via `ExpressibleBy…Literal` protocols.""",NK)
c('integer-overflow',T,'What happens when an integer overflows?',"""Plain arithmetic **traps** at runtime (a crash, not silent wraparound) — a safety feature. Use the overflow operators `&+`, `&-`, `&*` to wrap deliberately, or `addingReportingOverflow(_:)` to detect it. `Int.max`/`Int.min` give the bounds.""",TU)
c('comments',T,'How do you write single-line and multi-line comments?',"""`//` for single-line, `/* … */` for multi-line — and unlike C, block comments **nest**, so you can comment out code that already contains comments. `///` and `/** */` are documentation comments picked up by Quick Help and DocC.""",TU)
c('typealias',T,'What is a `typealias`?',"""A new name for an existing type: `typealias Grid = [[Int]]`, `typealias Completion = (Result<Data, Error>) -> Void`. It doesn't create a distinct type (a `Grid` *is* a `[[Int]]`) — for a genuinely distinct type use a struct wrapper or phantom type. Protocols use `associatedtype` instead.""",NK)
c('print-vs-debugprint',T,'What is the difference between `print` and `debugPrint`?',"""`print` uses `CustomStringConvertible.description` (`"hi"` prints as `hi`), `debugPrint` uses `CustomDebugStringConvertible.debugDescription` (`"hi"` prints as `"hi"`, with quotes and escapes). Both take `separator:` and `terminator:`; `dump` prints a recursive structural view.""",TU)
c('immutability',T,'Why is immutability important in Swift?',"""Immutable values can't change under you, so they're easier to reason about, safe to share across threads (value types + `let` are `Sendable`-friendly), and let the compiler optimise. Swift nudges you there with `let`, value-type collections, `mutating` markers and the "never mutated" warning.""",HWS,NK)
c('swift-advantages',T,'Why is Swift preferred over Objective-C? What are its key features?',"""Safety (optionals, bounds and overflow checks, definite initialisation), speed (value types, static dispatch, generics specialisation), expressiveness (type inference, closures, enums with associated values, pattern matching, tuples), protocol-oriented design and modern concurrency (`async`/`await`, actors). ARC manages memory for both.""",TU,NK)
c('nil-vs-null',T,"What's the difference between Swift's `nil` and other languages' `null`?","""In Swift `nil` isn't a null pointer — it's `Optional.none`, the absence of a value for **any** type (including `Int`). Only optionals can hold it, so non-optional types are guaranteed to have a value and the compiler forces you to handle the missing case.""",TU)
# ---------------- Operators
T='Operators & ranges'
c('equality-vs-identity',T,"What's the difference between `==` and `===`?","""`==` asks *are these values equal?* — defined by `Equatable`. `===` asks *are these the same object instance?* — only for class instances (`AnyObject`). Two distinct objects with identical contents are `==` (if Equatable) but not `===`.""",FS,TU,NK)
c('half-open-range',T,'What are closed, half-open and one-sided ranges?',"""`a...b` includes `b`; `a..<b` excludes it (perfect for `0..<array.count`); one-sided `a...`, `...b`, `..<b` run to the end/start of a collection (`array[2...]`). A closed range with `a > b` traps at runtime.""",TU,HWS)
c('stride',T,'What does `stride` do?',"""`stride(from:to:by:)` excludes the end, `stride(from:through:by:)` includes it. They step by any amount, including negative and fractional: `stride(from: 10, through: 0, by: -2)`. Use it where C would use `for (i = 10; i >= 0; i -= 2)`.""",TU)
c('ternary',T,'How does the ternary conditional operator work?',"""`condition ? a : b` evaluates to one of two expressions of the same type. Great for simple choices; if either branch has side effects or the condition is long, an `if` expression (`let x = if c { a } else { b }`, Swift 5.9+) reads better. `c ? true : false` is just `c`.""",)
c('nil-coalescing',T,'What does the nil-coalescing operator `??` do?',"""`a ?? b` unwraps `a` if it has a value, otherwise evaluates `b` — lazily (it's an `@autoclosure`). It chains: `a ?? b ?? c`. The result is non-optional when `b` is non-optional.""",HWS)
c('operator-overloading',T,'What is operator overloading?',"""Defining an existing operator (`+`, `==`, `<`) for your own types as a `static func` — e.g. `static func + (l: Vector, r: Vector) -> Vector`. Conforming to `Equatable`/`Comparable` is just implementing `==` / `<`. Keep semantics unsurprising.""",HWS,TU)
c('custom-operators',T,'How do you define a custom operator?',"""Declare it (`infix operator **: MultiplicationPrecedence`, or `prefix`/`postfix`), then implement it as a function. You can create precedence groups with associativity. Use sparingly — custom symbols are hard to search for and read.""",TU)
c('tuple-comparison',T,'How would you compare two tuples?',"""Tuples of up to 6 `Equatable` elements support `==`, and of `Comparable` elements support `<` (lexicographic, left to right). Tuples can't conform to protocols themselves, so for more elements or as dictionary keys, use a struct.""",HWS)
c('pattern-matching-operator',T,'What is the `~=` pattern-matching operator?',"""`switch` and `case` patterns call `~=` under the hood — that's how `case 1...5:` matches a range. Overload `static func ~= (pattern: P, value: V) -> Bool` to make your own patterns work in `switch`.""",TU)
# ---------------- Strings
T='Strings'
c('strings-are-collections',T,'What does it mean that strings are collections?',"""`String` is a `BidirectionalCollection` of `Character`s, so `map`, `filter`, `reversed()`, `for c in s` all work. But indexes are `String.Index`, not `Int`, because characters are variable-width grapheme clusters — "é" or "👨‍👩‍👧" are one `Character` spanning several code units. `count` is O(n).""",HWS)
c('string-equality',T,'How do you check whether two strings are equal?',"""`==` compares with **canonical equivalence**: "é" (one scalar) equals "e" + combining accent. For case-insensitive comparison use `a.lowercased() == b.lowercased()` or `caseInsensitiveCompare` / `compare(_:options:)` from Foundation.""",TU)
c('raw-strings',T,'What are raw strings?',"""Strings wrapped in `#` — `#"C:\\path\\n"#` — where backslashes and quotes are literal. Interpolation needs the matching number of hashes: `\\#(value)`. Ideal for regexes and JSON snippets.""",HWS)
c('string-interpolation',T,'How does string interpolation work?',"""`"\\(expr)"` embeds any value using its `description`. It's extensible: `DefaultStringInterpolation` can be extended with `appendInterpolation(_:)` overloads to add custom formats like `"\\(price, format: .currency)"`.""",)
c('regex',T,'What is a regular expression in Swift?',"""Since Swift 5.7, `Regex` is built in: literals `/\\d+/`, `try Regex("…")` or the `RegexBuilder` DSL. Use `firstMatch(of:)`, `matches(of:)`, `wholeMatch(of:)`, `replacing(_:with:)`, `split(separator: regex)`. Captures are strongly typed tuples.""",NK)
# ---------------- Collections
T='Collections'
c('collection-types',T,'What collection types does Swift provide?',"""`Array` (ordered, duplicates allowed, O(1) index), `Set` (unordered, unique, O(1) membership, needs `Hashable`), `Dictionary` (unordered key→value, unique `Hashable` keys). All are **value types** with copy-on-write, and all are generic.""",DI,FS,NK)
c('array-basics',T,'What are arrays in Swift?',"""Ordered, zero-indexed, homogeneous `[Element]` collections. Out-of-bounds subscripts trap. Useful API: `append`, `insert(_:at:)`, `remove(at:)`, `first`/`last` (optional), `firstIndex(of:)`, `contains`, `sorted`, `reversed`, `enumerated`, `zip`.""",NK)
c('dictionary-basics',T,'How do dictionaries work, and how are they different from arrays?',"""Unordered `[Key: Value]` maps. Subscript reads return an optional (the key may be missing); `dict[k, default: 0] += 1` is the counting idiom; assigning `nil` removes a key. Unlike arrays, there's no ordering and lookup is by hashed key, not position.""",HWS,TU,NK)
c('set-vs-array',T,'When would you use a `Set` instead of an `Array`?',"""When order doesn't matter and elements are unique, and you need fast membership tests (O(1) vs O(n)) or set algebra: `union`, `intersection`, `subtracting`, `symmetricDifference`, `isSubset(of:)`. Elements must be `Hashable`.""",FS,HWS,TU)
c('sort-custom',T,'How do you sort an array of custom objects by a property?',"""`people.sorted { $0.age < $1.age }` returns a new array; `sort(by:)` sorts in place. For multiple keys, compare tuples: `{ ($0.last, $0.first) < ($1.last, $1.first) }`. Conform to `Comparable` to get plain `sorted()`. Swift's sort is stable (introsort-free since 5.0, currently a stable merge-based sort).""",FS,TU)
c('map-filter-reduce',T,'Compare `map`, `filter` and `reduce`.',"""`map` transforms every element (same count out), `filter` keeps elements matching a predicate, `reduce(initial, combine)` folds everything into one value. `reduce(into:)` is the efficient form when building collections. Chain them for declarative pipelines.""",TU)
c('compactmap-flatmap',T,'What is the difference between `map`, `compactMap` and `flatMap`?',"""`map` → one output per input (may be optionals). `compactMap` → drops `nil` results (`["1","x"].compactMap(Int.init)` is `[1]`). `flatMap` → each element maps to a sequence and the results are concatenated (flattens one level).""",HWS,NK)
c('higher-order-functions',T,'What are higher-order functions?',"""Functions that take or return other functions — `map`, `filter`, `reduce`, `sorted(by:)`, `forEach`, `contains(where:)`, `first(where:)`, `allSatisfy`. They replace hand-written loops with intent-revealing names.""",NK,TU)
c('lazy-sequences',T,'What are lazy sequences?',"""`array.lazy.map { … }.filter { … }` builds a view that computes elements on demand instead of allocating intermediate arrays — great with `first(where:)` or huge/infinite sequences. Beware: closures may run more than once per element if you iterate repeatedly.""",)
c('custom-collection',T,'How do you implement a custom collection type?',"""Conform to `Sequence` (provide `makeIterator()`) for single-pass iteration, or `Collection` (`startIndex`, `endIndex`, `index(after:)`, `subscript(position:)`) to get multi-pass iteration plus `count`, `first`, `map`, slicing and more for free.""",TU)
c('subscripts',T,'What is subscripting, and how do you write a custom subscript?',"""Subscripts give `[]` access to your type: `subscript(row: Int, col: Int) -> Int { get set }`. They can take multiple/labelled parameters, be generic, `static`, or overloaded. Dictionary's `subscript(key:default:)` is an example.""",TU,NK)
c('uuid',T,'What is a UUID and when would you use it?',"""A 128-bit universally unique identifier (`UUID()`, `uuidString` like `E621E1F8-C36C-495A-93FC-0C247A3E6E5F`). Use it to identify values that don't have a natural key (`Identifiable` models, file names, request IDs). Collisions are practically impossible.""",HWS)
c('copy-on-write',T,'What is copy-on-write?',"""Standard collections share their storage buffer when copied; the actual copy happens only when one copy is **mutated** while the buffer is shared. You get value semantics with the performance of passing references. Implement it for your own types using a class buffer + `isKnownUniquelyReferenced(&buffer)`.""",TU)
# ---------------- Tuples
c('tuples','Tuples','What are tuples and why are they useful?',"""Lightweight, fixed-size groupings of values of possibly different types: `(code: 404, message: "Not Found")`. Perfect for returning multiple values from a function and for switching on several values at once. Access by label or `.0`. They can't conform to protocols, so use a struct for anything long-lived.""",DI,HWS,TU,NK)
# ---------------- Control flow
T='Control flow'
c('control-flow',T,'How does Swift handle flow control with loops and conditions?',"""`if`/`else`, `guard`, `switch`; loops `for-in` (over any `Sequence`), `while`, `repeat-while`. Conditions must be `Bool` — no implicit truthiness. `if` and `switch` can be expressions (5.9+).""",DI)
c('for-in',T,'How does the `for-in` loop work?',"""It iterates any `Sequence`: ranges, arrays, dictionaries (as `(key, value)` tuples), strings, `stride`, `zip`. Add `where` to filter, `enumerated()` for indices, and use `_` when you don't need the value.""",TU)
c('break-continue',T,'What do `break`, `continue`, `fallthrough` and `return` do?',"""Control-transfer statements. `continue` skips to the next iteration; `break` exits the innermost loop or `switch`; labelled statements (`outer: for …` then `break outer`) exit nested loops; `fallthrough` continues into the next `switch` case; `return`/`throw` leave the function.""",TU,NK)
c('switch-statement',T,'What makes Swift `switch` powerful?',"""It must be **exhaustive**, doesn't fall through implicitly, and matches patterns: ranges, tuples, `let` bindings, `where` clauses, enum cases with associated values, type-casting patterns (`case let s as String`) and multiple patterns per case. Leaving out `default` on an enum switch makes adding a new case a compile error — a feature.""",DI,TU)
c('fallthrough',T,'What does `fallthrough` do?',"""It makes a `switch` case continue into the **next case's body** without checking its pattern (C-style). It can't be used if the next case binds variables. Rarely needed — prefer listing multiple patterns in one case.""",TU)
c('where-clause',T,'What is the `where` clause used for?',"""Extra conditions on patterns and generics: `for x in xs where x > 0`, `case let n where n.isMultiple(of: 2)`, `catch let e as MyError where e.code == 1`, and generic constraints `func f<T>(_ t: T) where T: Hashable`, `extension Array where Element: Numeric`.""",TU)
c('guard',T,'When would you use `guard`?',"""For early exit: `guard condition else { return }`. The `else` must leave the scope (`return`, `throw`, `break`, `continue` or a `Never` call). Values bound with `guard let` stay available **after** the guard, keeping the happy path unindented.""",HWS,NK)
c('pattern-matching',T,'What is pattern matching in Swift?',"""Destructuring and testing values with patterns in `switch`, `if case`, `guard case`, `for case`: wildcard `_`, bindings `let x`, tuples, enum cases with associated values, optionals `x?`, type casts `is`/`as`, ranges and expression patterns via `~=`.""",TU)
# ---------------- Functions
T='Functions'
c('functions-basics',T,'How do functions work in Swift?',"""Declared with `func name(label param: Type) -> Return`. Parameters are constants. Functions are first-class values with types like `(Int, Int) -> Int`, can be nested, overloaded, and return tuples for multiple values.""",)
c('argument-labels',T,'What are argument labels and why use them?',"""Each parameter has an external **argument label** (used at the call site) and an internal **name**. `func move(from start: Int, to end: Int)` reads as `move(from: 1, to: 5)`. `_` removes the label. Labels are part of the function's name, enabling overloads like `remove(at:)` vs `remove(_:)`.""",)
c('default-params',T,'How do default parameter values work?',"""`func greet(_ name: String, loudly: Bool = false)` lets callers omit trailing arguments. Defaults are evaluated at each call and can reference other defaults. They reduce the need for overloads.""",)
c('variadic',T,'What is a variadic function?',"""A parameter written `Type...` accepts zero or more values, received as an array: `func sum(_ xs: Int...) -> Int`. Since Swift 5.4 a function can have several variadic parameters. You can't pass an existing array to a variadic parameter directly.""",HWS,NK)
c('inout',T,'What is an `inout` parameter and when should you use one?',"""`inout` lets a function modify the caller's variable: the argument is passed with `&` and written back when the function returns (copy-in copy-out). Use it for in-place algorithms like `swap(&a, &b)`; otherwise prefer returning a new value — clearer and composable.""",FS,NK)
c('implicit-return',T,'When does a function not need a `return` keyword?',"""When its body is a single expression (Swift 5.1+), for functions, closures, computed properties and subscripts. Since 5.9, `if`/`switch` expressions can be that single expression too.""",HWS)
c('overloading-overriding',T,'What is the difference between method overloading and overriding?',"""**Overloading**: several functions with the same base name but different parameter types, labels or return types, resolved at compile time. **Overriding**: a subclass replaces an inherited method with `override`, chosen at runtime via dynamic dispatch.""",TU,NK)
c('functions-vs-methods',T,'What is the difference between a function and a method?',"""A method is a function associated with a type — instance methods get implicit `self`, type methods are `static`/`class`. Free functions live at global scope. Method references like `Person.greet` are curried: `Person.greet(p)()`.""",FS)
c('currying',T,'What is function currying?',"""Turning a function of several arguments into a chain of single-argument functions: `func add(_ a: Int) -> (Int) -> Int { { b in a + b } }` so `add(2)(3) == 5`. It enables partial application — `let addTwo = add(2)`.""",TU,NK)
c('never-type','Functions','What is the `Never` type?',"""A return type for functions that never return normally — `fatalError`, `preconditionFailure`, infinite loops. The compiler knows code after them is unreachable, so they satisfy `guard … else` and non-`Void` return requirements.""",)
# ---------------- Closures
T='Closures'
c('closures',T,'What are closures?',"""Self-contained blocks of code that can be passed around and that **capture** constants and variables from their surrounding scope. Global and nested functions are special cases of closures. Syntax: `{ (params) -> Return in body }`, shortened via inference, implicit returns and `$0` shorthand.""",FS,TU,NK,HWS)
c('trailing-closure',T,'What is trailing closure syntax?',"""When the last argument(s) are closures, write them after the parentheses: `nums.sorted { $0 > $1 }`, dropping `()` entirely if it's the only argument. Multiple trailing closures use labels for the extra ones.""",FS,TU)
c('capturing-values',T,'How do closures capture values?',"""By **reference** to the variable by default — a closure sees later changes and can mutate captured `var`s (a counter closure keeps its own state alive). A **capture list** `[x]` captures the current value instead, and `[weak self]`/`[unowned self]` change reference strength.""",TU)
c('capture-list',T,'What is a capture list?',"""`{ [a, weak self, unowned b] in … }` — evaluated when the closure is **created**: value captures snapshot the current value; `weak`/`unowned` avoid strong references (and thus retain cycles).""",NK)
c('escaping',T,'What is the difference between escaping and non-escaping closures?',"""By default a closure parameter is **non-escaping**: it must be called (or not) before the function returns, which lets the compiler optimise and lets you use `self` implicitly. Mark it `@escaping` if it's stored or called later (completion handlers, stored callbacks); then think about capture and retain cycles.""",HWS,TU,NK)
c('autoclosure',T,'What is `@autoclosure` and when should you use it?',"""It wraps an argument expression in a closure automatically, delaying its evaluation: `func log(_ msg: @autoclosure () -> String)`. Used by `assert`, `&&`, `??` so expensive right-hand sides aren't evaluated unless needed. Overuse hides evaluation semantics from callers.""",FS,HWS,NK)
c('computed-vs-closure-property',T,'Computed property vs a property set to a closure?',"""A computed property runs its getter **every access**. `var x: Int = { … }()` runs a closure **once** at initialisation and stores the result. `lazy var x = { … }()` runs once on first access.""",FS)
c('functions-vs-closures',T,'What is the difference between functions and closures?',"""Functions are named closures. Closures can be anonymous inline expressions and capture context; both are reference types with function types like `(Int) -> Bool`, so they're interchangeable wherever that type is expected.""",FS,TU)
c('closures-memory',T,'How does ARC handle memory for closures?',"""Closures are reference types that strongly retain what they capture. If an object stores a closure that captures `self` strongly, you have a cycle: object → closure → object. Break it with `[weak self]` (then `guard let self`) or `[unowned self]` when the closure can't outlive the object.""",TU,NK)
# ---------------- Optionals
T='Optionals'
c('optionals',T,'What are optionals and why do they exist?',"""`T?` is `Optional<T>`, an enum with cases `.some(T)` and `.none` (`nil`). They make the possibility of "no value" explicit in the type system, so non-optional values are guaranteed present and the compiler forces you to handle absence.""",DI,NK)
c('optional-binding',T,'What is optional binding, and how is it different from force unwrapping?',"""`if let x = opt { … }` / `guard let x = opt else { … }` safely test and unwrap in one step (shorthand `if let x`). Force unwrapping `opt!` crashes if `nil` — use only when `nil` is a programmer error you'd want to trap on.""",TU,NK)
c('if-let-vs-guard',T,'What is the difference between `if let` and `guard let`?',"""`if let` scopes the unwrapped value **inside** its braces; `guard let` requires the else branch to exit and makes the value available for the **rest** of the scope. Use `guard` for preconditions/early exits, `if let` when there's work to do only in the present case.""",HWS,TU)
c('multiple-optional-binding',T,'How do you bind multiple optionals at once?',"""Comma-separate the clauses: `if let a = x, let b = y, a < b { … }` — all must succeed, evaluated left to right, and later clauses can use earlier bindings.""",TU)
c('optional-chaining',T,'What problem does optional chaining solve?',"""`person?.address?.city` calls through a chain of optionals and short-circuits to `nil` at the first missing link, producing an optional result instead of nested `if let`s. Works for properties, methods and subscripts; assignments through a chain return `Void?` to tell you if they happened.""",HWS,TU,NK)
c('implicitly-unwrapped',T,"What's the difference between `String?` and `String!`?","""Both can hold `nil`. `String!` is an *implicitly unwrapped optional*: it's force-unwrapped automatically when used where a non-optional is needed (crashing if `nil`). It exists for values that are `nil` only briefly during setup (e.g. IBOutlets). Prefer `?`.""",HWS)
c('forced-unwrapping',T,'What is forced unwrapping?',"""`value!` extracts the wrapped value and traps with "Unexpectedly found nil" if there isn't one. Reasonable only when `nil` would be a bug, and then `guard let … else { preconditionFailure("why") }` documents intent better.""",NK)
# ---------------- Errors
T='Error handling'
c('error-handling',T,'How does Swift handle errors?',"""Functions marked `throws` can `throw` any `Error`-conforming value (usually an enum). Callers must mark the call with `try` and either propagate (`throws` themselves) or handle with `do { try … } catch { … }`. Swift 6 adds typed throws: `throws(MyError)`.""",TU,NK)
c('try-variants',T,'What is the difference between `try`, `try?` and `try!`?',"""`try` propagates/requires a `catch`. `try?` converts the result to an optional, returning `nil` on error (the error is discarded). `try!` asserts no error will be thrown and crashes if one is.""",HWS)
c('multi-pattern-catch',T,'What are multi-pattern catch clauses?',"""A single `catch` can list several patterns: `catch VendingError.outOfStock, VendingError.invalidSelection { … }`. Patterns can bind values and use `where`. A final bare `catch` binds `error`.""",HWS)
c('defer',T,'What does `defer` do?',"""Schedules code to run when the current **scope exits** — normally, via `return`, `break` or a thrown error. Perfect for cleanup (closing files, unlocking). Multiple `defer`s run in **reverse** order of declaration.""",FS,TU,HWS,NK)
c('rethrows',T,'What is the difference between `throws` and `rethrows`?',"""A `rethrows` function only throws if a closure argument throws — so `map` needs `try` only when you pass a throwing closure. `throws` means the function itself may throw regardless.""",TU)
c('result-type',T,"When would you use Swift's `Result` type?","""`Result<Success, Failure: Error>` stores the outcome of an operation as a value: `.success(v)` or `.failure(e)`. Useful for callbacks, storing outcomes, or transforming with `map`/`flatMap`. Convert with `Result { try f() }` and `try result.get()`. With `async throws`, it's needed less often.""",HWS,TU)
c('assert',T,'What does `assert()` do?',"""`assert(cond, msg)` checks a condition in **debug** builds only and traps if false; it's compiled out of `-O` builds. `precondition` checks in release too; `fatalError` always traps. Use assertions for internal invariants, not user input.""",HWS,TU)
# ---------------- Enums
T='Enums'
c('enums',T,'What are enumerations in Swift?',"""A type with a closed set of cases: `enum Direction { case north, south }`. Enums are value types with methods, computed properties, initialisers and protocol conformances. `switch` over them must be exhaustive.""",DI,TU,NK)
c('associated-values',T,'What are associated values, and how do they differ from raw values?',"""**Raw values** are compile-time constants of one type shared by every instance of a case (`case get = "GET"`), with `init?(rawValue:)`. **Associated values** attach per-instance data of any types to a case: `case failure(code: Int, message: String)`. An enum can't have both.""",DI,FS,TU,HWS)
c('case-iterable',T,'What does `CaseIterable` do?',"""Conforming a (payload-free) enum to `CaseIterable` synthesises `static var allCases`, so you can loop over cases, count them, or build pickers without maintaining a list by hand.""",HWS)
c('indirect-enums',T,'What are `indirect` enums, and how do they compare to classes for recursive data?',"""`indirect` lets a case contain the enum itself (expression trees, linked lists) by boxing the payload on the heap. Unlike classes, they keep **value semantics**, exhaustive switching and no inheritance.""",NK)
# ---------------- Structs & classes
T='Structs & classes'
c('struct-vs-class',T,'What are the differences between structs and classes?',"""Structs are **value types** (copied on assignment), get a memberwise initialiser, need `mutating` to change themselves, and can't inherit. Classes are **reference types** (shared), support inheritance, deinitialisers, identity (`===`) and are ARC-managed. Default to structs.""",DI,FS,TU,HWS,NK)
c('value-vs-reference',T,"What's the difference between a value type and a reference type?","""Assigning or passing a **value type** creates an independent copy; mutating one doesn't affect the other. A **reference type** variable holds a pointer to a shared instance; all references see mutations. Structs, enums, tuples and standard collections are value types; classes, closures and actors are reference types.""",HWS,TU)
c('value-semantics',T,'What are value semantics and their benefits?',"""A type has value semantics when copies are independent. Benefits: local reasoning, no unexpected sharing, thread safety, and cheap copies thanks to copy-on-write. Classes can simulate it (immutable classes, COW wrappers).""",TU)
c('mutating',T,'What does the `mutating` keyword mean?',"""Struct and enum methods can't modify `self` unless marked `mutating`. Calling one on a `let` constant is a compile error. Inside, `self` is effectively `inout` — you can even reassign `self = …`.""",FS,TU,NK)
c('class-definition',T,'How do you define a class?',"""`class Name: Superclass, Protocol { stored properties; init; methods; deinit }`. All stored properties must be initialised before use — either with defaults or in a designated `init`.""",DI)
c('inheritance',T,'What are the key principles of inheritance?',"""Classes inherit properties/methods from a single superclass, `override` them (explicitly marked), call up with `super`, and can prevent overriding with `final`. Structs/enums can't inherit — use protocols for shared behaviour.""",DI)
c('multiple-inheritance',T,'Does Swift support multiple inheritance?',"""No — a class has at most one superclass. But any type can conform to **multiple protocols**, and protocol extensions supply default implementations, which gives most benefits of multiple inheritance without the diamond problem.""",DI)
c('encapsulation',T,'How does encapsulation work with classes and structs?',"""Hide implementation with access control (`private`, `fileprivate`, `private(set)`), expose computed properties and methods as the interface, and keep invariants inside the type.""",DI)
c('initializers',T,'What does `init()` do and what are the rules for initialisers?',"""Initialisers set every stored property before the instance is used. Structs get a free memberwise init. Classes have **designated** inits (fully initialise, call `super.init`) and **convenience** inits (must delegate across to another init of the same class).""",NK)
c('convenience-init',T,'What is a convenience initialiser?',"""A secondary `convenience init` in a class that must call another initialiser of the **same** class (`self.init(...)`), usually supplying defaults. Designated inits delegate **up**, convenience inits delegate **across**.""",NK)
c('failable-init',T,'What is a failable initialiser?',"""`init?(…)` may `return nil` when inputs are invalid, producing an optional instance: `Int("42")` is a failable init returning `Int?`. `init!` exists but is rare.""",NK)
c('required-init',T,'What does the `required` keyword mean?',"""`required init` forces every subclass to implement that initialiser (or inherit it). It's needed for protocol init requirements on non-final classes, so `T.init()` works for any subclass.""",FS)
c('initializer-delegation',T,'What is initialiser delegation?',"""Initialisers calling other initialisers to avoid duplication. Value types: `self.init(...)`. Classes: designated → `super.init` (delegate up), convenience → `self.init` (delegate across).""",TU)
c('two-phase-init',T,'What is two-phase initialisation?',"""Phase 1: each class in the hierarchy initialises its **own** stored properties, bottom-up, via `super.init`. Phase 2: once everything is initialised, inits may customise, call methods and use `self`. This guarantees no property is read before being set.""",)
c('deinit',T,'What is `deinit` and when should you use it?',"""A class's deinitialiser runs automatically right before ARC frees the instance. Use it for cleanup (close files, remove observers, invalidate timers) — and while learning, as a leak detector by printing from it. Structs have no `deinit`.""",FS,NK)
c('computed-properties',T,'What is a computed property?',"""A property with a getter (and optional setter) that calculates its value each access instead of storing it: `var area: Double { width * height }`. The setter receives `newValue`.""",TU,NK)
c('property-observers',T,'What are property observers?',"""`willSet` (with `newValue`) and `didSet` (with `oldValue`) run around assignments to a stored property — not during `init` of the same type. Great for validation, clamping and triggering updates.""",HWS,TU,NK)
c('lazy-properties',T,'What is a lazy property?',"""`lazy var` isn't initialised until first accessed, then stored. Useful for expensive setup or values depending on `self`. Must be `var`, and isn't thread-safe.""",TU,NK)
c('lazy-vs-computed',T,'What is the difference between a `lazy var` and a computed property?',"""A lazy var computes **once** on first access and stores the result; a computed property recalculates **on every access** and stores nothing.""",NK)
c('static-vs-class',T,"What's the difference between `static` and `class` members?","""Both belong to the type, not instances. `static` members can't be overridden; `class` methods/computed properties (classes only) **can** be overridden by subclasses. `static` = `class final`.""",FS,NK)
c('static-properties',T,'What are static properties and methods?',"""Members shared by the type itself: `static let maxLevel = 99`, `Math.square(3)`. `static let` is lazily initialised once, thread-safely — the basis for the singleton pattern.""",NK)
c('final',T,'What does `final` do, and why use it?',"""Prevents a class from being subclassed or a member from being overridden. Communicates intent and enables **static dispatch** (faster calls). Consider making classes `final` by default.""",HWS,NK)
c('self-usage',T,'When would you use `self` in a method?',"""To disambiguate a property from a parameter (`self.name = name`), in escaping closures (where explicit `self` makes capture visible, unless using `[self]`), or to pass/return the instance. Otherwise it's implicit.""",FS)
c('upcast-downcast',T,'What is the difference between upcasting and downcasting?',"""Upcasting treats a subclass instance as its superclass — always safe, implicit or with `as`. Downcasting goes the other way and might fail — `as?` returns an optional, `as!` traps on failure.""",FS)
c('abstract-class',T,'Is there a way to create an abstract class?',"""No `abstract` keyword. Options: a protocol with default implementations (usually best), or a base class whose methods call `fatalError("subclass must override")` with an `init` that isn't public.""",FS)
c('singleton',T,'How do you implement a singleton, and when is it a good idea?',"""`final class Settings { static let shared = Settings(); private init() {} }` — `static let` guarantees lazy, thread-safe single initialisation and `private init` prevents other instances. Good for truly global resources; overuse hurts testability — prefer dependency injection.""",HWS,NK)
# ---------------- Access control
T='Access control'
c('access-control',T,'What access levels does Swift have?',"""From most to least open: `open` (subclass/override outside the module), `public`, `internal` (the **default**: whole module), `fileprivate` (the file), `private` (the enclosing declaration + its same-file extensions). `private(set)` restricts only the setter.""",TU,NK)
c('open-vs-public',T,'What is the difference between `open` and `public`?',"""Both are visible outside the module, but only `open` classes can be **subclassed** and `open` members **overridden** outside it. `public` lets other modules use but not extend.""",FS,NK)
c('fileprivate-vs-private',T,'What is the difference between `fileprivate` and `private`?',"""`private` is visible within the enclosing declaration and its extensions **in the same file**; `fileprivate` is visible anywhere in the file.""",FS)
c('private-set','Access control','What does `private(set)` do?',"""Keeps the getter at the property's access level but makes the setter private: outsiders can read, only the type can write. Ideal for exposing state that must change only through methods.""",)
# ---------------- Protocols
T='Protocols'
c('protocols',T,'What is a protocol and what is it for?',"""A blueprint of requirements — methods, properties, initialisers, associated types — that classes, structs and enums adopt. Code can depend on the protocol instead of a concrete type, enabling polymorphism, testing with mocks and generic algorithms.""",TU,HWS,NK)
c('protocol-vs-class',T,"What's the difference between a protocol and a class? Is it like a Java interface?","""A class is a concrete reference type with storage and inheritance; a protocol only states requirements. Unlike Java interfaces, Swift protocols can be adopted by value types, have associated types, be extended retroactively and get default implementations via extensions.""",FS)
c('protocol-extension',T,'What is a protocol extension?',"""An extension on a protocol that adds **default implementations** or new methods for every conforming type: `extension Collection { var isNotEmpty: Bool { !isEmpty } }`. Can be constrained with `where`.""",NK,HWS)
c('extension-vs-protocol-extension',T,'What is the difference between an extension and a protocol extension?',"""An extension adds functionality to **one** concrete type. A protocol extension adds it to **every** type that conforms to the protocol — and methods not declared as requirements are statically dispatched.""",HWS)
c('pop',T,'What is protocol-oriented programming?',"""Designing around protocols + extensions + value types instead of class hierarchies: small focused protocols, default behaviour in extensions, composition over inheritance. Benefits: works with structs, retroactive conformance, easy mocking. Drawbacks: can make type relationships complex and harder to debug.""",TU,HWS,NK)
c('protocol-composition',T,'What is protocol composition?',"""Combining protocols into one requirement with `&`: `func save(_ x: Codable & Identifiable)` or `typealias Model = Codable & Hashable`. You can include a class too: `UIView & Themeable`.""",TU)
c('associated-types',T,'What are associated types in protocols?',"""Placeholders a protocol declares with `associatedtype Item` that each conforming type fills in (often inferred). They make protocols generic — `Collection.Element`. Constrain them with `where` clauses.""",TU,NK)
c('equatable-hashable',T,'What is the difference between `Equatable` and `Hashable`?',"""`Equatable` requires `==`. `Hashable` refines it and requires `hash(into:)` so values can be `Set` elements or `Dictionary` keys. Both are synthesised for structs/enums whose members conform. Equal values **must** hash equally.""",NK)
c('comparable',T,'How do you make a type Comparable?',"""Conform to `Comparable` and implement `static func <`. You get `>`, `<=`, `>=`, `min`, `max`, `sorted()` for free. Enums without associated values get synthesised `Comparable` by case order.""",)
c('delegation',T,'How would you explain delegation?',"""One object hands off some responsibilities to another via a protocol: `protocol DownloaderDelegate: AnyObject { func didFinish(_ data: Data) }`, stored as `weak var delegate` (to avoid cycles). It decouples the worker from whoever reacts to its events.""",HWS,TU)
c('dependency-injection',T,'How do you implement dependency injection?',"""Pass dependencies in instead of creating them inside: initialiser injection (preferred), property injection or method injection, usually typed as protocols so tests can supply fakes. Property wrappers or containers can automate it.""",HWS,TU,NK)
c('conditional-conformance',T,'What are conditional conformances?',"""A generic type conforms to a protocol only when its type parameters do: `extension Array: Equatable where Element: Equatable`. That's why `[Int]` is Equatable but `[SomeNonEquatable]` isn't.""",HWS,NK)
c('self-vs-Self',T,"What's the difference between `self` and `Self`?","""`self` is the current **instance** (or the type itself inside static methods). `Self` is the current **type** — in protocols it means "the conforming type" (`static func make() -> Self`), in classes the dynamic type.""",FS,HWS,TU)
c('any-anyobject',T,'What is the difference between `Any` and `AnyObject`?',"""`Any` can hold an instance of any type — structs, enums, functions, optionals. `AnyObject` holds only class instances. Using them discards static type information, so you need casts to get it back.""",TU,NK)
c('type-casting',T,'What is type casting, and how do `is`, `as`, `as?` and `as!` differ?',"""`is` checks a type (`Bool`). `as` does guaranteed conversions (upcasts, literal bridging). `as?` attempts a downcast and returns an optional. `as!` force-downcasts and traps on failure.""",DI,FS,TU,NK)
c('existential-any',T,'What does `any Protocol` mean?',"""An **existential** — a box that can hold any conforming value, whose concrete type can change at runtime (`var shapes: [any Shape]`). It costs dynamic dispatch and allocation, and exposes only the protocol's members.""",)
c('opaque-types',T,'What are opaque return types (`some`)?',"""`func make() -> some Shape` returns one **specific** concrete type that the caller doesn't get to see, but the compiler does — preserving type identity (so associated types and `Self` requirements work) while hiding implementation. It's "reverse generics": the callee picks the type.""",TU,HWS,NK)
c('opaque-vs-generics',T,'How do opaque return types compare with generics?',"""With generics (`func f<T: Shape>(_: T)`) the **caller** chooses the concrete type. With `some Shape` as a return type the **implementation** chooses it. `some` in parameter position is sugar for a generic parameter.""",TU)
c('type-erasure',T,'What is type erasure and when would you use it?',"""Wrapping values of different concrete types behind one concrete wrapper type, e.g. `AnyPublisher`, `AnyHashable`, or your own `AnyShape` storing closures forwarded to the wrapped value. Historically needed for protocols with associated types; `any P<T>` covers many cases now.""",HWS,TU,NK)
c('dynamic-member-lookup',T,'What is `@dynamicMemberLookup`?',"""Lets a type resolve `value.anything` through `subscript(dynamicMember:)` — with `String` members (dynamic, e.g. JSON wrappers) or type-safe `KeyPath` members (forwarding wrappers).""",NK)
c('method-dispatch',T,'How does method dispatch work in Swift?',"""**Static/direct** dispatch for structs, enums, `final`, `private` and protocol-extension-only methods; **table (vtable/witness table)** dispatch for overridable class methods and protocol requirements; **message** dispatch for `@objc dynamic`. A method declared only in a protocol extension is statically dispatched — calling it through the protocol type ignores a conforming type's own version.""",NK)
# ---------------- Extensions
c('extensions','Extensions','What are extensions used for?',"""Adding computed properties, methods, initialisers, subscripts, nested types and protocol conformances to existing types — including ones you don't own like `Int` or `String`. They can't add stored properties or override existing members.""",FS,NK)
# ---------------- Generics
T='Generics'
c('generics',T,'What are generics and why are they useful?',"""Code written once for any type satisfying constraints: `func swapValues<T>(_ a: inout T, _ b: inout T)`, `struct Stack<Element>`. They keep full type safety (no `Any` casts) and are specialised for performance. `Array`, `Dictionary`, `Optional` and `Result` are all generic.""",TU,HWS,NK)
c('generic-constraints',T,'How do you constrain generic types?',"""Constrain placeholders with protocols or superclasses — `<T: Comparable>` — and add `where` clauses for relationships: `where C.Element == Int`, `where T: Hashable & Codable`.""",)
c('phantom-types',T,'What are phantom types and when would you use them?',"""A generic parameter that's never stored — used only to tag a value at compile time: `struct ID<Entity> { let raw: UUID }` makes `ID<User>` and `ID<Order>` incompatible; `Distance<Meters>` can't be added to `Distance<Feet>`.""",HWS,TU,NK)
c('key-paths',T,'What are key paths?',"""Typed references to properties: `\\Person.name` is a `KeyPath<Person, String>`. Read with `p[keyPath: kp]`, write through `WritableKeyPath`. Great for generic sorting, `map(\\.name)` and bindings.""",HWS,TU,NK)
# ---------------- Memory
T='Memory management'
c('arc',T,'How does Swift manage memory (ARC)?',"""Automatic Reference Counting: each class instance tracks how many **strong** references point to it and is deallocated (running `deinit`) when the count reaches zero. Value types are copied/stack-allocated or inline and aren't reference counted themselves.""",TU,HWS,NK)
c('arc-vs-gc',T,'What is the difference between ARC and garbage collection?',"""ARC inserts retain/release at compile time and frees objects deterministically the moment the last reference goes; there are no GC pauses. The cost: it can't collect **cycles** by itself, so you must break them with `weak`/`unowned`.""",FS)
c('strong-reference',T,"What's a strong reference, and why do we need it?","""The default kind of reference: it keeps the object alive. Without at least one strong reference, ARC frees the object immediately.""",FS)
c('weak-unowned',T,'What is the difference between `weak` and `unowned`?',"""Both don't keep the object alive. `weak` is always an optional `var` and becomes `nil` when the object is freed — use when the referent can go away first. `unowned` is non-optional and assumes the referent outlives you; accessing it after deallocation traps.""",FS,HWS,TU,NK)
c('retain-cycle',T,'What is a retain cycle and how do you prevent it?',"""Two or more objects holding strong references to each other (or an object and a closure it stores), so counts never reach zero — a leak. Break one edge with `weak`/`unowned` (parent→child strong, child→parent weak; `[weak self]` in stored closures). `deinit` printing is a quick detector; Xcode's memory graph finds them.""",HWS,TU,NK)
c('memory-safety',T,'How does memory safety work in Swift?',"""Variables are initialised before use, arrays are bounds-checked, integer overflow traps, ARC prevents use-after-free, and the **law of exclusivity** forbids overlapping accesses (e.g. passing the same variable as two `inout` arguments) — enforced at compile time and at runtime.""",NK,TU)
c('ownership',T,'What is ownership in Swift (`~Copyable`, `consuming`, `borrowing`)?',"""Swift 5.9+ lets types opt out of copyability with `~Copyable`; such values have a single owner and are **moved**. Parameters can be `borrowing` (read-only access) or `consuming` (take ownership), and the `consume` operator ends a binding's lifetime early. It enables unique resources like file handles with compile-time guarantees.""",NK)
c('memory-leaks',T,'What causes memory leaks in Swift and how do you find them?',"""Mostly retain cycles: delegates held strongly, closures capturing `self` stored on `self`, parent/child references. Detect with `deinit` logging, Instruments' Leaks, or the Xcode memory graph; fix with `weak`/`unowned` capture.""",TU,HWS)
c('caching',T,'What is an efficient way to cache data in memory?',"""A dictionary for O(1) lookup plus an eviction policy — e.g. an LRU cache (dictionary + doubly linked list, O(1) get/put). `NSCache` gives automatic eviction under memory pressure. Memoisation caches pure function results.""",HWS)
c('memory-layout',T,"How does Swift's memory layout affect performance?","""Value types are stored inline (stack, or inside their container) with no reference counting; classes live on the heap with refcounts. `MemoryLayout<T>.size/stride/alignment` shows the layout; property order affects padding. Fewer heap allocations and less refcounting = faster.""",NK)
# ---------------- Concurrency
T='Concurrency'
c('async-await',T,'How does Swift handle asynchronous tasks?',"""Structured concurrency: `async` functions suspend at `await` without blocking threads; `async let` and `TaskGroup` run child tasks in parallel; `Task {}` starts unstructured work; cancellation is cooperative. Older code uses GCD (`DispatchQueue`) and completion handlers.""",TU)
c('actors',T,'How do you handle thread safety in Swift?',"""Modern: **actors** serialise access to their mutable state (calls from outside are `await`ed), and Swift 6's strict concurrency checking uses `Sendable` to prove data-race safety at compile time. Older approaches: serial `DispatchQueue`, locks (`NSLock`, `Mutex`).""",TU,NK)
c('dispatch-sync-async',T,'What is the difference between `DispatchQueue.async` and `sync`?',"""`async` schedules work and returns immediately; `sync` blocks the caller until the work finishes. Calling `sync` onto the queue you're already on (e.g. `main.sync` from main) deadlocks. A serial queue runs one task at a time in order.""",FS)
c('task-group',T,'What is a TaskGroup?',"""`withTaskGroup(of:)` / `withThrowingTaskGroup` spawns a dynamic number of child tasks and collects results as they finish (in **completion** order, not submission order). All children finish or are cancelled before the group returns.""",)
c('sendable',T,'What is `Sendable`?',"""A marker protocol for types safe to share across concurrency domains: value types of Sendable members, actors, immutable final classes. Swift 6 language mode makes non-Sendable sharing a compile **error**, which is why global mutable `var`s are flagged.""",)
# ---------------- Advanced features
T='Advanced features'
c('property-wrappers',T,'What are property wrappers? Give an example.',"""A `@propertyWrapper` type with a `wrappedValue` that encapsulates storage logic, reused as an attribute: `@Clamped(0...100) var volume = 50`, `@Trimmed var name`. Can expose a `projectedValue` via `$name`. SwiftUI's `@State` is one.""",TU,HWS,NK)
c('result-builders',T,'What are result builders?',"""A `@resultBuilder` type with static `buildBlock` (plus `buildOptional`, `buildEither`, `buildArray` …) that turns a sequence of statements in a closure into a single combined value — the DSL mechanism behind SwiftUI's view bodies and `RegexBuilder`.""",TU,HWS,NK)
c('codable',T,'What does `Codable` do?',"""`Codable` = `Encodable & Decodable`. The compiler synthesises encoding/decoding for types whose properties are Codable, so `JSONDecoder().decode(User.self, from: data)` just works. Customise with `CodingKeys`, `init(from:)` and `encode(to:)`.""",HWS,NK)
c('codable-keys',T,'Why do key decoding strategies and `CodingKeys` matter?',"""JSON rarely matches Swift naming. `decoder.keyDecodingStrategy = .convertFromSnakeCase` maps `first_name` → `firstName`; a `CodingKeys` enum renames/omits individual keys; custom `init(from:)` handles nesting, defaults and type mismatches.""",HWS,NK)
c('availability',T,'What do `#available` and `@available` do?',"""`@available(macOS 14, *)` marks declarations as needing an OS version; `if #available(macOS 14, *) { … }` checks at runtime and lets you use newer APIs in that branch. `@available(*, deprecated, message:)` deprecates your own APIs.""",HWS,TU)
c('compiler-directives',T,'What do `#if`, `#error`, `canImport()` and `targetEnvironment()` do?',"""Compile-time conditions: `#if DEBUG`, `#if os(macOS)`, `#if swift(>=6.0)`, `#if canImport(UIKit)`, `#if targetEnvironment(simulator)` include/exclude code. `#error("msg")` / `#warning("msg")` emit a diagnostic deliberately.""",HWS)
c('main-attribute',T,'What does the `@main` attribute do?',"""Marks the type that provides the program's entry point via a `static func main()` (sync or `async`). It replaces `main.swift` top-level code; SwiftUI's `App` and ArgumentParser use it.""",HWS)
c('hashing',T,'How would you calculate a secure hash for some data?',"""With CryptoKit: `SHA256.hash(data: Data(string.utf8))` returns a digest you can hex-encode. `Hasher`/`hashValue` are **not** secure or stable across runs — never use them for persistence or security.""",HWS)
c('file-manager',T,'How do you list files in a directory?',"""`FileManager.default.contentsOfDirectory(atPath:)` (or `contentsOfDirectory(at:includingPropertiesForKeys:)` with URLs); `enumerator(at:)` walks recursively. All throw, so handle errors.""",HWS)

import os
out = '/Users/shrishti/Desktop/varun_notes/swift-judge/content/concepts.json'
json.dump(C, open(out, 'w'), indent=1, ensure_ascii=False)
ids = [x['id'] for x in C]; assert len(ids) == len(set(ids))
print(len(C), 'concepts')
