"""Reference registry: topic key -> Swift book chapters, Apple docs, articles, and YouTube title searches.

Keys are the 5th field of each enrichment entry (authoring/enrichment/e*.py). Video searches are regexes
matched against video titles in authoring/research/all_videos.json, per creator, best match first.
"""
BOOK = 'https://docs.swift.org/swift-book/documentation/the-swift-programming-language/'
AD = 'https://developer.apple.com/documentation/'
SE = 'https://github.com/swiftlang/swift-evolution/blob/main/proposals/'

# key: (book chapter slugs, [(apple doc title, path under AD)], [(article title, url, source)], [video title regexes])
R = {
 'value-types': (['classesandstructures'], [('Choosing Between Structures and Classes', 'swift/choosing-between-structures-and-classes')], [], [r'struct.*class|class.*struct', r'value.*reference|reference.*value']),
 'constants': (['thebasics'], [], [], [r'\bvar\b.*\blet\b|\blet\b.*\bvar\b|constants', r'variables']),
 'types': (['thebasics'], [('Swift Standard Library', 'swift/swift-standard-library')], [], [r'type inference|data types|types in swift', r'basic data types']),
 'numbers': (['thebasics', 'advancedoperators'], [('Int', 'swift/int'), ('Double', 'swift/double')], [], [r'\bintegers?\b|\bdoubles?\b(?!-tap)|\bnumbers\b', r'overflow']),
 'basics': (['basicoperators', 'thebasics'], [('Bool', 'swift/bool')], [], [r'booleans?|operators', r'conditions?']),
 'strings': (['stringsandcharacters'], [('String', 'swift/string'), ('Character', 'swift/character')], [], [r'strings?', r'characters?']),
 'collections': (['collectiontypes'], [('Array', 'swift/array')], [], [r'arrays?', r'collections?']),
 'dictionaries': (['collectiontypes'], [('Dictionary', 'swift/dictionary')], [], [r'dictionar', r'collections?']),
 'sets': (['collectiontypes'], [('Set', 'swift/set')], [], [r'\bsets?\b', r'collections?']),
 'hashable': (['protocols'], [('Hashable', 'swift/hashable'), ('Equatable', 'swift/equatable')], [], [r'hashable', r'equatable']),
 'tuples': (['thebasics', 'functions'], [], [], [r'tuples?', r'multiple values|return.*values']),
 'ranges': (['basicoperators'], [('ClosedRange', 'swift/closedrange'), ('Range', 'swift/range')], [], [r'ranges?', r'loops?']),
 'conditionals': (['controlflow'], [], [], [r'conditions?|if statements?|\bif\b', r'ternary']),
 'switch': (['controlflow'], [], [], [r'switch', r'pattern match']),
 'loops': (['controlflow'], [], [], [r'\bloops?\b|for loops?|while', r'break|continue']),
 'functions': (['functions'], [], [], [r'functions?', r'parameters?|return']),
 'enums': (['enumerations'], [('CaseIterable', 'swift/caseiterable')], [], [r'\benums?\b|enumerations?', r'associated values?|raw values?']),
 'enums-deep': (['enumerations'], [], [], [r'indirect|recursive enum', r'\benums?\b']),
 'io': (['thebasics'], [('readLine(strippingNewline:)', 'swift/readline(strippingnewline:)')], [], [r'command[- ]line|terminal|readline', r'print']),
 'optionals': (['optionalchaining', 'thebasics'], [('Optional', 'swift/optional')], [], [r'optionals?', r'unwrap|guard|nil']),
 'errors': (['errorhandling'], [('Error', 'swift/error'), ('Result', 'swift/result')], [], [r'error handling|errors?|throw', r'do.*catch|try']),
 'closures': (['closures'], [], [], [r'closures?', r'escaping|capture|higher[- ]order']),
 'keypaths': (['expressions'], [('KeyPath', 'swift/keypath')], [], [r'key ?paths?', r'keypath']),
 'operators': (['advancedoperators'], [], [], [r'operators?', r'overload']),
 'structs': (['classesandstructures', 'properties', 'methods'], [], [], [r'structs?|structures?', r'mutating|properties']),
 'classes': (['inheritance', 'initialization', 'classesandstructures'], [], [], [r'class(es)?\b', r'inheritance|initiali[sz]']),
 'casting': (['typecasting'], [], [], [r'type cast|casting|\bas\?', r'\bAny\b']),
 'protocols': (['protocols'], [], [('Protocol-Oriented Programming in Swift (WWDC15)', 'https://developer.apple.com/videos/play/wwdc2015/408/', 'WWDC')], [r'protocols?', r'protocol[- ]oriented']),
 'extensions': (['extensions'], [], [], [r'extensions?', r'protocols?']),
 'access': (['accesscontrol'], [], [], [r'access control|private|public', r'encapsulation']),
 'memory': (['automaticreferencecounting'], [], [], [r'retain cycle|memory leak|weak self|\bweak\b', r'\bARC\b|memory']),
 'ownership': (['memorysafety'], [('Copyable', 'swift/copyable')], [('SE-0390: Noncopyable structs and enums', SE + '0390-noncopyable-structs-and-enums.md', 'Swift Evolution')], [r'noncopyable|ownership|consume', r'memory']),
 'generics': (['generics'], [], [], [r'generics?', r'protocols?']),
 'opaque': (['opaquetypes'], [], [('SE-0335: Introduce existential any', SE + '0335-existential-any.md', 'Swift Evolution')], [r'\bsome\b|opaque|\bany\b', r'generics?']),
 'advanced': (['attributes', 'advancedoperators'], [], [], [r'dynamic member|callasfunction|macros?|result builder', r'advanced']),
 'property-wrappers': (['properties'], [], [('SE-0258: Property Wrappers', SE + '0258-property-wrappers.md', 'Swift Evolution')], [r'property wrappers?', r'@State|@Published']),
 'result-builders': (['advancedoperators'], [('ViewBuilder', 'swiftui/viewbuilder')], [('SE-0289: Result builders', SE + '0289-result-builders.md', 'Swift Evolution')], [r'result builders?|viewbuilder', r'@ViewBuilder']),
 'collections-deep': (['generics'], [('Collection', 'swift/collection'), ('Sequence', 'swift/sequence')], [], [r'sequence|collection protocol|lazy', r'collections?']),
 'regex': (['stringsandcharacters'], [('Regex', 'swift/regex')], [('SE-0354: Regex literals', SE + '0354-regex-literals.md', 'Swift Evolution')], [r'regex', r'strings?']),
 'foundation': ([], [('Foundation', 'foundation')], [], [r'foundation|uuid|filemanager|cryptokit|attributed', r'data']),
 'caching': ([], [('NSCache', 'foundation/nscache')], [], [r'cach(e|ing)', r'memoiz']),
 'design': (['protocols'], [], [], [r'dependency injection|design patterns?|singleton', r'architecture']),
 'algorithms': (['collectiontypes', 'controlflow'], [], [], [r'algorithm|leetcode|interview|big[- ]o', r'data structures?']),
 'algorithms-pkg': ([], [], [('Swift Algorithms (GitHub)', 'https://github.com/apple/swift-algorithms', 'Apple open source')], [r'swift algorithms|algorithms package', r'algorithms?']),
 'data-structures': (['collectiontypes'], [], [], [r'data structures?|stack|queue', r'algorithm']),
 'interview': (['collectiontypes'], [], [], [r'interview|coding challenge|leetcode', r'algorithm']),
 'concurrency': (['concurrency'], [('Swift Concurrency', 'swift/concurrency')], [('SE-0296: async/await', SE + '0296-async-await.md', 'Swift Evolution')], [r'async|await|actors?|task', r'concurrency|threads?']),
 'evolution': ([], [], [('Swift Evolution proposals', 'https://www.swift.org/swift-evolution/', 'swift.org')], [r'swift [56]\.\d|what.?s new in swift', r'new in swift']),
 'architecture': ([], [], [], [r'mvvm|architecture|dependency injection|clean', r'view ?model']),
 'testing': ([], [('Swift Testing', 'testing'), ('XCTest', 'xctest')], [], [r'unit test|testing|xctest', r'mock']),
 'swiftui-state': ([], [('Managing model data in your app', 'swiftui/managing-model-data-in-your-app'), ('State', 'swiftui/state')], [], [r'@State|@Binding|@Observable|observable|state|binding', r'environment|data flow']),
 'swiftui-composition': ([], [('View', 'swiftui/view'), ('ViewBuilder', 'swiftui/viewbuilder')], [], [r'viewbuilder|view modifier|some view|modifiers?', r'custom views?|extract']),
 'swiftui-lists': ([], [('List', 'swiftui/list'), ('ForEach', 'swiftui/foreach')], [], [r'\blists?\b|foreach|scroll ?view|search', r'swipe|delete']),
 'swiftui-navigation': ([], [('NavigationStack', 'swiftui/navigationstack')], [], [r'navigation|sheet|tab ?view|deep link', r'alert']),
 'swiftui-layout': ([], [('Layout fundamentals', 'swiftui/layout-fundamentals')], [], [r'layout|grid|stack|geometry|viewthatfits', r'frame|padding']),
 'swiftui-drawing': ([], [('Shape', 'swiftui/shape'), ('Color', 'swiftui/color')], [], [r'shapes?|path|colou?r|canvas', r'drawing']),
 'swiftui-animation': ([], [('Animation', 'swiftui/animation')], [], [r'animat', r'transition']),
 'swiftui-gestures': ([], [('Gestures', 'swiftui/gestures')], [], [r'gestures?|drag|magnif|rotation|long ?press', r'swipe']),
 'swiftui-controls': ([], [('Form', 'swiftui/form'), ('FocusState', 'swiftui/focusstate')], [], [r'forms?|textfield|focus|slider|stepper|picker', r'keyboard']),
 'swiftui-accessibility': ([], [('Accessibility fundamentals', 'swiftui/accessibility-fundamentals')], [], [r'accessibility|voiceover|dynamic type|locali[sz]', r'colou?rs?']),
 'formatting': ([], [('FormatStyle', 'foundation/formatstyle')], [], [r'format', r'dates?|numbers?|currency']),
 'dates': ([], [('Calendar', 'foundation/calendar'), ('Date', 'foundation/date')], [], [r'dates?|calendar|time ?zones?', r'format']),
 'codable': (['protocols'], [('Encoding and Decoding Custom Types', 'foundation/encoding-and-decoding-custom-types'), ('JSONDecoder', 'foundation/jsondecoder')], [], [r'codable|json|decod', r'api']),
 'networking': ([], [('URLSession', 'foundation/urlsession')], [], [r'network|urlsession|api call|download json|fetch', r'json']),
 'persistence': ([], [('UserDefaults', 'foundation/userdefaults'), ('FileManager', 'foundation/filemanager')], [], [r'userdefaults|appstorage|filemanager|save data|persist', r'cach']),
 'combine': ([], [('Combine', 'combine')], [], [r'combine|publisher|subscriber', r'@Published|sink']),
 'coredata': ([], [('Core Data', 'coredata')], [], [r'core ?data', r'persist']),
 'swiftdata': ([], [('SwiftData', 'swiftdata')], [], [r'swift ?data', r'@Model|query']),
 'location': ([], [('Core Location', 'corelocation'), ('MapKit', 'mapkit')], [], [r'map|location', r'annotation']),
 'security': ([], [('CryptoKit', 'cryptokit')], [], [r'crypto|encrypt|keychain|security', r'hash']),
 'platform': ([], [('WidgetKit', 'widgetkit'), ('StoreKit', 'storekit'), ('User Notifications', 'usernotifications')], [], [r'widget|storekit|in-app purchase|notification|healthkit|charts?', r'subscription']),
 'backend': ([], [], [('Firebase for Apple platforms', 'https://firebase.google.com/docs/ios/setup', 'Firebase')], [r'firebase|firestore|auth', r'backend|pagination']),
 'uikit': ([], [('UIKit', 'uikit'), ('Updating collection views using diffable data sources', 'uikit/updating-collection-views-using-diffable-data-sources')], [], [r'uikit|diffable|collection ?view|table ?view', r'uikit']),
 'product': ([], [('Human Interface Guidelines', 'https://developer.apple.com/design/human-interface-guidelines')], [], [r'a/?b test|app store|rating|review|infinite scroll|offline|universal link|onboarding', r'grow|users?']),
 'performance': ([], [('Image I/O', 'imageio')], [], [r'performance|instruments|memory|image', r'optimi[sz]']),
 'cs193p': ([], [], [('Stanford CS193p — Developing Apps for iOS', 'https://cs193p.stanford.edu', 'Stanford')], []),
}
