# (impact, jsBridge, compass[(kind, q)], transcript keywords, reference key)
E = {}
E['predict-array-copy'] = ('c', """In JS, `const b = a` for an array copies the **reference** — `b.push(4)` changes `a` too. Swift's `Array` is a **value type**: `var b = a` gives `b` its own logical copy, and mutating `b` never touches `a`. It's cheap because storage is shared until one side writes (copy-on-write), so it behaves like `[...a]` but without paying for the copy up front.""",
 [('js', "React forces you to write `[...items, x]` so state changes are detectable. Why does SwiftUI never need that spread, and what does it do instead to notice the change?"),
  ('practice', "A view model hands its `items` array to a background task that sorts it. Can the task corrupt the view model's array? What would change if `items` were an `NSMutableArray`?"),
  ('java', "Java's `ArrayList` is a reference type, like JS arrays. What bugs does Java's defensive-copy idiom (`new ArrayList<>(list)`) guard against that Swift arrays rule out by construction?"),
  ('edge', "If copying is lazy, when exactly is the copy made — at `var b = a`, or at the first `b.append`? How could you prove it without a debugger?")],
 ['value type', 'copy', 'array'], 'value-types')
E['predict-struct-vs-class'] = ('c', """JS has only one kind of object, and it's always shared by reference. Swift makes you choose: `struct` (copied on assignment, like a JS primitive) or `class` (shared, like a JS object). Most Swift model types are structs, which is the opposite of JS's default.""",
 [('js', "In JS, `Object.freeze` and immutable libraries (Immer, Immutable.js) exist to bolt value semantics onto objects. What does Swift get \"for free\" by building value semantics into the language, and what does it cost?"),
  ('practice', "Your `User` model is displayed in five screens. Would you make it a struct or a class, and what happens to the other four screens when one screen edits the user?"),
  ('contrast', "A struct holding a class reference: is it still a value type? What happens when you copy it and mutate the object inside?"),
  ('java', "Java 16 added `record`s. Are they value types like Swift structs, or immutable references? What's the practical difference?")],
 ['struct', 'class', 'reference type'], 'value-types')
E['swap-values'] = ('e', """JS can't pass a variable by reference at all — you'd return a new pair or mutate an object's property. Swift's `inout` looks like pass-by-reference but is actually **copy-in copy-out**: the value is copied in, modified, then written back when the function returns. That's why `&` is required at the call site and why overlapping `inout` access is a compile error.""",
 [('js', "The JS idiom `[a, b] = [b, a]` also works in Swift as `(a, b) = (b, a)`. So why does `swap(_:_:)` exist, and why does `swapAt` exist on arrays?"),
  ('edge', "What happens if you call `swap(&arr[0], &arr[1])`? Why does the compiler reject it, and how does `swapAt` get around the rule?"),
  ('java', "Java is always pass-by-value (object references are values). Is Swift's `inout` pass-by-reference? What can you observe that distinguishes copy-in copy-out from true references?"),
  ('practice', "Where do you see `inout` in real iOS code? Hint: `mutating` methods and `reduce(into:)` are built on the same idea.")],
 ['inout', 'swap', 'ampersand'], 'functions')
E['runtime-constant'] = ('c', """JS `const` must be initialised on the same line. Swift `let` only has to be assigned **exactly once before use**, so you can declare it and assign it in each branch of an `if`/`switch`. The compiler proves every path assigns it exactly once (definite initialisation).""",
 [('js', "JS devs often write `let x; if (...) x = 1; else x = 2;` and lose immutability. Swift keeps `let`. What analysis does the compiler do that TypeScript doesn't?"),
  ('contrast', "`let` vs `if`-expression (`let x = if c { 1 } else { 2 }`): when is each clearer, and which works when branches need several statements?"),
  ('edge', "Does `let` on a class instance make the object immutable? What about `let` on a struct with `var` properties?"),
  ('practice', "Why does Xcode warn \"variable was never mutated; consider changing to let\"? What does preferring `let` buy in a large codebase, beyond style?")],
 ['let', 'constant', 'var'], 'constants')
E['diag-let-reassign'] = ('c', """Same idea as JS `const`, but it goes further: in JS, `const obj = {}` still allows `obj.x = 1`. In Swift, `let` on a **struct** freezes the whole value, including its properties. On a class it freezes only the reference, just like JS `const`.""",
 [('js', "`const arr = []; arr.push(1)` is legal JS. Is `let arr: [Int] = []; arr.append(1)` legal Swift? Why is the answer different?"),
  ('contrast', "`let` on a class instance vs a struct instance: which properties can you still change in each case?"),
  ('java', "Java's `final` is closest to which Swift case, `let` on a class or on a struct?"),
  ('practice', "When the compiler says \"cannot assign to value: 'x' is a 'let' constant\" inside a SwiftUI view, what's usually the real fix — `var`, `@State`, or something else?")],
 ['let', 'constant', 'cannot assign'], 'constants')
E['type-inference-describe'] = ('c', """Like TypeScript, Swift infers types from literals, but the defaults differ. `42` is `Int`, `3.0` is `Double` (JS has only `number`), and `1...3` is a `ClosedRange<Int>`. Inference is also **bidirectional**: `let x: Double = 42` makes the literal a Double, which TS can't do.""",
 [('js', "TypeScript infers `const x = 42` as the literal type `42`. What does Swift infer, and why doesn't Swift have literal types at all?"),
  ('edge', "Why can type-checking `let x = 1 + 2.0 + 3 + 4.5 + ...` with many literals be slow or fail with \"expression too complex\"? What does that reveal about how literals are inferred?"),
  ('contrast', "`[1, 2]` is `[Int]` but `[1, \"a\"]` is an error without annotation. How is that different from TS inferring `(number | string)[]`?"),
  ('practice', "In a large app, when is an explicit type annotation worth it despite inference: compile times, public APIs, or readability?")],
 ['type inference', 'infer', 'type of'], 'types')
E['numeric-literals'] = ('e', """JS has `0b`, `0o`, `0x` and `1_000_000` numeric separators too. The difference is that Swift literals have no type until context gives them one, so `0xFF` can become a `UInt8`, `Int` or `Double`.""",
 [('js', "In JS, `0.1` and `1` are both `number`. In Swift, can `let x: UInt8 = 256` compile? What does the error teach about literal typing?"),
  ('practice', "Where do hex literals show up in iOS work? Think colors (`0xFF8800`), bit flags in `OptionSet`, and binary protocols."),
  ('edge', "Why does `let big = 1_0_0` compile? Are underscores just ignored, or are there rules?"),
  ('contrast', "Integer literal vs `Int(\"0xFF\", radix:)` parsing at runtime: which catches mistakes earlier?")],
 ['hexadecimal', 'binary', 'literal'], 'numbers')
E['to-binary-string'] = ('e', """The same as JS `n.toString(16)` / `parseInt(s, 16)`. Swift spells them `String(n, radix: 16)` and the failable `Int(s, radix: 16)`, which returns an optional instead of JS's `NaN`.""",
 [('js', "`parseInt('12abc')` returns 12 in JS. What does `Int(\"12abc\")` return in Swift, and which behaviour do you want in a payment form?"),
  ('edge', "`String(Int.min, radix: 2)`: does a negative number come out as two's complement or with a minus sign? Why might a bit-twiddler be surprised?"),
  ('practice', "Where would you format numbers in a radix in an app: color hex strings, debug dumps of flags, short IDs?"),
  ('contrast', "`String(n, radix:)` vs `n.formatted()`: when is each right? Which respects the user's locale?")],
 ['radix', 'string', 'binary'], 'numbers')
E['overflow-safe-add'] = ('c', """In JS, `Number.MAX_SAFE_INTEGER + 2` silently loses precision, and there's no integer overflow at all, just floats. Swift's `Int` is a real 64-bit integer, and `+` **traps** (crashes) on overflow instead of wrapping silently. `addingReportingOverflow` lets you detect it.""",
 [('js', "Is Swift crashing on overflow better or worse than JS silently becoming imprecise? Think about a bank balance, then a game score."),
  ('java', "Java's `int` silently wraps on overflow (`Integer.MAX_VALUE + 1` is negative). Which of Java, JS and Swift would you trust for a money calculation, and why?"),
  ('practice', "Where could overflow realistically happen in an iOS app: timestamps in ms, file sizes, counters? When would you use `Int64` or `Decimal` instead?"),
  ('edge', "Is overflow checked in `-Ounchecked` builds? What does that say about relying on a crash as a safety net?")],
 ['overflow', 'crash', 'integer'], 'numbers')
E['wrapping-hash'] = ('e', """In JS you'd write `(hash * 33 + c) | 0` or `Math.imul` to force 32-bit wrapping. Swift makes wrapping explicit with `&*`, `&+` and `&-`: plain operators trap on overflow, and the ampersand variants wrap on purpose.""",
 [('js', "JS hash functions often use `>>> 0` to get an unsigned 32-bit number. What's the Swift equivalent, and why does Swift need separate `UInt32` and `Int` types for it?"),
  ('contrast', "Why not use Swift's built-in `hashValue` for this? What changes between app launches?"),
  ('practice', "When have you needed a stable hash in an app: cache keys, A/B bucketing, content-addressed files? What goes wrong if the hash changes between releases?"),
  ('edge', "Is `&*` faster than `*`? What work does the checked version do that the wrapping version skips?")],
 ['overflow', 'wrapping', 'hash'], 'numbers')
E['float-compare'] = ('c', """It's identical to JS: `0.1 + 0.2 !== 0.3` because both use IEEE-754 doubles. What's new in Swift is that `Float` (32-bit) and `Double` (64-bit) are separate types, and `Decimal` exists for money.""",
 [('js', "JS devs reach for `Number.EPSILON`. Why is a fixed epsilon wrong for large values, and why does this problem scale by magnitude?"),
  ('practice', "How should an app store money: `Double`, `Decimal`, or integer cents? What does Apple's `formatted(.currency(code:))` expect?"),
  ('edge', "`Double.nan == Double.nan` is false. What does that do to a `Set<Double>` or to sorting an array containing NaN?"),
  ('contrast', "`Float` vs `Double` vs `CGFloat`: why does UI code use `CGFloat`, and when did it become interchangeable with `Double`?")],
 ['floating point', 'double', 'precision'], 'numbers')
E['digit-sum'] = ('e', """In JS you'd use `String(Math.abs(n)).split('').reduce(...)`. Swift can do the same with `String(n).compactMap(\\.wholeNumberValue).reduce(0, +)`, or with plain arithmetic. Watch for `abs(Int.min)`, which traps in Swift; in JS it's just a float.""",
 [('edge', "What does `abs(Int.min)` do? How does `n.magnitude` (a `UInt`) avoid the problem?"),
  ('contrast', "Arithmetic `n % 10` loop vs converting to a string: which is faster, and which is clearer? Does it matter at this scale?"),
  ('js', "`Array.from(String(n))` vs Swift's `String` being a collection directly: what does Swift let you skip?"),
  ('practice', "Checksum-style digit sums show up in credit-card (Luhn) validation. Where would that validation live in an iOS app?")],
 ['digits', 'reduce', 'sum'], 'numbers')
E['fahrenheit'] = ('c', """In JS, `100 * 9 / 5` is `180` because everything is a float. In Swift, `Int / Int` is **integer division** (truncating) and you can't mix `Int` and `Double` without an explicit conversion. There's no implicit numeric coercion at all.""",
 [('js', "JS silently coerces `\"5\" * 2` to 10. Swift won't even convert `Int` to `Double` implicitly. Which bugs does that strictness prevent, and what does it cost in ergonomics?"),
  ('edge', "`37 * 9 / 5 + 32` in integer maths gives 98, not 98.6. Where else might silent truncation hide in UI code, like a percent-complete bar?"),
  ('java', "Java does promote `int` to `double` automatically in `int * double`. Why did Swift choose not to?"),
  ('practice', "Should unit conversion be hand-written at all? Look up `Measurement<UnitTemperature>`: what does it give you for free, such as localisation?")],
 ['integer division', 'double', 'convert'], 'numbers')
E['bool-toggle-xor'] = ('e', """JS has truthiness: `true + true === 2` and `if (count)` works. Swift's `Bool` is not a number and nothing is truthy, so `if count` doesn't compile. You write `count > 0`, or count with `filter { $0 }.count`.""",
 [('js', "List three JS truthiness bugs (`0`, `\"\"`, `NaN`) that Swift's `Bool` rules make impossible. Is anything lost?"),
  ('contrast', "`a != b` works as XOR for two Bools. Why doesn't it generalise to \"exactly one of three\"?"),
  ('practice', "A settings screen has three mutually exclusive toggles. Would you model them as three Bools or as one enum? What does the enum prevent?"),
  ('edge', "`Bool.toggle()` is a mutating method. Why is that nicer in SwiftUI (`isOn.toggle()`) than `isOn = !isOn`?")],
 ['bool', 'true', 'false'], 'basics')
E['leap-year'] = ('e', """JS: `y % 4 === 0 && ...`. Swift has `isMultiple(of:)`, which reads better and is safe for `Int.min` and zero. For real calendars you'd never hand-roll this, and you'd ask `Calendar` instead.""",
 [('practice', "Why should app code use `Calendar.current.range(of: .day, in: .month, for:)` rather than a leap-year formula? Which calendars does the user's device support?"),
  ('js', "JS's `Date` has no calendar system awareness beyond Gregorian. How does Foundation's `Calendar` differ, for example for the Japanese or Hebrew calendars?"),
  ('edge', "Why does `isMultiple(of: 0)` not crash when `x % 0` does?"),
  ('contrast', "Nested `if` vs one boolean expression vs a `switch` on `(y%4, y%100, y%400)`: which is easiest to audit?")],
 ['leap year', 'divisible', 'multiple'], 'basics')
E['character-count'] = ('c', """JS strings are UTF-16: `"é".length` can be 1 or 2, and emoji are 2+. Swift's `count` counts **grapheme clusters**, what a human sees as one character, so `"👨‍👩‍👧".count == 1`. The `utf8`, `utf16` and `unicodeScalars` views give you the JS-style counts when an API needs them.""",
 [('js', "An `NSString`/`UITextField` limit of 140 characters: does it use Swift `count` or `utf16.count`? What does JS's `maxlength` count?"),
  ('practice', "A backend validates length in bytes (UTF-8) and the app in characters. Which user input breaks the contract?"),
  ('edge', "Why is `String.count` O(n) in Swift but `.length` O(1) in JS? What's the consequence of calling `count` in a loop?"),
  ('java', "Java strings are UTF-16 like JS. How does Java's `codePointCount` compare with Swift's grapheme count for flags and family emoji?")],
 ['unicode', 'character', 'grapheme'], 'strings')
E['reverse-words'] = ('e', """The same as JS `s.trim().split(/\\s+/).reverse().join(' ')`. Swift's `split(separator: " ")` drops empty pieces by default, which `components(separatedBy:)` doesn't, and `reversed()` returns a lazy view rather than a new array.""",
 [('contrast', "`split(separator:)` vs `components(separatedBy:)`: which keeps empty strings, and which returns `Substring`s?"),
  ('js', "JS `.reverse()` mutates the array in place. Swift `reversed()` doesn't. What does it return, and why is that cheap?"),
  ('edge', "What does `Substring` keep alive in memory? When should you convert back with `String(sub)`?"),
  ('practice', "Word splitting on spaces fails for Chinese or Japanese. Which Foundation API enumerates words properly?")],
 ['split', 'reversed', 'words'], 'strings')
E['palindrome'] = ('e', """JS would lowercase and strip with a regex like `/[^a-z0-9]/gi`, which is ASCII-only. Swift's `Character.isLetter` and `isNumber` are Unicode-aware, so accented letters and other scripts work, and `lowercased()` handles more than ASCII.""",
 [('js', "Your JS regex `[a-z0-9]` breaks for \"Ésope reste ici et se repose\". What does Swift's `isLetter` do differently?"),
  ('edge', "Is `Array(s) == Array(s).reversed()` correct for strings with combining accents? What if one side uses a precomposed é and the other e + ◌́?"),
  ('contrast', "Two-pointer on `String.Index` vs converting to `[Character]` first: memory vs simplicity. Which would you ship?"),
  ('practice', "Case-insensitive, diacritic-insensitive comparison in search bars: what does `localizedStandardContains` do that `lowercased().contains` misses?")],
 ['palindrome', 'lowercased', 'letter'], 'strings')
E['string-index-nth'] = ('c', """JS gives `str[5]` in O(1) over UTF-16 units, which can split an emoji. Swift **refuses integer subscripts** on `String` because characters have variable width. You walk with `index(_:offsetBy:limitedBy:)`, which makes the O(n) cost visible.""",
 [('js', "JS `str[i]` is O(1) but can return half an emoji. Swift makes it O(n) and correct. Which trade-off would you choose for a text editor?"),
  ('practice', "If you need random access, like highlighting search matches, what's the idiomatic Swift approach: `Array(string)`, storing `String.Index` values, or `NSRange`?"),
  ('edge', "Can you use an index from one string on another string, or on a mutated copy? What happens?"),
  ('java', "Java's `charAt(i)` returns a UTF-16 unit like JS. Why did Swift decide the ergonomic loss was worth it?")],
 ['string index', 'index', 'offset'], 'strings')
E['vowel-count'] = ('e', """In JS, `new Set('aeiou')` then `.has(c)`. Swift's `Set<Character>` is the same, and `"aeiou".contains(c)` also works since `String` is a collection. A set literal (`let vowels: Set<Character> = ["a", …]`) makes the O(1) intent explicit.""",
 [('contrast', "For 5 vowels, is a `Set` really faster than a `String.contains` scan? When does the set win?"),
  ('js', "JS `Set` keeps insertion order. Does Swift's `Set`? What does that mean for printing or tests?"),
  ('edge', "Is \"É\" a vowel here? How would you make the check diacritic-insensitive?"),
  ('practice', "Filtering characters shows up in input validation, like allowed characters in a username. Where would you use `CharacterSet` instead?")],
 ['set', 'vowels', 'contains'], 'strings')
E['caesar-cipher'] = ('e', """JS does `String.fromCharCode(((c - 65 + k) % 26 + 26) % 26 + 65)`. Swift works on `Character.asciiValue` (`UInt8?`) and `UnicodeScalar`. The `%` remainder can be negative in both languages, so the double-mod trick carries over.""",
 [('edge', "Why is `asciiValue` optional? What happens to \"é\" or \"🙂\" in your cipher?"),
  ('js', "Both JS and Swift `%` return negative results for negative operands. Which languages have a true modulo, and how would you write one in Swift?"),
  ('contrast', "Mapping over `unicodeScalars` vs `Character`s: which is faster, and which is more correct?"),
  ('practice', "Real apps must never roll their own crypto. Which Apple framework do you use instead, and what does it give you?")],
 ['ascii', 'character', 'shift'], 'strings')
E['interpolation-receipt'] = ('c', """Like JS template literals, `"\\(x)"` works like `` `${x}` ``, but Swift interpolation is type-checked and extensible (`DefaultStringInterpolation`). Money should be integer cents or `Decimal`, never `Double`, which is the same advice as in JS.""",
 [('js', "JS template tags (`` sql`...` ``) customise interpolation. What is Swift's equivalent, and what can a custom `appendInterpolation` do?"),
  ('practice', "In production, would you build `\"$\\(dollars).\\(cents)\"` by hand or use `formatted(.currency(code: \"USD\"))`? What breaks for a user in Germany?"),
  ('edge', "What does `String(format: \"%02d\", cents)` do if you pass an `Int64` on some platforms? Why is `String(format:)` less safe than interpolation?"),
  ('contrast', "Integer cents vs `Decimal` vs `Double`: which one does StoreKit's `Product.price` use?")],
 ['interpolation', 'format', 'string'], 'strings')
E['multiline-raw-strings'] = ('e', """JS has `String.raw` and template literals for multiline strings. Swift uses `#"…"#` for raw strings (interpolate with `\\#(x)`) and `\"\"\"…\"\"\"` for multiline strings, where the closing delimiter's indentation is stripped from every line.""",
 [('js', "`String.raw` and Swift's `#\"...\"#` both disable escapes. Why does Swift need the `\\#(x)` interpolation syntax rather than plain `\\(x)`?"),
  ('practice', "Raw strings shine for regex and JSON fixtures in tests. Rewrite `\"\\\\d+\\\\.\\\\d+\"` as a raw string. Which is easier to review?"),
  ('edge', "How do you put `\"#` inside a raw string? What do `##\"…\"##` delimiters do?"),
  ('contrast', "A multiline string literal vs a `.json` file in the test bundle: when is each the better fixture?")],
 ['raw string', 'multiline', 'backslash'], 'strings')
E['predict-interpolation'] = ('e', """`print` is `console.log`. `debugPrint` is closer to `console.dir` or `JSON.stringify`: it shows quotes and escapes. `separator:` and `terminator:` control spacing and the trailing newline, which `console.log` can't.""",
 [('contrast', "`CustomStringConvertible` vs `CustomDebugStringConvertible`: which one does `print` use, which does `debugPrint` use, and which does the debugger's `po` use?"),
  ('practice', "Why shouldn't shipping app code use `print` at all? What does `Logger` from `os` give you: privacy redaction, levels, Console.app?"),
  ('js', "`console.log(obj)` shows an interactive tree. What does `print(someStruct)` show, and how does `dump()` compare?"),
  ('edge', "Does `print` flush immediately? When does output get lost when an app crashes?")],
 ['print', 'debug', 'terminator'], 'strings')
E['acronym'] = ('e', """JS: `s.split(/[\\s-]+/).filter(Boolean).map(w => w[0].toUpperCase()).join('')`. Swift's `split(whereSeparator:)` drops empties for you, and `compactMap(\\.first)` avoids JS's `undefined[0]` crash on empty strings.""",
 [('contrast', "`map` vs `compactMap` vs `flatMap` on a `[String]`: what does each return when some words are empty?"),
  ('js', "`w[0]` on an empty JS string is `undefined`, and then `.toUpperCase()` throws. How does Swift's `first` being optional change the shape of the code?"),
  ('edge', "What does `\"ǆ\".uppercased()` return? Can uppercasing change a string's length?"),
  ('practice', "Initials avatars (\"VS\" for Varun Sharma) need the same logic. What goes wrong for names in scripts without case?")],
 ['compactmap', 'first', 'uppercased'], 'strings')
E['echo-stdin-upper'] = ('e', """Like Node's `readline` interface, but synchronous: `readLine()` blocks and returns `String?`, where `nil` means EOF. iOS apps never read stdin. This is how command-line Swift tools work (Swift Argument Parser).""",
 [('js', "Node's readline is event-based and async. Why can a Swift CLI get away with a blocking `while let line = readLine()`?"),
  ('practice', "Where would you write Swift CLIs as an iOS engineer: build scripts, code generators, SPM plugins?"),
  ('edge', "Does `readLine()` strip `\\r\\n` from Windows-style input? What does `strippingNewline:` do?"),
  ('contrast', "`readLine()` vs `FileHandle.standardInput.bytes.lines` (async): when would you need the async version?")],
 ['readline', 'input', 'command line'], 'io')
E['running-sum'] = ('e', """JS `reduce` can build a running sum. Swift has no `scan` in the standard library, but swift-algorithms' `reductions` is exactly `scan`. The idiomatic hand-written version is a `for` loop with `append`, or `reduce(into:)`.""",
 [('contrast', "`reduce` vs `reduce(into:)`: why is `into:` faster for building arrays? What copying does plain `reduce` do?"),
  ('js', "JS `reduce((acc, x) => [...acc, acc.at(-1) + x], [])` is O(n²). Is the Swift version with `+` the same? Why?"),
  ('practice', "Running totals appear in charts, like a cumulative steps graph in HealthKit. Where would you compute them: the view, the view model, or the query?"),
  ('edge', "What happens with `[Int.max, 1]`? Should the result type be `Int` or something else?")],
 ['reduce', 'running', 'sum'], 'collections')
E['second-largest'] = ('e', """In JS you'd return `undefined` or `-Infinity`. Swift returns `Int?`, so the caller is forced to handle "no answer". `Set(nums).sorted().dropLast().last` is the short version, but a one-pass scan is O(n).""",
 [('js', "Returning `-Infinity` or `null` in JS lets callers forget the empty case. How does `Int?` make forgetting impossible?"),
  ('contrast', "`Set(nums).sorted()` (O(n log n)) vs one pass tracking two values (O(n)): at what size does it matter on an iPhone?"),
  ('edge', "What is `[].max()` in Swift? `Math.max()` in JS returns `-Infinity`. Which is safer?"),
  ('practice', "\"Second best\" logic shows up in leaderboards and runner-up badges. Where do ties make product decisions tricky?")],
 ['optional', 'max', 'distinct'], 'collections')
E['move-zeroes'] = ('e', """In JS the array is passed by reference, so a function mutates it directly. In Swift the array is a value, and in-place mutation requires `inout` (with `&` at the call site). Otherwise the function gets a copy.""",
 [('js', "In JS any function you pass an array to can mutate it. How does `inout` make mutation visible at the call site, and why do Swift APIs prefer returning new arrays?"),
  ('contrast', "In-place with two pointers vs `filter { $0 != 0 } + zeros`: which allocates? Does allocation matter here?"),
  ('edge', "Look at the standard library's `partition(by:)`. Is it stable? Why can't it replace this solution?"),
  ('practice', "When does in-place mutation of large arrays matter on iOS: image pixels, audio buffers? What does `withUnsafeMutableBufferPointer` give you?")],
 ['in place', 'inout', 'array'], 'collections')
E['rotate-array'] = ('e', """JS: `[...a.slice(-k), ...a.slice(0, -k)]`. Swift uses `ArraySlice` ranges: `a[(n-k)...] + a[..<(n-k)]`. Slices share storage with the original array and keep its indices, a classic gotcha.""",
 [('edge', "`let s = a[2...]`: what is `s.startIndex`? Why does `s[0]` crash?"),
  ('js', "JS `slice` always copies. Swift's `ArraySlice` doesn't. What are the memory implications of storing a tiny slice of a huge array?"),
  ('contrast', "The three-reversal trick (O(1) extra space) vs slicing (O(n) extra): when would you pick each?"),
  ('practice', "Carousels and circular buffers rotate indices. Would you rotate data or just map indices with `%`?")],
 ['slice', 'rotate', 'range'], 'collections')
E['chunked'] = ('e', """lodash has `_.chunk`. Swift's standard library doesn't, but swift-algorithms has `chunks(ofCount:)`. By hand you'd use `stride(from:to:by:)`, the Swift `for (i = 0; i < n; i += size)`.""",
 [('js', "Swift has no C-style `for (;;)` loop. Why was it removed (SE-0007), and how does `stride` replace it?"),
  ('contrast', "Returning `[[T]]` vs `[ArraySlice<T>]`: which avoids copying, and which is safer to store?"),
  ('practice', "Batching requests (e.g. 50 IDs per API call) and grid layouts both need chunking. Where have you done this in JS?"),
  ('edge', "What does `stride(from: 0, to: 0, by: 2)` produce? And `by: 0`?")],
 ['stride', 'chunks', 'batch'], 'collections')
E['merge-sorted'] = ('e', """The same algorithm as in JS. The Swift twist is that you can't index past the end silently: JS returns `undefined` and your comparison quietly goes false, while Swift traps. So bounds-checking in the loop condition is mandatory.""",
 [('js', "`a[i] < b[j]` when `i` is out of range is `undefined < 5`, which is false in JS. What does Swift do, and which bugs does that catch early?"),
  ('contrast', "Two-pointer merge O(n+m) vs `(a + b).sorted()` O((n+m)log(n+m)): Swift's sort is Timsort-like and fast on nearly sorted input. Does that change your answer?"),
  ('practice', "Merging two sorted feeds (local cache and server page) is a real app task. How do you handle duplicates by ID?"),
  ('edge', "Can you write this generically for any `Comparable` sequence, not just arrays? What does that buy you?")],
 ['merge', 'sorted', 'two pointers'], 'collections')
E['array-safe-subscript'] = ('c', """JS returns `undefined` for out-of-range reads and never crashes. Swift traps, deliberately. A `subscript(safe:)` extension restores the optional behaviour where you want it, and extensions on `Collection` apply to arrays, strings and slices at once.""",
 [('js', "Is Swift's crash-on-out-of-bounds better than JS's silent `undefined`? Argue both sides for an app with millions of users."),
  ('java', "Java throws `IndexOutOfBoundsException`, which you can catch. Swift's trap can't be caught. Why did Swift choose a non-recoverable failure?"),
  ('edge', "Why must the check be `indices.contains(i)`, not `i < count`? Think of `ArraySlice` and `String`."),
  ('practice', "`items[safe: indexPath.row]` in table-view code is common. Is it hiding a real bug (a data-source mismatch) that you should fix instead?")],
 ['subscript', 'extension', 'out of range'], 'extensions')
E['two-sum'] = ('c', """A Swift `Dictionary` is JS's `Map`, not a plain object. Keys can be any `Hashable` type, and lookups return **optionals** (`dict[k]` is `V?`), so `if let j = seen[target - x]` replaces `if (map.has(...))`.""",
 [('js', "JS object keys are always strings (`obj[1] === obj['1']`). What does Swift's `[Int: Int]` guarantee instead?"),
  ('contrast', "Dictionary lookup vs sorting plus two pointers: which uses less memory? When does that matter?"),
  ('edge', "Does Swift's `Dictionary` preserve insertion order like JS `Map`? What should you use if you need order?"),
  ('practice', "Where do you use a dictionary as an index in apps: cells by ID, a cache by URL? What's the Swift type for the ID?")],
 ['dictionary', 'lookup', 'key'], 'dictionaries')
E['word-frequency'] = ('c', """JS: `counts[w] = (counts[w] || 0) + 1`. Swift has `counts[w, default: 0] += 1`, a subscript with a default that mutates in place without a double lookup. `Dictionary(grouping:by:)` and `reduce(into:)` are the functional forms.""",
 [('js', "JS `counts[w] || 0` treats a stored 0 as missing. Does Swift's `default:` subscript have that bug? Why not?"),
  ('contrast', "`[w, default: 0] += 1` vs `Dictionary(words.map { ($0, 1) }, uniquingKeysWith: +)`: which is clearer, and which is faster?"),
  ('edge', "Is the `default:` value stored in the dictionary when you only *read* with it?"),
  ('practice', "Tag clouds, analytics event counts and badge counts all need frequency maps. Which should be computed server-side?")],
 ['default', 'dictionary', 'count'], 'dictionaries')
E['group-anagrams'] = ('e', """lodash `groupBy` corresponds to `Dictionary(grouping: words, by: { String($0.sorted()) })`. The key is a sorted `String`. In JS you'd sort `w.split('')`, and Swift sorts `Character`s directly.""",
 [('contrast', "Sorted-string key vs a 26-count letter signature: which is O(k) instead of O(k log k)? Can the count signature be a dictionary key in Swift?"),
  ('js', "In JS you'd need `JSON.stringify` to use an array as a Map key. Why can Swift use `[Int]` directly as a dictionary key?"),
  ('edge', "Are \"é\" (precomposed) and \"é\" (decomposed) anagrams under Swift's `sorted()`?"),
  ('practice', "Where does \"group by\" appear in iOS UIs: sectioned lists by date or first letter? Which SwiftUI API renders sections?")],
 ['grouping', 'dictionary', 'sorted'], 'dictionaries')
E['invert-dictionary'] = ('e', """JS: `Object.entries(g).reduce(...)`. Swift iterates `(key, value)` tuples directly with `for (k, v) in dict`, and `dict.keys.sorted()` gives order. Plain dictionary iteration order is arbitrary and changes between runs.""",
 [('edge', "Run the same program twice: does dictionary iteration order change? Why does Swift randomise hashing per process?"),
  ('js', "JS objects iterate in insertion order (mostly). What bugs appear when JS devs assume Swift dictionaries do the same?"),
  ('contrast', "`Dictionary(grouping:by:)` vs `reduce(into:)` with `[k, default: []].append(v)`: which one builds fewer intermediate arrays?"),
  ('practice', "Why must a test assert on sorted keys, or compare dictionaries with `==`, rather than printing a dictionary?")],
 ['dictionary', 'keys', 'sorted'], 'dictionaries')
E['first-unique-char'] = ('e', """Two passes, the same as in JS. Swift strings are collections of `Character`, so `enumerated()` gives character offsets directly, with no `codePointAt` juggling for emoji.""",
 [('js', "In JS, iterating `for (const ch of s)` gives code points but `s[i]` gives UTF-16 units. Which does Swift's `enumerated()` give?"),
  ('contrast', "Counting with `[Character: Int]` vs a fixed `[Int](repeating: 0, count: 26)`: when is the array allowed and faster?"),
  ('edge', "Is the returned index usable as `String.Index`? How would you convert it?"),
  ('practice', "First non-repeated item logic appears in deduping notifications. Where else?")],
 ['character', 'count', 'index'], 'dictionaries')
E['dictionary-default-lookup'] = ('c', """JS: `table[code] ?? \\`Unknown (${code})\\``. Swift's `??` is the same operator, but the left side must be an optional. Dictionary lookup returns `String?`, so the types line up perfectly.""",
 [('js', "JS `??` and Swift `??` look identical. What happens in Swift if the left side isn't optional?"),
  ('contrast', "`dict[k] ?? fallback` vs `dict[k, default: fallback]`: when does each make sense, reading vs mutating?"),
  ('edge', "The right side of `??` is an `@autoclosure`. When is it evaluated? Does an expensive fallback run when the key exists?"),
  ('practice', "Mapping error codes to user-facing messages: should the table live in code, a `Localizable.xcstrings` catalog, or the server?")],
 ['nil coalescing', 'default', 'dictionary'], 'optionals')
E['contains-duplicate'] = ('c', """JS: `new Set(a).size !== a.length`. The same trick works in Swift: `Set(nums).count != nums.count`. Swift's `Set` requires `Hashable` elements, which JS's reference-identity `Set` doesn't.""",
 [('js', "`new Set([{a:1},{a:1}]).size` is 2 in JS. What would a Swift `Set` of equal structs contain? Why?"),
  ('contrast', "Early exit with `insert(_:).inserted` vs building the whole `Set` first: when does it matter?"),
  ('edge', "What is the complexity of `Set.insert` in the worst case? Can adversarial input slow it down, and how does Swift defend against that?"),
  ('practice', "Deduplicating API results by `id` is common. Would you use `Set`, a `Dictionary` by id, or `OrderedSet` from swift-collections?")],
 ['set', 'duplicate', 'contains'], 'sets')
E['set-algebra'] = ('e', """JS got `Set.prototype.intersection` and friends only recently (ES2025). Swift's `Set` has always had `intersection`, `subtracting`, `union` and `symmetricDifference`, plus mutating `form…` variants, all part of the `SetAlgebra` protocol, which `OptionSet` also adopts.""",
 [('js', "Before ES2025 you wrote `[...a].filter(x => b.has(x))`. What's the complexity of Swift's `intersection` compared with that?"),
  ('contrast', "`SetAlgebra` is also adopted by `OptionSet` (like `[.bold, .italic]`). How is a bit mask \"a set\"?"),
  ('practice', "Syncing tags or permissions between client and server is set algebra. Sketch which operations give \"to add\" and \"to remove\"."),
  ('edge', "Sets are unordered. Why does the problem ask for sorted output, and what would a flaky test look like?")],
 ['intersection', 'union', 'set'], 'sets')
E['longest-consecutive'] = ('e', """The same O(n) set-based algorithm as in JS. Swift's `Set.contains` is an O(1) hash lookup, and the \"only start at run beginnings\" trick is what keeps it linear.""",
 [('contrast', "Sorting first (O(n log n)) vs the set trick (O(n)): at what n does the difference show up on-device?"),
  ('edge', "Why does `for x in set where !set.contains(x - 1)` keep it O(n) even though there's a nested while loop?"),
  ('js', "In JS, `Set` of numbers is keyed by SameValueZero. Is Swift's `Set<Int>` any different for negatives and zero?"),
  ('practice', "Streaks (\"7 days in a row\") are this problem with dates. Why is `Calendar` arithmetic needed instead of plain integers?")],
 ['set', 'consecutive', 'sequence'], 'sets')
E['hashable-point-set'] = ('c', """JS `Set`s compare objects by **identity**, so two `{x:1,y:2}` objects are different. Swift compares by **value** through `Hashable`, and structs get `==` and `hash(into:)` synthesised automatically. Tuples can't conform to protocols yet, so they can't go in a `Set`.""",
 [('js', "JS devs stringify keys (`${x},${y}`) to dedupe points. What does synthesised `Hashable` give you instead, and why is it safer?"),
  ('java', "Java requires overriding both `equals` and `hashCode` consistently. How does Swift synthesis prevent the classic \"equal but different hash\" bug?"),
  ('edge', "If you hand-write `==` to compare only `x`, but keep the synthesised hash, what breaks?"),
  ('practice', "SwiftUI `ForEach` and diffable data sources need `Hashable`/`Identifiable`. What happens when two items hash equal but aren't the same row?")],
 ['hashable', 'equatable', 'set'], 'hashable')
E['min-max-tuple'] = ('c', """Named tuples like `(min: Int, max: Int)` are Swift's lightweight multiple return values. In JS you'd return `{min, max}` or an array. Tuples are anonymous types, so they can't conform to protocols (no `Codable`), which is why the judge needs an array.""",
 [('js', "JS returns `{ min, max }` objects and destructures them. How does `let (lo, hi) = minMax(...)` compare, and what can't a tuple do that a struct can?"),
  ('contrast', "Tuple vs struct for a return value: when does a tuple become a design smell?"),
  ('edge', "Why are `(Int, Int)?` and `(Int?, Int?)` different? What does each say about the empty array?"),
  ('practice', "Swift's `minmax` isn't in the standard library, but `min()` and `max()` are. What does swift-algorithms add?")],
 ['tuple', 'min', 'max'], 'tuples')
E['tuple-compare-sort'] = ('e', """JS sort comparators return numbers (`b.points - a.points || ...`). Swift's `sorted(by:)` takes a **Bool** \"are these in increasing order\" predicate, and tuples of `Comparable`s compare lexicographically: `(-p1, -w1, n1) < (-p2, -w2, n2)`.""",
 [('js', "JS comparators return -1/0/1. Swift's return `Bool`. Why is a Bool predicate enough, and what rule must it obey (strict weak ordering)?"),
  ('contrast', "Tuple comparison vs `[SortDescriptor]` vs `KeyPathComparator`: which scales to user-selectable sort columns?"),
  ('edge', "Tuple comparison works up to 6 elements. Why is there a limit? Does parameter packs change it?"),
  ('practice', "Is Swift's `sort` stable? Does it matter when users sort a list by one column after another?")],
 ['tuple', 'sort', 'compare'], 'tuples')
E['predict-tuple-switch'] = ('e', """JS `switch` only compares with `===`. Swift `switch` **pattern-matches**: tuples, ranges, `_` wildcards, `let` bindings and `where` clauses. It's closer to TS discriminated-union narrowing, or pattern matching in Rust.""",
 [('js', "How would you write `case (0, _)` or `case (let x, 0) where x > 5` in JS? What does the compiler check for you in Swift that JS can't?"),
  ('edge', "If two cases both match, which runs? Does Swift warn about unreachable cases?"),
  ('practice', "Switching on a tuple `(state, event)` is a compact state machine. Where would that help: a player, an auth flow?"),
  ('contrast', "Tuple switch vs nested `if`s vs a dictionary of handlers: which is exhaustive by construction?")],
 ['switch', 'tuple', 'pattern'], 'switch')
E['stride-countdown'] = ('e', """Swift dropped C-style `for (i = n; i >= 0; i -= s)` loops. `stride(from:through:by:)` (inclusive) and `stride(from:to:by:)` (exclusive) replace them and work with negative steps and floating-point values.""",
 [('contrast', "`stride(from:to:)` vs `stride(from:through:)`: which includes the end? Which matches `..<` and which matches `...`?"),
  ('js', "Is there any loop in JS that Swift can't express without C-style `for`? Try a loop that modifies its own counter."),
  ('edge', "`stride(from: 0.0, through: 1.0, by: 0.1)`: does it include 1.0? Why is that shaky with floats?"),
  ('practice', "Countdown timers in apps: is a loop right at all, or should you use `Timer`/`TimelineView`?")],
 ['stride', 'countdown', 'loop'], 'loops')
E['range-clamp'] = ('e', """JS: `Math.min(Math.max(x, lo), hi)`. Swift can add `clamped(to:)` to **every** `Comparable` type with one extension (numbers, dates, strings), because protocol extensions add methods retroactively. JS would need prototype patching.""",
 [('js', "Adding `Number.prototype.clamp` in JS is frowned upon. Why is `extension Comparable` considered fine in Swift? What makes it safer (scoping, no runtime monkey-patching)?"),
  ('edge', "What happens if `low > high` when building `low...high`? Is that a compile-time or runtime error?"),
  ('contrast', "`ClosedRange` vs `Range` for clamping: why can't you clamp to `0..<10` as neatly?"),
  ('practice', "Clamping shows up in slider values, zoom scales and scroll offsets. Where would a `Comparable` extension live in a big app, to avoid collisions?")],
 ['clamp', 'comparable', 'range'], 'extensions')
E['diag-closed-range-crash'] = ('e', """JS has no range types. Swift distinguishes `Range` (`a..<b`) from `ClosedRange` (`a...b`) at the type level. The two can't hold each other's literals, which is why generic code uses `RangeExpression`.""",
 [('contrast', "Why are `Range` and `ClosedRange` separate types rather than one type with a flag? What would the flag cost?"),
  ('edge', "`5...1` compiles but crashes at runtime. Why can't the compiler catch it?"),
  ('practice', "APIs like `array[range]` accept `RangeExpression`. Why does that let you pass `2...`, `..<5` and `1...3` to the same subscript?"),
  ('js', "TS could model ranges with branded types. Would that catch `5...1`? What's special about what Swift checks at compile time?")],
 ['range', 'closed range', 'half open'], 'ranges')
E['fix-temperature-range'] = ('e', """The classic `x > 20 || x < 39` bug is language-agnostic. Swift gives you `(21...38).contains(x)` or `21...38 ~= x`, which states the intent. Pattern matching on ranges (`case 21...38:`) is the same operator.""",
 [('contrast', "`range.contains(x)` vs `range ~= x` vs `case range:`: are they the same operation?"),
  ('js', "JS has no range literals. How would you make this bug impossible there? Is a helper function as good?"),
  ('edge', "\"Strictly between\" vs \"between inclusive\": how do `20<..<39` style ranges not exist in Swift, and what do you write instead?"),
  ('practice', "Validation rules (age, password length) often hide boundary bugs. How would you table-test them in XCTest or Swift Testing?")],
 ['range', 'contains', 'between'], 'ranges')
E['fix-can-vote'] = ('e', """The same lesson in every language: `cond ? true : false` is just `cond`. The Swift angle: `Bool` is its own type, so there's no `!!value` coercion trick and no truthiness to fall back on.""",
 [('js', "JS uses `!!x` to coerce to boolean. Why does Swift not need, or allow, that?"),
  ('practice', "Age thresholds differ by country. Where should that rule live so it isn't hard-coded in a view?"),
  ('edge', "Should age be `Int` or `UInt`? What would `UInt` change, and why does Swift style prefer `Int` anyway?"),
  ('contrast', "A computed property `var canVote: Bool` vs a function `canVote(age:)`: when is each the better API?")],
 ['ternary', 'boolean', 'condition'], 'basics')
E['grade-letter'] = ('e', """JS `switch(true)` hacks, or `if` chains, become Swift `switch score { case 90...100: … }`. Range patterns are first-class, and the compiler demands exhaustiveness, so `default` catches invalid scores.""",
 [('js', "`switch (true) { case score >= 90: … }` is a known JS hack. Why does Swift not need it?"),
  ('edge', "If you write `case 90...:` and then `case 80..<90:`, is the order significant? What about overlapping ranges?"),
  ('contrast', "Switch on ranges vs a sorted array of thresholds you search through: which is easier to change from remote config?"),
  ('practice', "Would you return a `String` or an enum `Grade`? What does the enum give the UI layer?")],
 ['switch', 'range', 'case'], 'switch')
E['if-expression'] = ('e', """Swift 5.9 made `if` and `switch` **expressions**, so `let x = if … { a } else { b }` works like a multi-branch ternary. JS has nothing equivalent without an IIFE or a chain of nested ternaries.""",
 [('js', "JS devs nest ternaries or use IIFEs for this. What makes Swift's version type-safe that the IIFE isn't?"),
  ('edge', "Can each branch of an `if` expression contain several statements? What happens if the branches return different types?"),
  ('contrast', "`if` expression vs `switch` expression vs a ternary: which is most readable for 4 categories?"),
  ('practice', "In SwiftUI, `if` inside a `ViewBuilder` is different from an `if` expression. What does the builder turn it into (`_ConditionalContent`)?")],
 ['if expression', 'expression', 'let'], 'conditionals')
E['diag-exhaustive-switch'] = ('c', """TS's `never` exhaustiveness check (`const _: never = x`) is opt-in. Swift makes exhaustiveness **mandatory** for `switch` over enums, which is why adding a case breaks every switch that doesn't handle it. That's usually what you want.""",
 [('js', "In TS you add `default: assertNever(x)` to get this. What's the cost of Swift doing it by default?"),
  ('edge', "What is `@unknown default`, and why do switches over Apple's enums (`UIUserInterfaceStyle`) need it?"),
  ('practice', "You add `case snow` to an enum used in 40 places. Is \"breaking the build\" good or bad? When would `default` be the right call?"),
  ('java', "Java 21's switch patterns over sealed types are exhaustive too. How do Swift enums compare with sealed interfaces?")],
 ['exhaustive', 'switch', 'default'], 'switch')
E['fizzbuzz-stdio'] = ('e', """Switching on a tuple `(i % 3, i % 5)` with `case (0, 0)` is a Swift-ism with no JS equivalent. It turns nested conditions into a table.""",
 [('contrast', "Tuple switch vs string concatenation (`\"Fizz\" if…`, `\"Buzz\" if…`): which extends better to a \"Bazz\" rule for 7?"),
  ('js', "How would you write this with destructuring in JS? What's missing without pattern matching?"),
  ('edge', "What does `readLine()` return for empty input, and how should `Int(\"\")` be handled?"),
  ('practice', "Is FizzBuzz a useful interview question for iOS roles? What would you ask instead?")],
 ['switch', 'tuple', 'fizzbuzz'], 'switch')
E['switch-multiple-patterns'] = ('e', """Swift `case "a", "e", "i":` lists several patterns in one case, with no fall-through stacking like JS `case 'a': case 'e':`. A `where` clause adds arbitrary conditions to a pattern.""",
 [('js', "JS stacks `case 'a': case 'e':` and relies on fall-through. Why does Swift ban implicit fall-through?"),
  ('contrast', "`case let c where c.isNumber` vs `if c.isNumber`: when does the switch version win?"),
  ('edge', "Is `\"A\"` matched by `case \"a\"`? What's the cleanest way to make the switch case-insensitive?"),
  ('practice', "Character classification drives input filters like a PIN pad or phone number field. When should you use `CharacterSet` instead?")],
 ['switch', 'case', 'where'], 'switch')
E['fallthrough-description'] = ('e', """JS `switch` falls through **by default**, a famous source of bugs. Swift does the reverse: no implicit fall-through, and an explicit `fallthrough` keyword when you really want it (rarely).""",
 [('js', "How many JS bugs come from a forgotten `break`? Why is Swift's opt-in `fallthrough` the better default?"),
  ('edge', "Can `fallthrough` jump into a case that binds variables with `let`? Why not?"),
  ('contrast', "`fallthrough` vs extracting the shared code into a function: which would a reviewer prefer?"),
  ('practice', "Have you ever seen `fallthrough` in production Swift? What's a legitimate use?")],
 ['fallthrough', 'switch', 'default'], 'switch')
E['fix-infinite-while'] = ('e', """A `while` loop whose `continue` skips the increment hangs in JS too. Swift nudges you towards `for … in` over collections or `stride`, where the language owns the counter and this bug can't happen.""",
 [('contrast', "`for x in items.reversed()` vs an index-based `while`: which bugs does each make impossible?"),
  ('js', "In JS, `for…of` vs `for (let i…)`: do you reach for index loops more in JS than you need to in Swift?"),
  ('practice', "An infinite loop on the main thread freezes the UI. What does iOS do to an app that hangs too long (watchdog)?"),
  ('edge', "How did the judge detect the infinite loop? What does TLE mean in terms of process signals?")],
 ['while', 'continue', 'loop'], 'loops')
E['labeled-break'] = ('e', """JS has labelled statements too (`outer: for …`, `break outer`), but they're rarely used. Swift's are identical in spirit, and more common because there's no `goto` and returning early from a nested loop is the alternative.""",
 [('js', "JS has `outer:` labels too. Did you know? Why are they more idiomatic in Swift than in JS?"),
  ('contrast', "Labelled `break` vs extracting a function and `return`ing: which is clearer in a code review?"),
  ('edge', "Can you label an `if` or `switch` and `break` out of it? When would you?"),
  ('practice', "Searching a grid (calendar cells, game boards) is common. Would `firstIndex(where:)` with `flatMap` be cleaner?")],
 ['label', 'break', 'nested loop'], 'loops')
E['repeat-while-collatz'] = ('e', """`repeat { } while cond` is JS's `do { } while (cond)`, just renamed, because `do` in Swift introduces a scope or a `do/catch`.""",
 [('js', "Why did Swift rename `do-while` to `repeat-while`? What does `do` mean in Swift?"),
  ('edge', "Can Collatz overflow `Int` for some inputs? How would you detect it?"),
  ('contrast', "`repeat-while` vs `while` vs recursion: which reads best here, and does Swift guarantee tail-call optimisation?"),
  ('practice', "Retry loops (\"try at least once, then until success\") are a natural `repeat-while`. How would you add backoff with `Task.sleep`?")],
 ['repeat', 'while', 'loop'], 'loops')
