E = {}
E['multiplication-table-stdio'] = ('e', """Reading `"5 3"` from stdin: `readLine()!.split(separator: " ").compactMap { Int($0) }`, the Swift version of `line.split(' ').map(Number)`. The difference is that bad input gives `nil` instead of `NaN`.""",
 [('js', "`Number('x')` is `NaN` and poisons later maths silently. What does `Int(\"x\")` force you to decide up front?"),
  ('contrast', "`for i in 1...upTo` crashes when `upTo < 1`. Why? What's the safe alternative?"),
  ('edge', "What if the line has three numbers, or tabs instead of spaces? How strict should a parser be?"),
  ('practice', "Swift CLIs usually use swift-argument-parser, not stdin parsing. What does it give you: help, validation, completion?")],
 ['readline', 'split', 'range'], 'io')
E['pyramid-stdio'] = ('e', """`String(repeating: " ", count: n)` is JS `' '.repeat(n)`. The "no trailing spaces" requirement is where diffing judges (and snapshot tests) bite.""",
 [('contrast', "String concatenation in a loop vs building an array of rows and `joined(separator: \"\\n\")`: which is O(n²)?"),
  ('js', "JS `padStart` exists. Is there a Swift equivalent, and why might `padding(toLength:)` from Foundation surprise you?"),
  ('edge', "Would the pyramid stay centred with emoji instead of `*`? Why not?"),
  ('practice', "Where does whitespace-exact output matter in iOS work: snapshot tests, generated code, accessibility labels?")],
 ['repeating', 'string', 'loop'], 'io')
E['argument-labels'] = ('c', """JS has no argument labels; you pass an options object `{from, to, by}` to get readable calls. Swift builds labels into the signature: `move(from:to:by:)` is the function's **name**. The external label (`from`) and internal name (`start`) can differ.""",
 [('js', "An options object `{from, to}` vs Swift labels: which one lets you reorder arguments? Which one is checked at compile time?"),
  ('practice', "Read Apple's API Design Guidelines on labels. Why is it `insert(_:at:)` and not `insert(element:atIndex:)`?"),
  ('edge', "Can two functions differ only by labels, like `move(from:to:)` and `move(start:end:)`? Is that overloading?"),
  ('java', "Java has no labels, so builder patterns became popular. Do Swift labels reduce the need for builders?")],
 ['argument label', 'parameter', 'label'], 'functions')
E['default-parameters'] = ('c', """Like JS default parameters (`function greet(name, greeting = 'Hello')`), except Swift defaults can sit on any parameter because labels disambiguate. You can skip the middle one, which JS can't do without passing `undefined`.""",
 [('js', "JS: to use the default for `greeting` but set `punctuation`, you pass `undefined`. Why doesn't Swift need that?"),
  ('contrast', "Default parameters vs overloads: which keeps a public API evolvable without breaking callers?"),
  ('edge', "Are default values evaluated at each call, like JS, or once? Can a default reference another parameter?"),
  ('practice', "SwiftUI modifiers are full of defaults, like `padding(_ edges: = .all, _ length: = nil)`. Find one and read its signature.")],
 ['default', 'parameter', 'value'], 'functions')
E['variadic-average'] = ('e', """Like JS rest parameters (`...numbers`), but you can't spread an array into a Swift variadic parameter; there's no `average(...arr)`. That's why APIs provide an array overload too.""",
 [('js', "JS `fn(...arr)` spreads an array. Swift has no splat. What design pattern does that force on API authors?"),
  ('edge', "Can a function have two variadic parameters? (Swift 5.4 changed this.) What disambiguates them?"),
  ('contrast', "Variadic vs `[Double]` parameter: which is nicer at the call site, and which is more flexible?"),
  ('practice', "`print(_ items: Any...)` is variadic. What does `Any...` cost in type safety?")],
 ['variadic', 'parameters', 'average'], 'functions')
E['overloading-describe'] = ('e', """JS can't overload by type; you branch on `typeof` inside one function. Swift picks the overload **at compile time** from the static types, and the choice can't change at runtime. That's a key difference from dynamic dispatch.""",
 [('js', "In JS you'd write `if (typeof v === 'number')`. What does compile-time overload resolution give you, and what can it never do (think `Any`)?"),
  ('edge', "If you call `describe(x)` where `x: Any`, which overload runs? Why is that surprising?"),
  ('java', "Java also resolves overloads statically. Would a Java dev be surprised by any Swift overloading rule?"),
  ('contrast', "Overloads vs a generic function with a protocol constraint: when does each scale better?")],
 ['overload', 'function', 'type'], 'functions')
E['nested-functions'] = ('e', """Nested function declarations inside a function work like JS inner functions and close over outer variables. Functions are first-class: `let step: (Int) -> Int = stepForward` is the typed version of assigning a function to a variable.""",
 [('js', "JS inner functions are hoisted. Can a Swift nested function be called before its declaration in the body?"),
  ('contrast', "Nested `func` vs `let` closure: which can be recursive without tricks?"),
  ('edge', "Does a nested function that captures nothing allocate anything?"),
  ('practice', "When does a nested helper beat a `private` method: readability or scope?")],
 ['nested function', 'function type', 'closure'], 'functions')
E['implicit-return-sign'] = ('e', """Like JS arrow functions `x => x * 2`, Swift single-expression bodies return implicitly. Since Swift 5.9 that includes `switch` and `if` **expressions**, which JS arrows can't contain without braces.""",
 [('js', "An arrow function with braces needs `return`. What's the Swift rule: when exactly may `return` be omitted?"),
  ('edge', "Add a `print` inside one `switch` branch. Does implicit return still work?"),
  ('practice', "SwiftUI `body` relies on implicit return plus result builders. Why does adding a `let` inside `body` sometimes still work?"),
  ('contrast', "`switch` expression vs a dictionary lookup `[-1: \"negative\", …]`: which is exhaustive?")],
 ['implicit return', 'expression', 'switch'], 'functions')
E['enum-raw-values'] = ('c', """TS numeric enums (`enum Planet { Mercury = 1, … }`) auto-increment the same way. But a TS enum lookup by number gives `undefined`, while Swift's `Planet(rawValue:)` is a **failable initialiser** that returns `Planet?`.""",
 [('js', "TS enums create a reverse-mapping object at runtime. What does a Swift enum compile to, and can you iterate it without `CaseIterable`?"),
  ('practice', "Decoding API values with `String` raw values: what happens when the server adds a new value your enum doesn't know?"),
  ('edge', "Can raw values be computed or duplicated? Why must they be literals?"),
  ('java', "Java enums have `ordinal()` and `valueOf()`. What's the Swift equivalent of each, and why is relying on ordinal fragile?")],
 ['raw value', 'enum', 'rawValue'], 'enums')
E['enum-case-iterable'] = ('e', """TS gets `Object.values(Enum)`, with numeric-enum weirdness. Swift's `CaseIterable` synthesises `allCases` in declaration order, and computed properties on the enum keep data like `price` next to each case.""",
 [('js', "`Object.values` on a numeric TS enum returns names *and* numbers. What does Swift's `allCases` guarantee instead?"),
  ('practice', "`Picker` with `ForEach(Coffee.allCases)`: what else does the enum need (`Identifiable`, `Hashable`)?"),
  ('edge', "Can an enum with associated values be `CaseIterable` automatically? Why not?"),
  ('contrast', "A `price` computed property with a `switch` vs a `[Coffee: Int]` dictionary: which can the compiler check for missing cases?")],
 ['caseiterable', 'allcases', 'enum'], 'enums')
E['enum-associated-shapes'] = ('c', """This is TS's **discriminated union** (`{kind: 'circle', radius} | {kind: 'rect', …}`) built into the language. Swift's `switch` narrows the payload with `case .circle(let r)`, and exhaustiveness is enforced without a `never` check.""",
 [('js', "Write the TS discriminated union for Shape. What does Swift remove: the `kind` tag string, and the need for a type guard?"),
  ('practice', "Model a network request state as `enum Loadable<T> { case idle, loading, loaded(T), failed(Error) }`. What impossible states does that rule out compared with `isLoading` + `data?` + `error?`?"),
  ('java', "Java 17 sealed interfaces + records do the same. What's more verbose there?"),
  ('contrast', "Enum with payloads vs protocol + structs (`Shape` protocol): which is easier to extend with new *cases*, and which with new *operations*? (The expression problem.)")],
 ['associated value', 'enum', 'case'], 'enums')
E['enum-mutating-toggle'] = ('e', """An enum method that changes `self` must be `mutating`, because enums are value types. In JS you'd reassign `light = next(light)`. Swift lets the value transition itself in place: `self = .green`.""",
 [('js', "State machines in JS often use xstate or a reducer. How close is a Swift enum with a `mutating func next()` to a reducer?"),
  ('edge', "Can you call `next()` on a `let` light? What error do you get?"),
  ('practice', "Would you put transition logic in the enum, or in a separate reducer? What about side effects like playing a sound?"),
  ('contrast', "`mutating func next()` vs `func next() -> TrafficLight`: which composes better with SwiftUI `@State`?")],
 ['mutating', 'enum', 'self'], 'enums')
E['predict-enum-switch-order'] = ('e', """`if case .loaded(let value) = state` is pattern matching outside a `switch`. The nearest JS equivalent is `if (state.kind === 'loaded') { const value = state.value }`, but Swift combines the check and the binding in one step.""",
 [('js', "How would you write `if case .loaded(let x) = s, x > 3` in TS? How many lines?"),
  ('edge', "`for case .some(let x) in optionals`: what does it iterate over?"),
  ('contrast', "`if case` vs `switch` with a `default`: when does each communicate intent better?"),
  ('practice', "Where would `guard case` show up in a view model?")],
 ['if case', 'pattern', 'enum'], 'enums')
E['typealias-grid'] = ('e', """Swift's `typealias` is TS's `type Grid = number[][]`: a new name, not a new type, so `Grid` and `[[Int]]` are interchangeable. For a distinct type, wrap it in a struct, which is the equivalent of TS branded types.""",
 [('js', "TS `type UserID = string` doesn't stop you passing any string. Does Swift's `typealias` behave the same? How do you get real type safety?"),
  ('contrast', "`typealias Cell = (row: Int, col: Int)` vs `struct Cell`: what can the struct do that the tuple alias can't?"),
  ('practice', "Where does Apple use typealiases: `Codable = Decodable & Encodable`, `TimeInterval = Double`? What does each communicate?"),
  ('edge', "Can a typealias be generic, like `typealias Pair<T> = (T, T)`?")],
 ['typealias', 'alias', 'type'], 'types')
E['predict-nested-comments'] = ('e', """JS (like C) block comments don't nest, so `/* /* */ */` breaks. Swift's do nest, so you can comment out a block that already contains comments.""",
 [('js', "Why doesn't JS support nested block comments? What parsing trade-off is involved?"),
  ('practice', "What do `///` doc comments and `// MARK: -` do in Xcode? How are they like JSDoc?"),
  ('edge', "Does a `*/` inside a string literal end a comment in Swift?"),
  ('contrast', "Commenting out code vs `#if false … #endif`: which one still gets parsed?")],
 ['comment', 'nested', 'block'], 'basics')
E['checkpoint-2-unique-count'] = ('e', """`new Set(arr).size` in JS is `Set(arr).count` in Swift. The difference is that Swift requires the element type to be `Hashable`, where JS silently uses identity.""",
 [('js', "`new Set([[1],[1]]).size` is 2 in JS. What would `Set([[1],[1]]).count` be in Swift?"),
  ('contrast', "Counting unique items via `Set` vs `Dictionary(grouping:)`: when do you need the counts too?"),
  ('edge', "Are `\"café\"` (precomposed) and `\"café\"` (decomposed) one element or two in a Swift `Set<String>`?"),
  ('practice', "Unique counts show up in analytics, like \"distinct screens visited\". Where should those be computed?")],
 ['set', 'unique', 'count'], 'sets')
E['checkpoint-4-integer-sqrt'] = ('c', """JS throws anything (`throw 'oops'`), and callers don't know what might come back. Swift functions must be marked `throws`, callers must write `try`, and errors are values that conform to `Error`, usually enums.""",
 [('js', "In JS, any function may throw and nothing marks it. How does Swift's `throws` + `try` change code review?"),
  ('java', "Java has checked exceptions that list the types. Swift's `throws` (untyped) doesn't. Why did Swift avoid Java's approach, and what did typed `throws(E)` in Swift 6 add back?"),
  ('contrast', "Throwing vs returning `Int?` vs returning `Result`: which tells the caller *why* it failed?"),
  ('practice', "Is throwing expensive in Swift like exceptions in some languages? (Hint: Swift errors are ordinary return values under the hood.)")],
 ['throw', 'error', 'try'], 'errors')
E['checkpoint-5-lucky-numbers'] = ('c', """JS `arr.filter().sort().map()` becomes Swift's `filter { }.sorted().map { }`, almost identical. Two differences: `sorted()` returns a new array (JS `sort` mutates), and the default sort is numeric, not JS's lexicographic `[10, 9].sort()` surprise.""",
 [('js', "`[10, 9, 1].sort()` in JS gives `[1, 10, 9]`. What does Swift's `sorted()` do, and why?"),
  ('contrast', "Chained `filter`/`map` creates intermediate arrays. When would you use `.lazy`?"),
  ('practice', "Chains like this often live in view models for display lists. When should they be precomputed instead of recomputed in `body`?"),
  ('java', "Java Streams are lazy by default and need `.collect()`. Swift's are eager unless you ask for `lazy`. Which default is better?")],
 ['filter', 'map', 'sorted'], 'closures')
E['compound-assignment'] = ('e', """`+=`, `-=` and friends work as in JS, including `+=` on strings. The differences: `/` on `Int` truncates, overflow traps, and there's no `++` or `--` (removed in Swift 3).""",
 [('js', "Why did Swift remove `++` and `--` (SE-0004)? Do you miss them?"),
  ('edge', "`score /= 0` would crash. What does JS do with `/ 0`?"),
  ('contrast', "`title += \" x\"` vs `title.append(\" x\")`: any performance difference?"),
  ('practice', "Can you define `+=` for your own types, like a `Money` struct? Should you?")],
 ['compound', 'assignment', 'operator'], 'basics')
E['multi-line-strings'] = ('e', """Swift `\"\"\"` blocks are like JS template literals, with one difference: the closing delimiter's indentation is stripped from every line, so you can indent code naturally. A trailing `\\` joins lines.""",
 [('js', "JS template literals keep all indentation, so people use `dedent` libraries. What does Swift do that makes those unnecessary?"),
  ('edge', "What happens if a line is indented *less* than the closing `\"\"\"`?"),
  ('practice', "Multi-line strings are handy for GraphQL queries and test fixtures. Where else?"),
  ('contrast', "A trailing `\\` in a multi-line string vs concatenation with `+`: which is clearer?")],
 ['multi-line', 'string', 'indentation'], 'strings')
E['string-methods'] = ('e', """Most JS string methods have Swift equivalents: `hasPrefix` (`startsWith`), `contains`, `uppercased()`, `replacingOccurrences` (`replaceAll`). Some come from Foundation (`import Foundation`), which is Apple's "extra standard library".""",
 [('js', "Which string methods need `import Foundation` in Swift? Why is Foundation separate from the standard library?"),
  ('edge', "`\"ß\".uppercased()` is `\"SS\"`. What other length-changing case mappings exist?"),
  ('contrast', "`contains(\"x\")` (Foundation/StringProtocol) vs `contains(Character)` (Sequence): why do both exist?"),
  ('practice', "For user-facing comparisons, why use `localizedCaseInsensitiveCompare` or `localizedStandardContains`?")],
 ['hasprefix', 'uppercased', 'string'], 'strings')
E['array-methods'] = ('e', """JS `push`, `unshift`, `splice` and `indexOf` map to Swift `append`, `insert(_:at:)`, `remove(at:)` and `firstIndex(of:)`. Swift's return optionals instead of `-1`, and they trap on bad indices instead of quietly doing nothing.""",
 [('js', "`indexOf` returns -1. `firstIndex(of:)` returns `Int?`. Which bug class does the optional remove?"),
  ('contrast', "`insert(_, at: 0)` is O(n). What data structure makes front insertion O(1) (`Deque` in swift-collections)?"),
  ('edge', "`removeFirst()` on an empty array crashes. What's the safe variant (`popFirst` on slices)?"),
  ('practice', "A playlist in a SwiftUI `List` supports `.onMove` and `.onDelete`. Which array methods do they call?")],
 ['append', 'insert', 'remove'], 'collections')
E['predict-empty-collections'] = ('e', """JS: `[]` and `{}` need no types. Swift: `[]` alone can't infer an element type, so you write `[Int]()`, `[String: Int]()` or annotate the variable. `Set` has no literal of its own; it borrows array literal syntax.""",
 [('js', "Why can't Swift infer `let x = []`? What does TS infer for `const x = []` (`any[]` or `never[]`)?"),
  ('edge', "`let s: Set = [1, 2]`: how does an array literal become a `Set`? (`ExpressibleByArrayLiteral`)"),
  ('contrast', "`[Int]()` vs `[] as [Int]` vs `Array<Int>()`: any difference?"),
  ('practice', "Should an empty array property be `var items: [Item] = []` or `[Item]? = nil`? What does each mean to the UI?")],
 ['empty', 'array', 'dictionary'], 'collections')
E['dictionary-merge'] = ('e', """JS `{...a, ...b}` makes b win on conflicts. Swift's `merging(_:uniquingKeysWith:)` makes you decide with a closure: `+` to add, `{ $1 }` for "new wins". Merging never silently discards data.""",
 [('js', "`{...a, ...b}` silently overwrites. How does Swift make conflict resolution explicit?"),
  ('contrast', "`merging` (returns new) vs `merge` (mutating): when does the mutating version save work?"),
  ('edge', "What does `Dictionary(uniqueKeysWithValues:)` do on a duplicate key? Why is that a crash and not an error?"),
  ('practice', "Merging local and remote settings: which side should win, and should that be a closure parameter?")],
 ['merging', 'dictionary', 'merge'], 'dictionaries')
E['ordered-dedupe'] = ('c', """JS: `[...new Set(arr)]` keeps insertion order because JS `Set` is ordered. Swift's `Set` is **unordered**, so `Array(Set(arr))` scrambles the order. Filter with a `seen` set, or use `OrderedSet` from swift-collections.""",
 [('js', "JS `Set` preserves insertion order. Swift's doesn't. Which JS habits break because of that?"),
  ('contrast', "`filter { seen.insert($0).inserted }` vs `OrderedSet(arr)`: which would you ship, and what does adding a package cost?"),
  ('edge', "The `insert` in `filter` mutates captured state. Is a side-effecting closure inside `filter` OK style?"),
  ('practice', "Deduping search results by ID while keeping rank order is this exact problem. How would you key by ID rather than the whole value?")],
 ['duplicates', 'set', 'order'], 'sets')
E['enum-string-raw'] = ('e', """`String` raw values default to the case name (`case small` means `"small"`), like TS string enums but without typing the name twice. `"\\(Size.large)"` prints the **case name**, not the raw value, a common surprise.""",
 [('js', "TS string enums need `Small = 'small'`. What does Swift infer if you omit the raw value?"),
  ('edge', "Why does `print(Size.large)` print `large` and not `L`? How would you make it print `L`?"),
  ('practice', "Raw values often mirror API strings. Should the enum's case names follow Swift style while raw values follow the API?"),
  ('contrast', "Raw values vs `CodingKeys`-style mapping: where does each belong?")],
 ['raw value', 'string', 'enum'], 'enums')
E['diag-type-annotation'] = ('e', """TS would also flag `let score: number = "100"`, so the idea is familiar. Swift goes further: there's no `any` escape hatch by default and no implicit conversion at runtime, and type errors are always compile errors.""",
 [('js', "TS has `as any` to silence this. What's the closest Swift escape hatch, and why is it much rarer?"),
  ('contrast', "Annotation mismatch vs failed `as!` cast: compile-time vs runtime. Which one can still crash?"),
  ('edge', "Why does `let x: Double = 100` compile but `let x: Int = 100.0` doesn't?"),
  ('practice', "When reading unfamiliar Swift errors, what does \"cannot convert value of type…\" usually mean in SwiftUI code?")],
 ['type annotation', 'cannot convert', 'type'], 'types')
E['skipping-items'] = ('e', """`continue` and `break` work exactly as in JS. The idiomatic Swift variant often replaces the loop with `prefix(while:)` for the break and `compactMap` for the skip.""",
 [('contrast', "Rewrite with `prefix(while:)` + `compactMap` + `filter`. Is it clearer or not?"),
  ('js', "JS `for…of` supports `break`, but `.forEach` doesn't. Is Swift's `forEach` the same?"),
  ('edge', "Does `continue` inside a `switch` inside a loop continue the loop, or exit the switch?"),
  ('practice', "Parsing sensor or health data often has sentinel values. How would you represent \"END\" in a typed model?")],
 ['continue', 'break', 'loop'], 'loops')
E['predict-ranges'] = ('e', """JS has no range operators. Swift has `...` (closed), `..<` (half-open) and one-sided `2...`/`..<5`. They're values you can store and pass around, and slicing uses them directly.""",
 [('contrast', "`Range` vs `ClosedRange` vs `PartialRangeFrom`: which can you iterate over, and which can't you?"),
  ('js', "What's the JS idiom for `0..<n` (`Array.from({length: n}, (_, i) => i)`)? What does it allocate?"),
  ('edge', "Can you iterate `1.0...2.0`? Why not? What do you use instead?"),
  ('practice', "`array[..<3]` is a common way to take the first 3. What does `prefix(3)` do differently for short arrays?")],
 ['range', 'half open', 'closed'], 'ranges')
E['switch-strings'] = ('e', """JS `switch` on strings uses `===`. Swift pattern-matches strings too, and adds `case let s where s.hasPrefix(\"storm\")`, so switch can do what JS needs an `if` chain for.""",
 [('js', "How would you do the \"starts with storm\" case in a JS `switch`? (`switch (true)` again?)"),
  ('contrast', "Switching on raw strings vs parsing them into an enum first: which scales, and where should parsing happen?"),
  ('edge', "Is a string switch case-sensitive? Where's the right place to normalise?"),
  ('practice', "Server-driven UI sends strings like `\"banner\"`. What should unknown values do?")],
 ['switch', 'string', 'case'], 'switch')
E['rounding-doubles'] = ('e', """JS has `Math.round` (half up), `floor`, `ceil` and `trunc`. Swift's `rounded(_:)` takes a `FloatingPointRoundingRule`, and the default is **half away from zero**: `-2.5` becomes `-3`, where JS gives `-2`.""",
 [('js', "`Math.round(-2.5)` is -2 in JS. What is `(-2.5).rounded()` in Swift? Which is \"right\"?"),
  ('edge', "Why can `(x * 100).rounded() / 100` still print `1.0049999999`? What should a UI use instead?"),
  ('contrast', "`.toNearestOrEven` (banker's rounding) vs `.toNearestOrAwayFromZero`: where does banker's rounding matter?"),
  ('practice', "For display, use `value.formatted(.number.precision(.fractionLength(2)))`. Why is formatting better than rounding the stored number?")],
 ['rounded', 'round', 'double'], 'numbers')
E['character-properties'] = ('e', """JS regex classes like `/[A-Z]/` are ASCII-centric (unless you use `\\p{Lu}` with the `u` flag). Swift's `Character` has `isUppercase`, `isNumber` and `isLetter`, which are Unicode-aware by default.""",
 [('js', "JS `/\\p{Lu}/u` is Unicode-aware. Is `Character.isUppercase` equivalent? Test \"É\"."),
  ('edge', "Is \"½\" `isNumber`? Is it `isWholeNumber`? Does that matter for a password rule?"),
  ('practice', "Real password strength should use entropy or zxcvbn-style scoring. What does iOS do for you with `textContentType = .newPassword`?"),
  ('contrast', "`Character` properties vs `CharacterSet` vs Swift `Regex`: when would you pick each?")],
 ['character', 'uppercase', 'password'], 'strings')
E['nested-collections'] = ('e', """`[String: [String]]` is JS's `Record<string, string[]>`. The difference: `dict[k]?.append(x)` silently does nothing when the key is missing, so you need `dict[k, default: []].append(x)`.""",
 [('js', "In JS, `map[k].push(x)` throws if `map[k]` is undefined. What does `dict[k]?.append(x)` do in Swift, and why is that sneakier?"),
  ('edge', "Does `dict[k, default: []].append(x)` copy the array? (It mutates in place.)"),
  ('contrast', "`[String: [String]]` vs `[String: Set<String>]` for de-duplication: which fits better?"),
  ('practice', "Sectioned lists in SwiftUI need an ordered list of sections. Why is a dictionary alone not enough?")],
 ['nested', 'dictionary', 'array'], 'dictionaries')
E['word-stats-stdio'] = ('e', """Reading all of stdin: `while let line = readLine()`, the synchronous version of collecting Node's `process.stdin` data events. `max(by:)` returns the **last** maximum on ties, not the first. Know your standard library's tie rules.""",
 [('edge', "Does `max(by:)` return the first or the last of equal elements? How do you get the first?"),
  ('js', "`reduce` for \"longest\" in JS: what tie behaviour does `>` vs `>=` give? Same in Swift?"),
  ('contrast', "`split(whereSeparator: \\.isWhitespace)` vs `components(separatedBy: .whitespacesAndNewlines)`: which one gives empty strings?"),
  ('practice', "Word counting for a notes app: would you use `NLTokenizer` instead? Why?")],
 ['readline', 'words', 'max'], 'io')
E['functions-returning-tuples'] = ('e', """Returning a named tuple `(mean:, median:, range:)` is like returning `{mean, median, range}` in JS, and `let (mean, median, range) = …` is destructuring. Optional tuples express "no result" for empty input.""",
 [('js', "JS destructuring works with defaults and renaming. What can Swift tuple destructuring do, and not do?"),
  ('contrast', "At what point should this tuple become a `Summary` struct?"),
  ('edge', "Median of an even count: which average do you use? Integer or floating-point?"),
  ('practice', "Charts in Swift Charts need summary statistics. Would you compute them in SQL, Core Data, or Swift?")],
 ['tuple', 'return', 'destructure'], 'tuples')
E['predict-shadowing'] = ('c', """`if let name { }` (Swift 5.7) is shorthand for `if let name = name`. It **shadows** the optional with a non-optional of the same name inside the braces. JS has no equivalent; TS narrowing does something similar without making a new variable.""",
 [('js', "TS narrows `name` inside `if (name)`. Swift creates a new constant. What's observably different? (Hint: assign to it.)"),
  ('edge', "After `guard let name else { return }`, what type is `name` for the rest of the function?"),
  ('contrast', "`if let` vs `guard let`: which keeps the happy path unindented?"),
  ('practice', "Shadowing `self` with `guard let self` in closures is idiomatic. Why?")],
 ['if let', 'shadow', 'guard'], 'optionals')
E['temperature-table-stdio'] = ('e', """`stride(from:through:by:)` handles negative steps, which a JS `for` loop needs a flipped condition for. Rounding to the nearest integer uses `Int(f.rounded())`, not `Int(f)`, which truncates.""",
 [('edge', "`Int(-0.6)` is 0, `Int((-0.6).rounded())` is -1. Which one prints \"-0\"?"),
  ('contrast', "`stride` handles a negative step. What does `stride(from: 0, through: 10, by: -1)` yield?"),
  ('js', "`Math.round` vs `rounded()`: how do they differ on negatives?"),
  ('practice', "Should you print `°C` yourself or use `MeasurementFormatter`?")],
 ['stride', 'temperature', 'rounded'], 'loops')
E['nil-coalescing-chains'] = ('c', """`a ?? b ?? "Anonymous"` is identical to JS's `??` chains, and `tags?.count ?? 0` is `tags?.length ?? 0`. The difference is that Swift's optional chaining result is typed `Int?`, so the compiler insists on a fallback.""",
 [('js', "JS `a || b` treats `\"\"` as missing, `a ?? b` doesn't. Which one matches Swift's `??`? Is there a Swift `||` for strings?"),
  ('edge', "A nickname of `\"\"` (empty but present): should it fall back to the name? How would you express that?"),
  ('contrast', "`tags?.first?.uppercased() ?? \"-\"` vs `if let`: which reads better at 3+ levels?"),
  ('practice', "Display-name fallback logic appears on every profile screen. Where would you centralise it?")],
 ['nil coalescing', 'optional chaining', 'default'], 'optionals')
E['variadic-join'] = ('e', """A variadic `String...` combined with a defaulted `separator:` parameter after it: the label is what lets the compiler know where the variadic list ends. JS rest parameters must come last; Swift variadics needn't.""",
 [('js', "JS rest params must be last. How can Swift put `separator:` after the variadic?"),
  ('contrast', "Hand-built path joining vs `URL.appending(path:)`: what does `URL` handle that string joining doesn't?"),
  ('edge', "What happens with a component like `\"a//b\"`? Should inner slashes be collapsed?"),
  ('practice', "Building API paths by string concatenation is error-prone. What would a typed `Endpoint` enum look like?")],
 ['variadic', 'join', 'path'], 'functions')
E['enum-methods-state'] = ('c', """An order state machine as an enum plus a `mutating func handle(_:)` is like a Redux reducer that owns its own state. Invalid transitions return `false` instead of silently corrupting state. JS would need a library like xstate for this rigour.""",
 [('js', "How would xstate express this? What does Swift's exhaustive switch give you that a JS object of transitions doesn't?"),
  ('practice', "Order status comes from the server. Should the client enforce transitions, or only display them?"),
  ('contrast', "Enum state machine vs typestate pattern (different types per state, e.g. `PaidOrder`): which catches invalid transitions at compile time?"),
  ('edge', "Should `cancel` be valid after `shipped`? How do you encode business rules that change often?")],
 ['state', 'enum', 'transition'], 'enums')
E['predict-integer-division'] = ('c', """`7 / 2` is `3` in Swift (Int) but `3.5` in JS. `7 % -2` keeps the dividend's sign in both languages. Mixing `Int` and `Double` needs explicit conversion, so these surprises are always visible in the types.""",
 [('js', "JS has one number type. List three bugs that come from Swift having `Int` and `Double` as different types, and three it prevents."),
  ('edge', "What is `Int.min / -1`? Why does it trap?"),
  ('contrast', "`Double(7) / 2` vs `Double(7 / 2)`: why are the results different?"),
  ('practice', "Progress bars compute `completed / total`. What goes wrong with `Int`s?")],
 ['integer division', 'remainder', 'double'], 'numbers')
E['parse-sum-optionals'] = ('c', """`Number(s)` returns `NaN` in JS, while `Int(s)` returns `Int?`. `compactMap { Int($0) }` parses and drops failures in one step, the typed version of `.map(Number).filter(n => !isNaN(n))`.""",
 [('js', "`Number(' 7')` is 7 and `Number('')` is 0 in JS. What do `Int(\" 7\")` and `Int(\"\")` return? Which is stricter, and why is that better for forms?"),
  ('contrast', "`compactMap` vs `map` then `filter { $0 != nil }` then force unwrap: why is the first idiomatic?"),
  ('edge', "Why doesn't `Int(\"4.5\")` return 4? How would you parse a decimal string into an Int?"),
  ('practice', "Parsing user number input should respect locale (\"1,5\" in Germany). Which API handles that?")],
 ['failable', 'compactmap', 'parse'], 'optionals')
E['if-let-chain'] = ('c', """`if let w = Int(a), let h = Int(b), w > 0, h > 0` binds several optionals and tests conditions in one statement. JS needs nested checks or `&&` with repeated conversions.""",
 [('js', "Write the JS equivalent without repeated `Number()` calls. What does Swift's comma-list do that `&&` can't (binding)?"),
  ('contrast', "Comma-separated conditions vs `&&`: are they the same in Swift? (Hint: bindings.)"),
  ('edge', "If `a` fails to parse, is `Int(b)` ever evaluated?"),
  ('practice', "Form validation with many fields: when does a single `if let` chain become unreadable, and what replaces it?")],
 ['if let', 'optional binding', 'multiple'], 'optionals')
E['guard-let-validate'] = ('c', """`guard let … else { return }` is the **early return** pattern JS devs use (`if (!x) return`), promoted to syntax. The compiler checks that `else` exits, and bound values stay in scope afterwards.""",
 [('js', "`if (!user) return` in JS doesn't narrow in plain JS. How does `guard let` make the unwrapped value available below?"),
  ('edge', "What happens if the `guard`'s `else` block doesn't `return`, `throw` or `break`?"),
  ('contrast', "`guard` vs `if let` pyramids: why do Swift style guides prefer `guard` for preconditions?"),
  ('practice', "Validation that returns the *first* error vs *all* errors: which is better UX on a sign-up form?")],
 ['guard', 'early exit', 'else'], 'optionals')
E['nil-coalescing-config'] = ('e', """`Int(args["port"] ?? "") ?? Int(env["PORT"] ?? "") ?? 8080` mixes optional dictionary lookups, failable parsing and fallbacks, like `Number(args.port) || Number(env.PORT) || 8080` but without the `NaN`/`0` traps.""",
 [('js', "`Number(undefined) || 8080` works by accident because NaN is falsy. What goes wrong with port `0`?"),
  ('contrast', "`flatMap(Int.init)` vs `Int(x ?? \"\")`: which avoids parsing an empty string?"),
  ('edge', "What's the type of `args[\"port\"].flatMap(Int.init)`? Why not `Int??`?"),
  ('practice', "App configuration in iOS: Info.plist, xcconfig, remote config. Which has precedence in your app?")],
 ['nil coalescing', 'config', 'default'], 'optionals')
E['optional-chaining-company'] = ('c', """Swift optional chaining (`company.ceo?.address?.city`) is JS's `?.`. The result is `String?`, and the whole chain short-circuits to `nil`. Swift checks at compile time that you didn't forget a `?`, whereas JS only fails at runtime.""",
 [('js', "JS `a.b?.c` returns `undefined`. Swift returns `nil`, and the type tells you. What does TS's `strictNullChecks` give you, and what's still missing?"),
  ('edge', "What's the type of `company.ceo?.address?.city.count`? Where does the `?` apply?"),
  ('contrast', "Deep optional chains vs flattening the model (`ceoCity: String?`): which is better for UI code?"),
  ('practice', "API responses with many optionals: when should decoding fail vs produce optionals?")],
 ['optional chaining', 'question mark', 'nil'], 'optionals')
E['optional-map-flatmap'] = ('c', """`Optional.map` is like `x?.pipe(f)` if JS had one: it applies `f` only when there's a value. `flatMap` is for when `f` itself returns an optional (like `Int.init`). It's the same `map`/`flatMap` split as for arrays; an optional is a collection of 0 or 1 values.""",
 [('js', "JS has no `Optional.map`, so you write `x == null ? null : f(x)`. Where would `.map` have simplified your JS code?"),
  ('contrast', "Why does `Optional<String>.map(Int.init)` give `Int??`, while `flatMap` gives `Int?`?"),
  ('java', "Java's `Optional` has `map` and `flatMap` too. What makes Swift optionals nicer (language syntax: `?`, `if let`, `??`)?"),
  ('practice', "`url.map { URL(string: $0) }`: where do optional transforms show up in view models?")],
 ['flatmap', 'optional', 'map'], 'optionals')
E['predict-optional-printing'] = ('e', """Printing an optional shows `Optional("x")`, a leak of the wrapper that JS doesn't have (`undefined` just prints). Interpolating optionals into UI strings is a classic bug, and the compiler warns about it.""",
 [('js', "`${undefined}` prints \"undefined\". `\"\\(optional)\"` prints `Optional(\"x\")`. Which is worse to ship to users?"),
  ('edge', "Implicitly unwrapped optionals (`String!`) print how? When do they unwrap automatically?"),
  ('contrast', "`String(describing: opt)` vs `opt ?? \"\"` vs `opt.map { \"\\($0)\" }`: when is each right?"),
  ('practice', "Where do IUOs still appear in iOS code: `@IBOutlet`? Why?")],
 ['optional', 'print', 'unwrap'], 'optionals')
E['check-password-throws'] = ('c', """Errors as enums (`enum PasswordError: Error { case short, obvious }`) are like throwing typed error objects in JS, but the catch site can pattern-match cases instead of checking `instanceof` or message strings.""",
 [('js', "JS devs often check `err.message.includes(...)`. How does an error enum make that impossible?"),
  ('contrast', "Throwing for validation vs returning a `ValidationResult`: is invalid user input really \"exceptional\"?"),
  ('practice', "How would you show these errors in a SwiftUI form (`LocalizedError.errorDescription`)?"),
  ('java', "Java would use exception subclasses. What's the enum approach's advantage when matching?")],
 ['throw', 'error', 'enum'], 'errors')
E['do-catch-patterns'] = ('c', """`catch VendingError.invalidSelection, VendingError.outOfStock` matches several patterns in one clause. JS has a single untyped `catch (e)` followed by `if` chains; Swift's catch clauses are pattern matches.""",
 [('js', "JS has one `catch (e)`. How many `instanceof` checks does this Swift code replace?"),
  ('edge', "Must a `do/catch` be exhaustive? What happens to errors no clause matches in a throwing vs non-throwing function?"),
  ('contrast', "`catch let e as VendingError` vs `catch VendingError.x`: when does each fit?"),
  ('practice', "Network errors (`URLError.notConnectedToInternet`) are commonly matched this way. Which URLError codes deserve special UI?")],
 ['catch', 'do', 'error'], 'errors')
E['try-optional'] = ('c', """`try?` converts a thrown error into `nil`, like `await p.catch(() => null)`. `try!` crashes on error, and has no JS analogue beyond an unhandled rejection. Use `try?` when *why* it failed doesn't matter.""",
 [('js', "`.catch(() => null)` is `try?`. What's `try!` in JS terms, and when is it acceptable in Swift (never in production paths)?"),
  ('edge', "What's the type of `try? f()` when `f` returns `Int?`: `Int??` or `Int?`? (It changed in Swift 5.)"),
  ('contrast', "`try?` vs `Result(catching:)`: which keeps the error around?"),
  ('practice', "`try? JSONDecoder().decode(...)` hides decoding bugs. What's the cost in debugging time?")],
 ['try?', 'optional', 'error'], 'errors')
E['defer-order'] = ('c', """`defer` runs when the scope exits, in **reverse** order of declaration, like stacked `finally` blocks, or Go's `defer`. It fits cleanup that must happen on every exit path (`return`, `throw`), which in JS takes nested `try/finally`.""",
 [('js', "Rewrite three stacked `defer`s as JS `try/finally`. How deep does the nesting get?"),
  ('edge', "Does `defer` run if the process crashes (`fatalError`)? If an error is thrown?"),
  ('contrast', "`defer` vs `deinit`-based cleanup (RAII): which is deterministic in Swift?"),
  ('practice', "Typical `defer` uses: `lock.unlock()`, `isLoading = false`, closing file handles. What's the risk of `defer { isLoading = false }` in an async function?")],
 ['defer', 'cleanup', 'reverse'], 'errors')
E['result-type'] = ('c', """`Result<Success, Failure>` is a typed either, like returning `{ ok: true, value } | { ok: false, error }` in TS. It was vital for callback APIs before async/await. Now it's mostly used to store outcomes, since `throws` covers control flow.""",
 [('js', "Is `Result` more like a Promise's settled state (`{status, value|reason}`) or an Either? Where does it fit in async/await code?"),
  ('contrast', "`throws` vs `Result`: when would you choose `Result` in 2026 Swift?"),
  ('edge', "`Result.get()` turns it back into a throw. Why is that bridge useful?"),
  ('practice', "Completion-handler APIs used `(Result<T, Error>) -> Void`. How do you wrap one with `withCheckedThrowingContinuation`?")],
 ['result', 'success', 'failure'], 'errors')
E['typed-throws'] = ('e', """Swift 6's `throws(BankError)` declares the exact error type, like Java's checked exceptions but with one type. The catch gets a `BankError`, not `any Error`. TS can't type what a function throws at all.""",
 [('js', "TS can't declare what a function throws. What does `throws(E)` let a caller do that TS can't?"),
  ('java', "Java checked exceptions are considered a mistake by many. What's different about Swift's single typed error that avoids Java's problems?"),
  ('contrast', "Typed throws vs `Result<T, E>`: which composes better with `async`?"),
  ('practice', "Swift Evolution recommends *untyped* throws for most APIs. When is typed throws worth it (embedded, exhaustive handling)?")],
 ['typed throws', 'throws', 'error'], 'errors')
E['rethrows-map'] = ('e', """`rethrows` says "I only throw if the closure you gave me throws", so `map` with a non-throwing closure needs no `try`. JS doesn't track this; every call may throw.""",
 [('js', "In JS, `arr.map(f)` might throw if `f` throws, and nothing tells you. How does `rethrows` encode that in the type?"),
  ('edge', "Can a `rethrows` function throw its *own* errors, unrelated to the closure?"),
  ('contrast', "`rethrows` vs typed throws `throws(E)` with generic `E`: is `rethrows` still needed in Swift 6?"),
  ('practice', "Which standard library functions are `rethrows`? Check `map`, `filter`, `first(where:)`.")],
 ['rethrows', 'throws', 'map'], 'errors')
E['predict-defer-throw'] = ('e', """`defer` blocks run *before* the error reaches the caller's `catch`. It's the same as `finally` running before the outer `catch` in JS, and just as easy to mis-predict.""",
 [('js', "In JS, does `finally` run before the outer `catch`? Is the ordering the same as Swift's `defer`?"),
  ('edge', "Can a `defer` block throw? What does the compiler say?"),
  ('contrast', "`defer` inside a `do` block vs at function level: which runs first?"),
  ('practice', "Logging with `defer` for timing (`let start = …; defer { log(elapsed) }`): does it capture failed paths?")],
 ['defer', 'throw', 'catch'], 'errors')
E['closure-shortening'] = ('c', """Swift's closure-shortening ladder: full syntax → inferred types → implicit return → `$0`/`$1` → trailing closure. JS arrow functions sit at about step 3. `$0` has no JS equivalent, though Kotlin's `it` is close.""",
 [('js', "`names.filter(n => n.startsWith('t'))` vs `names.filter { $0.hasPrefix(\"t\") }`: which is more readable to a newcomer? When does `$0` hurt?"),
  ('contrast', "Trailing closure syntax vs passing a function reference (`filter(isValid)`): when is each clearer?"),
  ('edge', "Why can't you use `$0` inside a nested closure to mean the outer closure's argument?"),
  ('practice', "SwiftUI is built on trailing closures (`Button { } label: { }`). What are multiple trailing closures (SE-0279)?")],
 ['closure', 'trailing', 'shorthand'], 'closures')
E['make-counter'] = ('c', """This is exactly JS's counter-closure interview question: `makeCounter` returns a closure that captures `total` **by reference**. Each call to `makeCounter` creates a fresh captured variable. Swift boxes the captured `var` on the heap.""",
 [('js', "The classic JS closure counter works identically. Where does Swift's version differ: memory management, thread safety?"),
  ('edge', "Two closures created by the same `makeCounter` call share state. What about two calls to `makeCounter`?"),
  ('contrast', "Closure counter vs a `class Counter`: which is easier to test, and which is easier to make thread-safe?"),
  ('practice', "In Swift 6, capturing a mutable `var` in a `@Sendable` closure is an error. Why?")],
 ['closure', 'capture', 'counter'], 'closures')
E['capture-list-snapshot'] = ('c', """Swift closures capture variables **by reference** (like JS). A capture list `[x]` copies the value at creation time, which JS has no syntax for; you'd use an IIFE or `const snapshot = x`.""",
 [('js', "In JS you'd write `const snap = x; () => snap`. What does `[x]` add? (Hint: it also works for `[weak self]`.)"),
  ('edge', "Is `[x]` a copy of a class instance or of the reference? What if `x` is a struct?"),
  ('contrast', "`[x]` vs `[weak x]` vs `[unowned x]`: what does each capture?"),
  ('practice', "When would you snapshot state before an async task starts, so a later change doesn't affect the request?")],
 ['capture list', 'capture', 'closure'], 'closures')
E['escaping-handlers'] = ('c', """In JS every callback can be stored for later. Swift makes you mark those parameters `@escaping`. Non-escaping closures (the default) can't outlive the call, which lets the compiler skip reference counting and makes `self` capture rules looser.""",
 [('js', "JS never distinguishes \"called now\" from \"stored for later\" callbacks. What bugs does Swift's `@escaping` annotation surface (retain cycles, reentrancy)?"),
  ('edge', "Why must you write `self.` explicitly inside escaping closures but not in non-escaping ones?"),
  ('contrast', "Stored callbacks vs Combine subjects vs `AsyncStream`: which handles unsubscribe best?"),
  ('practice', "An event bus that stores handlers forever leaks. How do you design unsubscription (tokens, `weak` observers)?")],
 ['escaping', 'closure', 'callback'], 'closures')
E['autoclosure-log'] = ('e', """`@autoclosure` wraps an argument expression in a closure automatically, so `debugLog(expensive())` doesn't evaluate `expensive()` unless needed. In JS you'd pass `() => expensive()` by hand. `assert`, `??` and `&&` all rely on it.""",
 [('js', "JS loggers take `() => msg` to be lazy. How does `@autoclosure` hide that at the call site, and is hiding it good?"),
  ('edge', "Is an `@autoclosure` argument evaluated once or every time the closure is called?"),
  ('contrast', "`@autoclosure` vs `os.Logger`'s interpolation (which is lazy too): how does Apple's logger avoid formatting cost?"),
  ('practice', "Why is `@autoclosure` discouraged for public APIs where evaluation isn't obvious?")],
 ['autoclosure', 'lazy', 'log'], 'closures')
E['sort-by-keypath'] = ('c', """Key paths like `\\Person.age` are typed property references, a type-safe version of passing `'age'` strings to lodash's `sortBy(people, 'age')`. The compiler knows `\\.age` is `KeyPath<Person, Int>`, so a typo is a compile error.""",
 [('js', "`_.sortBy(arr, 'agee')` fails silently at runtime. What does `sorted(by: \\.agee)` do?"),
  ('contrast', "Key paths vs closures `{ $0.age }`: where can a key path go that a closure can't (Hashable, SwiftData `#Predicate`, `@dynamicMemberLookup`)?"),
  ('edge', "What's the difference between `KeyPath`, `WritableKeyPath` and `ReferenceWritableKeyPath`?"),
  ('practice', "SwiftUI `ForEach(items, id: \\.id)` and `Table` columns use key paths. Why a key path rather than a closure there?")],
 ['key path', 'keypath', 'sorted'], 'keypaths')
E['compose-functions'] = ('e', """Swift lets you declare new operators like `>>>` with precedence groups. JS can't; you'd write `pipe(f, g)` or wait for the pipeline operator proposal. Generic composition `(A→B, B→C) → (A→C)` type-checks end to end.""",
 [('js', "JS's `|>` proposal has been stuck for years. What does Swift give you, and why do teams still avoid custom operators?"),
  ('contrast', "Custom operator vs a named `compose(f, g)` function: which is easier for a new teammate to search for?"),
  ('edge', "Why must operators be declared at file scope with a precedence group? What happens with `f >>> g >>> h` associativity?"),
  ('practice', "Where do custom operators legitimately show up: vector maths, parser combinators, TCA's `~>`?")],
 ['operator', 'compose', 'function'], 'operators')
E['curried-add'] = ('e', """Currying works as in JS: `add(1)(2)`. Swift's function types make it explicit (`(Int) -> (Int) -> Int`). Instance methods are curried under the hood: `Type.method` is `(Type) -> (Args) -> Result`.""",
 [('js', "`const add = a => b => a + b` in JS vs `func add(_ a: Int) -> (Int) -> Int`. Is there a difference in how captured `a` is stored?"),
  ('edge', "What's the type of `String.uppercased`, unapplied? Try `let f = String.uppercased`."),
  ('contrast', "Currying vs default parameters vs a configured struct: which does Swift code favour?"),
  ('practice', "Partial application shows up in dependency injection: `makeFetcher(session)` returns `(URL) async throws -> Data`. Where else?")],
 ['curry', 'partial', 'function'], 'closures')
E['reduce-into'] = ('c', """`reduce(into: [:]) { acc, x in acc[k, default: []].append(x) }` mutates the accumulator in place. JS `reduce` with `{...acc}` spread copies every step (O(n²)). Swift's plain `reduce` has the same copying risk, so reach for `into:`.""",
 [('js', "The JS pattern `reduce((acc, x) => ({...acc, [k]: …}), {})` is O(n²). How does `reduce(into:)` avoid that?"),
  ('contrast', "`reduce(into:)` vs `Dictionary(grouping:by:)`: which keeps first-seen order within groups?"),
  ('edge', "Why can't plain `reduce` mutate its accumulator? What's `inout` doing in `into:`?"),
  ('practice', "Bucketing items by day for a calendar list: which API would you use, and how do you get the day key?")],
 ['reduce', 'into', 'dictionary'], 'closures')
E['predict-closure-capture-loop'] = ('e', """The famous JS `var` in a loop bug (all closures see the last `i`) **doesn't happen** with Swift's `for-in`: each iteration gets a fresh `let` binding, like JS `let` in `for`. But a captured `var` outside the loop is shared.""",
 [('js', "The `for (var i…)` closure bug: does Swift's `for i in` have it? What about a `var` declared before a `while` loop?"),
  ('edge', "Capture a `var counter` in closures created in a loop, then mutate it after the loop. What do they print?"),
  ('contrast', "Capture list `[i]` vs relying on per-iteration binding: which is more explicit?"),
  ('practice', "Creating `Button`s in a `ForEach` that capture the item: why does SwiftUI not have this bug?")],
 ['closure', 'loop', 'capture'], 'closures')
E['fix-vacation-setter'] = ('c', """Computed properties with `get`/`set` are JS getters/setters (`get vacationRemaining() {}`). In the setter, `newValue` is implicit. The bug here is the round-trip rule: setting then getting must return what you set.""",
 [('js', "JS `get x()` / `set x(v)` vs Swift `var x { get set }`: what's `newValue`, and can you rename it?"),
  ('contrast', "Computed property vs method: when does something with side effects stop being a property?"),
  ('edge', "Can a computed property be `mutating` in a struct getter? What about `nonmutating set`?"),
  ('practice', "How would you unit test the \"set then get returns the same value\" law?")],
 ['computed property', 'setter', 'get'], 'structs')
E['property-observers-clamp'] = ('c', """`willSet`/`didSet` run around a stored property's change, like a JS setter wrapping a private field, or MobX reactions. They don't fire during `init`, and setting the property inside `didSet` doesn't recurse.""",
 [('js', "In JS you'd implement this with a private `_volume` and a setter. What boilerplate do observers remove?"),
  ('edge', "Do observers fire during `init`? When you pass the property as `inout`?"),
  ('contrast', "`didSet` vs a SwiftUI `.onChange(of:)`: where should clamping logic live?"),
  ('practice', "`@Published var x { didSet { … } }`: does the observer run before or after subscribers see the new value?")],
 ['didset', 'willset', 'observer'], 'structs')
E['mutating-bank-account'] = ('c', """`private(set) var funds` is a public getter with a private setter. JS would use `#funds` plus a getter. Struct methods that change properties must be `mutating`, because they replace the whole value.""",
 [('js', "JS: `#funds` + `get funds()`. Swift: `private(set)`. Which is less code, and which is enforced at compile time vs runtime?"),
  ('contrast', "Struct `BankAccount` vs `class`/`actor`: if two screens share an account, which model is right?"),
  ('edge', "Can a `mutating` method be called on a `let` constant? On an rvalue like `makeAccount().deposit(5)`?"),
  ('practice', "Money in real apps: `Decimal`, cents, or a `Money` type with currency? Where does validation belong?")],
 ['mutating', 'private set', 'struct'], 'structs')
E['custom-init-keeps-memberwise'] = ('e', """Structs get a free memberwise `init`, like a TS class with parameter properties. Writing a custom `init` inside the struct **removes** it, while writing it in an **extension** keeps both. There's no JS parallel.""",
 [('js', "TS `constructor(public name: string)` gives a free constructor. Why does Swift drop the memberwise init when you add your own?"),
  ('edge', "Is the memberwise init `public` for a public struct? (No, it's `internal`.) Why does that matter for packages?"),
  ('contrast', "Custom init in an extension vs a static factory (`Player.named(\"x\")`): which reads better?"),
  ('practice', "Previews and tests often need convenience inits. Where do you put them (`#if DEBUG` extensions)?")],
 ['init', 'memberwise', 'extension'], 'structs')
