E = {}
E['static-counter'] = ('c', """`static` members belong to the type, like JS `static` class fields. In Swift they work on structs and enums too, and `static let` is **lazily initialised and thread-safe**, which is why it's the standard singleton pattern.""",
 [('js', "JS static fields initialise when the class is evaluated. When does a Swift `static let` initialise, and who guarantees thread safety?"),
  ('java', "Java `static` + the holder idiom for lazy singletons: how does Swift's `static let` make that idiom unnecessary?"),
  ('edge', "In Swift 6, why is `static var count = 0` an error (global mutable state not concurrency-safe)? What are the fixes?"),
  ('practice', "Where does static state bite in tests: shared caches, singletons? How would you inject instead?")],
 ['static', 'type property', 'shared'], 'structs')
E['diag-mutating-let'] = ('c', """A `let` struct is fully frozen, so calling a `mutating` method on it is a compile error. JS `const` only freezes the binding, and `obj.increment()` works fine. This is value semantics enforced by the compiler.""",
 [('js', "`const c = new Counter(); c.increment()` works in JS. Why must Swift reject the struct version? What would break if it didn't?"),
  ('contrast', "The same code with `class Counter`: does it compile? Why?"),
  ('edge', "Can you call a `mutating` method on a struct stored in a `let` array element? A `let` dictionary value?"),
  ('practice', "In SwiftUI, `body` sees `self` as immutable. Is that the same rule, and why does `@State` get around it?")],
 ['mutating', 'let', 'immutable'], 'structs')
E['diag-struct-needs-mutating'] = ('c', """Struct methods can't modify `self` unless marked `mutating`, because `self` is an immutable copy inside ordinary methods. JS methods can always mutate `this`. The keyword makes mutation visible in the API.""",
 [('js', "In JS, any method can change `this`. What does Swift's `mutating` annotation tell a caller that JS never does?"),
  ('edge', "What does `mutating` do under the hood: is `self` passed `inout`?"),
  ('contrast', "Classes don't need `mutating`. Why not, and what does that say about reference types?"),
  ('practice', "Protocol requirements can be `mutating`. Why must a protocol for both structs and classes declare it?")],
 ['mutating', 'self', 'immutable'], 'structs')
E['dynamic-dispatch-employees'] = ('c', """Overriding works like JS classes (`class Developer extends Employee`), and the call goes to the runtime type (dynamic dispatch). Swift requires the `override` keyword, and `final` turns dispatch static. JS has neither.""",
 [('js', "JS prototypes dispatch dynamically always. What does Swift's `final` buy (performance, intent), and why do Swift style guides mark classes `final` by default?"),
  ('java', "Java methods are virtual by default and `@Override` is optional. Why did Swift make `override` mandatory?"),
  ('contrast', "Class inheritance vs protocol with default implementations: which does Swift prefer for sharing behaviour?"),
  ('practice', "UIKit subclassing (`UIViewController`) is everywhere. Why does SwiftUI avoid inheritance entirely?")],
 ['override', 'inheritance', 'subclass'], 'classes')
E['diag-missing-override'] = ('e', """Swift refuses a subclass method that silently shadows a superclass method. You must write `override`. In JS, redefining a method in a subclass always overrides, with no keyword and no warning when you do it by accident.""",
 [('js', "TS 4.3 added `override` with `noImplicitOverride`. Why did TS copy this from languages like Swift?"),
  ('edge', "What if the superclass later renames the method? Which language catches the now-orphaned override?"),
  ('contrast', "Overriding vs overloading: what if the subclass method has a different parameter type?"),
  ('practice', "Overriding `viewDidLoad` without calling `super.viewDidLoad()`: does Swift catch that? What's the convention?")],
 ['override', 'subclass', 'method'], 'classes')
E['diag-super-init-order'] = ('e', """**Two-phase initialisation**: a subclass must initialise its own stored properties *before* calling `super.init`. JS is the reverse: you can't touch `this` before `super()`. Swift's order guarantees no property is ever read uninitialised.""",
 [('js', "JS requires `super()` before using `this`. Swift requires your properties *before* `super.init`. Why are they opposite?"),
  ('edge', "Why can a superclass initialiser call an overridden method that reads a subclass property? What does phase 1 protect against?"),
  ('java', "Java lets the superclass constructor call an overridden method that sees uninitialised subclass fields. How does Swift prevent this bug?"),
  ('practice', "Why do UIKit subclasses so often have `required init?(coder:)` with `fatalError`?")],
 ['super.init', 'initialization', 'phase'], 'classes')
E['diag-no-initializers'] = ('e', """A class with a stored property that has no default and no initialiser doesn't compile. Swift insists every property is set before use. JS leaves it `undefined`, and TS's `strictPropertyInitialization` is an opt-in version of the same check.""",
 [('js', "TS `strictPropertyInitialization` catches this, and `!` silences it. What's Swift's equivalent escape hatch (`!` IUOs), and why is it discouraged?"),
  ('contrast', "Structs get a memberwise init for free. Why don't classes?"),
  ('edge', "Which initialisers does a subclass inherit automatically? (Rules 1 and 2 of initialiser inheritance.)"),
  ('practice', "Is this why Swift developers default to structs for models?")],
 ['initializer', 'stored property', 'class'], 'classes')
E['convenience-init'] = ('e', """Designated initialisers set every property. `convenience` initialisers must delegate to one with `self.init(...)`, like overloaded constructors calling a primary one. `init?` can fail and return `nil`, which JS constructors can't.""",
 [('js', "A JS constructor can't return `null`. How would you model \"invalid hex\" in JS: static factory or throw? What does `init?` give you?"),
  ('contrast', "Failable `init?` vs throwing `init() throws`: when should callers learn *why* it failed?"),
  ('edge', "Can a convenience init call another convenience init? Can it call `super.init`?"),
  ('practice', "`UIColor(hex:)` is a common extension. Why is it usually a convenience init?")],
 ['convenience', 'init', 'failable'], 'classes')
E['deinit-lifecycle'] = ('c', """`deinit` runs **deterministically** when the last strong reference goes away (ARC). JS garbage collection is non-deterministic, and `FinalizationRegistry` callbacks may never run. In Swift you can rely on `deinit` for cleanup such as removing observers.""",
 [('js', "JS has no destructors you can rely on. What cleanup patterns (dispose, AbortController) become simpler with deterministic `deinit`?"),
  ('java', "Java's `finalize` was deprecated for being unpredictable. Why is Swift's `deinit` predictable?"),
  ('edge', "When exactly does a local variable's object deinit: end of scope or last use? (Swift can release early after last use.)"),
  ('practice', "Printing in `deinit` is the classic way to detect view controller leaks. How would you automate it in tests?")],
 ['deinit', 'arc', 'released'], 'memory')
E['class-let-reference'] = ('c', """`let alias = original` for a class copies the **reference**, just like JS objects, so `alias.name = …` changes both. `let` freezes the reference, not the object. `===` checks identity (JS `===` on objects).""",
 [('js', "This is exactly JS object semantics. Which Swift types behave like this, and which like JS primitives?"),
  ('contrast', "`==` vs `===` in Swift: which needs `Equatable`, and which only works on classes?"),
  ('edge', "Can a struct with a `let` property holding a class instance still change observable state?"),
  ('practice', "Two SwiftUI views holding the same `@Observable` class instance: what happens when one mutates it?")],
 ['reference', 'identity', 'class'], 'classes')
E['static-vs-class-method'] = ('e', """`class func` can be overridden by subclasses, and `static func` can't (it's `final class func`). JS static methods are always inherited and overridable. Swift makes you choose.""",
 [('js', "JS `static` methods are inherited and overridable. Which Swift keyword matches that behaviour?"),
  ('contrast', "Why can structs and enums only use `static`?"),
  ('edge', "Can a `class var` be a stored property? Why not?"),
  ('practice', "Where do overridable type methods appear in UIKit (`layerClass`, `requiresConstraintBasedLayout`)?")],
 ['class func', 'static', 'override'], 'classes')
E['required-init-factory'] = ('e', """`required init` forces every subclass to implement that initialiser, so `Self(level:)` can build the dynamic subclass type. JS gets this free with `new this.constructor(...)`. Swift needs the guarantee to type-check it.""",
 [('js', "`new this.constructor()` works in JS because constructors are always callable. Why does Swift need `required` to allow `Self(...)`?"),
  ('contrast', "`Self` vs `self` vs `Type.self`: which is which?"),
  ('edge', "What happens if a subclass adds a stored property but forgets the `required init`?"),
  ('practice', "`Decodable`'s `init(from:)` must be `required` in classes. Why?")],
 ['required', 'Self', 'factory'], 'classes')
E['type-casting-zoo'] = ('c', """`as?` is a checked downcast returning an optional, `is` tests the type, and `as!` forces the cast. It's like `instanceof` plus a cast in TS. `switch` with `case let n as Int` pattern-matches on types, which TS can only approximate with type guards.""",
 [('js', "TS: `if (typeof x === 'number')` narrows. Swift: `if let n = x as? Int`. Which one works for user-defined types (not just primitives)?"),
  ('edge', "Can `[Any]` containing `1` be cast `as? Double`? Why was bridging via `NSNumber` confusing?"),
  ('contrast', "`[Any]` + casting vs an enum with associated values: which should model heterogeneous data?"),
  ('practice', "JSON as `[String: Any]` from `JSONSerialization` needs casting everywhere. Why is `Codable` better?")],
 ['as?', 'type casting', 'is'], 'casting')
E['protocol-shapes'] = ('c', """Protocols are TS interfaces, but **nominal**: a type conforms only if it declares `: Shape`, while TS matches structurally. `any Shape` is an existential box, like a TS variable typed by an interface, and works through dynamic dispatch.""",
 [('js', "TS interfaces are structural: any object with `area` fits. Swift requires declared conformance. What does each approach catch or miss?"),
  ('java', "Java interfaces are nominal too. What can Swift protocols do that Java interfaces couldn't (value types, retroactive conformance, associated types)?"),
  ('contrast', "`[any Shape]` vs `[Shape]` enum: which one allows third parties to add shapes?"),
  ('edge', "What's the runtime cost of `any Shape`: boxing, witness tables? When does it matter?")],
 ['protocol', 'conform', 'any'], 'protocols')
E['protocol-extension-default'] = ('c', """Protocol extensions provide default method implementations, like mixins or TS abstract-class defaults, but applicable to structs and enums. Conforming types get the behaviour free and can override it.""",
 [('js', "JS mixins (`Object.assign(Proto, mixin)`) vs Swift protocol extensions: which is checked at compile time?"),
  ('java', "Java 8 default methods are the closest analogue. What's different about how Swift dispatches extension-only methods?"),
  ('contrast', "Protocol extension vs base class for shared behaviour: why does Swift favour \"protocol-oriented programming\"?"),
  ('edge', "Can a protocol extension add stored properties? What do people do instead?")],
 ['protocol extension', 'default implementation', 'extension'], 'protocols')
E['predict-static-dispatch-trap'] = ('c', """Methods declared **only** in a protocol extension are dispatched **statically**: `(x as any P).nickname()` calls the extension version even if the type has its own. JS has no equivalent trap, since every call is dynamic.""",
 [('js', "In JS, which `nickname` runs is always decided by the object. What makes Swift decide by the *static type* here?"),
  ('java', "Java default methods are always virtual. Why did Swift make extension-only methods static?"),
  ('practice', "How would this bug show up in a real app, with a type that \"overrides\" a helper that never gets called?"),
  ('edge', "Fix it by adding `nickname()` to the protocol's requirements. Why does that change dispatch?")],
 ['static dispatch', 'protocol extension', 'requirement'], 'protocols')
E['comparable-version'] = ('c', """Conforming to `Comparable` means implementing `<`. You get `>`, `<=`, `sorted()`, `max()` and `clamped` for free. JS needs a comparator function passed everywhere, while Swift puts ordering on the type.""",
 [('js', "semver comparison in JS needs a library call each time. What does putting `<` on the type let every API use automatically?"),
  ('edge', "Must `\"2\" == \"2.0.0\"`? If `==` says yes but the hash differs, what breaks in a `Set<Version>`?"),
  ('contrast', "`Comparable` conformance vs `sorted(by:)` closures: when does the type have a *natural* order?"),
  ('practice', "App version checks (\"force update below 2.3\"): where does this logic live, and how do you get the app's version?")],
 ['comparable', 'version', 'less than'], 'protocols')
E['protocol-composition-delegate'] = ('c', """Delegation is Apple's callback pattern: an object holds a `weak var delegate: P?` and calls methods on it. It's like passing an event-handler object in JS, but `weak` is required to avoid retain cycles, and `AnyObject` restricts the protocol to classes.""",
 [('js', "JS event emitters hold strong references to listeners too. Why doesn't that leak in JS (GC handles cycles) but does in Swift (ARC doesn't)?"),
  ('contrast', "Delegate vs closure callback vs Combine vs async sequence: which does modern Swift prefer, and when is a delegate still best?"),
  ('edge', "Why must the protocol be `: AnyObject` to be used with `weak`?"),
  ('practice', "`UITableViewDelegate` and `UITextFieldDelegate`: what would the SwiftUI equivalent be?")],
 ['delegate', 'weak', 'protocol'], 'memory')
E['extension-int-helpers'] = ('e', """Extensions add methods and computed properties to existing types, even `Int`. That's like patching `Number.prototype`, but scoped by module and resolved at compile time, so it's safe and common in Swift.""",
 [('js', "Extending `Number.prototype` is taboo in JS. Why is `extension Int` acceptable in Swift? What prevents collisions between libraries?"),
  ('edge', "Can an extension override an existing method? Add a stored property?"),
  ('contrast', "`5.times { }` (Ruby-style) vs a plain `for _ in 0..<5`: is the extension worth it?"),
  ('practice', "Which extensions are common in iOS codebases, like `Date` formatting or `View` modifiers? When do they become a dumping ground?")],
 ['extension', 'int', 'computed property'], 'extensions')
E['extension-protocol-conformance'] = ('c', """**Retroactive conformance**: you can make `Int` or `Array` adopt your protocol after the fact. TS gets this for free structurally, while nominal Swift needs an explicit `extension Int: Summarizable`. Conditional conformance (`where Element: Summarizable`) is what makes it powerful.""",
 [('js', "In TS, `Int` would \"conform\" automatically if it had `summary`. What does Swift's explicit conformance buy you?"),
  ('edge', "What's the Swift 6 warning about retroactively conforming a type you don't own to a protocol you don't own (`@retroactive`)?"),
  ('contrast', "Conditional conformance vs a wrapper type: when is each cleaner?"),
  ('practice', "Making `URL: Identifiable` for a `ForEach`: why is that risky in a shared codebase?")],
 ['retroactive', 'conformance', 'extension'], 'protocols')
E['diag-private-access'] = ('c', """`private` restricts access to the enclosing declaration and its extensions in the same file. JS `#private` fields are the closest match, but Swift has five levels (`private`, `fileprivate`, `internal`, `package`, `public`/`open`), all checked at compile time.""",
 [('js', "JS `#field` is enforced at runtime. TS `private` is compile-time only (erasable). Which does Swift's `private` resemble?"),
  ('contrast', "`private` vs `fileprivate` vs `internal`: which is Swift's default, and why is it `internal`?"),
  ('edge', "Can an extension in the same file see a `private` member? One in another file?"),
  ('java', "Java's package-private is the default. What's the closest Swift equivalent (`internal` for modules, `package`)?")],
 ['private', 'access control', 'fileprivate'], 'access')
E['diag-existential-member'] = ('c', """Through `any Vehicle` you can only call what the protocol declares, the same as a TS variable typed as an interface. To reach `openSunroof()` you downcast (`as? Car`), which is where the design question starts.""",
 [('js', "TS also hides extra members behind an interface type. What's the Swift equivalent of a TS type guard?"),
  ('contrast', "Downcasting from `any Vehicle` vs adding the method to the protocol vs generics `<V: Vehicle>`: which respects the abstraction?"),
  ('edge', "With `func commute<V: Vehicle>(_ v: V)`, can you call `openSunroof()`? Why not?"),
  ('practice', "When you find yourself downcasting a protocol a lot, what does that suggest about your abstraction?")],
 ['existential', 'any', 'member'], 'protocols')
E['abstract-class-emulation'] = ('e', """Swift has no `abstract` keyword (TS does). The idiomatic replacement is a protocol with required members plus an extension with the template method. The compiler then enforces the \"abstract\" parts.""",
 [('js', "TS `abstract class Report { abstract rows(): string[] }`: what does the Swift protocol + extension approach do better or worse?"),
  ('java', "Java's abstract classes can hold state; protocols can't. How do you share state in Swift then?"),
  ('contrast', "Class with `fatalError(\"subclass must override\")` vs protocol: which fails at compile time?"),
  ('practice', "`UIViewController` subclasses with required overrides are a UIKit pattern. How does SwiftUI replace it?")],
 ['abstract', 'protocol', 'template'], 'protocols')
E['design-min-stack'] = ('e', """The same algorithm as in JS (a parallel stack of running minimums). Swift makes it a `struct` with `mutating` methods, so a `MinStack` copy is independent. In JS, two variables would share one stack object.""",
 [('contrast', "Struct `MinStack` vs class: what does copying a struct stack cost thanks to copy-on-write?"),
  ('js', "In JS you'd implement this as a class. What changes for callers when it's a Swift struct?"),
  ('edge', "Should `pop()` on empty return `nil` or trap? What does `popLast()` vs `removeLast()` do?"),
  ('practice', "Undo stacks in editors are stacks with extra state. Where would you use a min/max-tracking stack?")],
 ['stack', 'min', 'push'], 'data-structures')
E['design-parking-lot'] = ('e', """A classic OOD interview question. The Swift angle: a `final class` for shared mutable state, an `enum` for car size instead of magic ints, and the question of whether it needs to be an `actor` once several threads park cars.""",
 [('contrast', "Class vs actor for `ParkingLot`: when do concurrent `park` calls make a class unsafe?"),
  ('js', "Node's single thread makes this safe in JS. Why doesn't that apply in Swift?"),
  ('practice', "Model car sizes as `enum CarSize: Int`. What does the raw value give you, and what does it risk?"),
  ('edge', "Should a small car be allowed into a big slot? How would you change the design for that rule?")],
 ['class', 'design', 'parking'], 'design')
E['predict-for-var-copy'] = ('c', """`for var item in items` gives you a **copy** of each struct, so mutating it doesn't touch the array. In JS, `for (const o of arr) o.x = 1` mutates the shared objects. To mutate in place in Swift, loop over indices or use `for i in items.indices`.""",
 [('js', "In JS mutating loop items changes the array's objects. Why doesn't Swift, and how do you write the in-place version?"),
  ('contrast', "`items.indices` loop vs `items = items.map { … }` vs `for i in 0..<items.count`: which is idiomatic?"),
  ('edge', "What if the elements are class instances? Does `for item in items { item.x = 1 }` mutate?"),
  ('practice', "`ForEach($items) { $item in … }` in SwiftUI binds each element. How does that solve this problem for UI?")],
 ['for', 'copy', 'struct'], 'value-types')
E['predict-observers-init'] = ('e', """Property observers **don't fire** when the property is set in the type's own `init`, but they do fire for later assignments. JS setters fire during the constructor too. It's a common \"why didn't my didSet run?\" surprise.""",
 [('js', "A JS setter runs even in the constructor. Why did Swift choose not to fire observers in init?"),
  ('edge', "Do observers fire when a *subclass* init sets an inherited property? (Yes, after `super.init`.)"),
  ('contrast', "`didSet` vs setting a value in `init` and calling a `configure()` method: which is clearer?"),
  ('practice', "A view model with `didSet { save() }`: does it save the initial value? Should it?")],
 ['didset', 'init', 'observer'], 'structs')
E['predict-lazy-order'] = ('e', """`lazy var` evaluates its initialiser on first access, like a memoised JS getter. A computed property re-runs every time, and a closure-initialised stored property (`= { … }()`) runs once at init.""",
 [('js', "How would you write a lazy memoised property in JS (getter + `Object.defineProperty`)? What does Swift's `lazy` do for you?"),
  ('edge', "Is `lazy var` thread-safe? What happens when two threads touch it first at the same time?"),
  ('contrast', "`lazy var` vs computed `var` vs `let x = { … }()`: when does each closure run, and how many times?"),
  ('practice', "`lazy var dateFormatter` is a classic. Why are formatters worth caching?")],
 ['lazy', 'computed', 'closure'], 'structs')
E['predict-deinit-order'] = ('c', """ARC releases an object the moment its last strong reference disappears, so the order of `deinit` output follows your code exactly. JS GC timing is unobservable. This predictability is why retain cycles matter so much in Swift.""",
 [('js', "Could you write this program in JS and predict when objects are collected? Why not?"),
  ('edge', "Does setting a variable to `nil` always deinit the object immediately? What if another reference exists?"),
  ('java', "Java GC collects cycles. Swift ARC doesn't. What's the trade-off (pause-free, deterministic vs leak-prone)?"),
  ('practice', "Instruments' Memory Graph debugger shows retain cycles. What would a leaking view controller look like there?")],
 ['deinit', 'reference count', 'nil'], 'memory')
E['predict-static-lazy'] = ('e', """Global and `static let` values are initialised lazily on first access, and atomically (via `dispatch_once`-style guarantees). JS module-level constants run eagerly when the module loads.""",
 [('js', "JS module top-level code runs at import. When does a Swift global `let` initialise? What about in `main.swift`?"),
  ('edge', "Globals in `main.swift` behave differently: they're initialised eagerly in order. Why is that a trap?"),
  ('contrast', "Lazy `static let` singleton vs dependency injection: which is easier to reset between tests?"),
  ('practice', "Heavy work in a `static let` initialiser can slow the first screen. How would you find that with Instruments?")],
 ['static', 'lazy', 'global'], 'structs')
E['predict-optional-chaining-assign'] = ('e', """Assigning through an optional chain (`person?.name = "x"`) returns `Void?`: `nil` if the assignment didn't happen. JS's `?.` can't be assigned through at all, since `a?.b = 1` is a syntax error.""",
 [('js', "`a?.b = 1` is invalid JS. What does Swift give you, and how do you check whether it happened?"),
  ('edge', "What does `dict[\"k\"]?.append(1)` do when the key is missing? Is that a silent bug?"),
  ('contrast', "`if (x?.y = 1) != nil` vs `if let x { x.y = 1 }`: which is clearer?"),
  ('practice', "Updating nested optional model fields in a view model: when do you want the chain to silently no-op?")],
 ['optional chaining', 'assignment', 'nil'], 'optionals')
E['predict-set-dictionary-order'] = ('c', """Swift randomises hashing **per process** (hash-flooding protection), so `Set` and `Dictionary` iteration order changes between runs. JS `Set` and `Map` keep insertion order. Never print or test raw iteration order in Swift.""",
 [('js', "JS guarantees insertion order for `Map`/`Set`. What design goal made Swift give that up?"),
  ('practice', "A snapshot test of `\"\\(dictionary)\"` passes locally and fails on CI. Why? How do you fix the test?"),
  ('edge', "Can you disable per-process seeding for debugging? (`SWIFT_DETERMINISTIC_HASHING`)"),
  ('contrast', "When do you need `OrderedDictionary` (swift-collections) vs sorting keys at display time?")],
 ['order', 'dictionary', 'set'], 'dictionaries')
E['predict-string-indices'] = ('c', """`String` isn't an array. `s.count` walks graphemes, `s.first` is a `Character?`, and slices are `Substring`s sharing storage. Coming from JS's `s[0]` and `s.length`, every one of these needs rewiring.""",
 [('js', "List three JS string operations that are O(1) in JS but O(n) in Swift. Why does Swift accept that?"),
  ('edge', "`\"e\\u{301}\" == \"é\"`: true or false in Swift? In JS?"),
  ('contrast', "`String` vs `[Character]` vs `Data`: when would you convert to each?"),
  ('practice', "Text truncation for a UI label: should you truncate by `Character` count or let the UI do it? Why?")],
 ['string index', 'character', 'unicode'], 'strings')
E['predict-switch-where-fallthrough'] = ('e', """Swift `switch` subtleties: the first matching case wins, `where` guards a case, `fallthrough` skips the next case's pattern check, and there's no implicit fall-through. They map loosely to JS's `switch(true)` idioms, but are checked by the compiler.""",
 [('edge', "`fallthrough` runs the next case's body without checking its pattern. What surprise does that create with `where` clauses?"),
  ('js', "Which JS `switch` behaviours are gone in Swift, and which are new?"),
  ('contrast', "Overlapping ranges in cases: does the compiler warn? What does \"first match wins\" mean for ordering?"),
  ('practice', "Would you allow `fallthrough` in your team's style guide?")],
 ['switch', 'where', 'fallthrough'], 'switch')
E['nested-types-cards'] = ('e', """Nested types (`Card.Suit`) namespace related types, like TS namespaces or static inner classes. Synthesised `Comparable` for raw-value enums (declaration order) plus `CaseIterable` build a full deck in one line.""",
 [('js', "TS would use separate `Suit` and `Rank` exports. What does nesting (`Card.Suit`) add?"),
  ('java', "Java static nested classes and enums are similar. Any differences?"),
  ('edge', "For a `Rank: Int` enum, is `<` based on raw values or declaration order?"),
  ('practice', "Nesting is common for `Model.ID`, `View.Style`, `Error`. When does nesting hurt discoverability?")],
 ['nested type', 'enum', 'caseiterable'], 'enums')
E['custom-string-convertible'] = ('e', """`CustomStringConvertible.description` is JS's `toString()`. `CustomDebugStringConvertible` controls debugger and `debugPrint` output, like Node's `util.inspect.custom`. Interpolation uses `description`.""",
 [('js', "JS `toString()` vs `[util.inspect.custom]`: which Swift protocols map to each?"),
  ('practice', "Should `description` be user-facing? (No: use formatters or `LocalizedStringResource`.) Why not?"),
  ('edge', "Negative cents: `-$0.50` vs `$-0.50`. Who decides? What does `formatted(.currency)` do?"),
  ('contrast', "`description` vs `dump()` vs `Mirror`: which reflects all stored properties?")],
 ['description', 'customstringconvertible', 'print'], 'protocols')
E['for-case-optional'] = ('e', """`for case let x? in values` iterates only the non-nil values: pattern matching in a loop. JS would use `.filter(x => x != null)`. Swift can pattern-match in `for`, `if`, `guard` and `while`.""",
 [('js', "`for (const x of arr.filter(v => v != null))` vs `for case let x? in arr`: which allocates an intermediate array?"),
  ('contrast', "`for case let x?` vs `compactMap { $0 }`: when is each clearer?"),
  ('edge', "What does `for case .some(let x) in values` mean? Is it the same thing?"),
  ('practice', "Where would a `where` clause on a `for case` loop help in real code?")],
 ['for case', 'optional', 'pattern'], 'optionals')
E['builder-pattern-copy'] = ('c', """Fluent builders that return **modified copies** of a struct (`request.method("POST").path("/x")`) give immutable-by-default configuration. It's the same idea as SwiftUI modifiers, and like immutable builders in JS (Immer, or spreading objects).""",
 [('js', "JS `{...req, method: 'POST'}` copies shallowly. Does a Swift struct copy deeply? What about a `[String: String]` headers property?"),
  ('contrast', "Non-mutating fluent methods vs `mutating` setters: which is more composable?"),
  ('edge', "Returning `Self` vs the concrete type: when does `Self` matter (protocol extensions)?"),
  ('practice', "SwiftUI modifiers return new views. How is `Text(\"x\").bold().padding()` this same pattern?")],
 ['builder', 'copy', 'fluent'], 'value-types')
E['tuple-swap-fibonacci'] = ('e', """`(a, b) = (b, a + b)` updates both at once with no temporary variable. JS array destructuring `[a, b] = [b, a + b]` does the same, but allocates an array, while Swift tuples are free.""",
 [('js', "JS `[a, b] = [b, a + b]` allocates an array. Does the Swift tuple version allocate anything?"),
  ('edge', "`fib(93)` overflows `Int`. What's the right return type for bigger n?"),
  ('contrast', "Iterative with tuple assignment vs recursive with memoisation: which is idiomatic Swift?"),
  ('practice', "Euclid's GCD appears in aspect-ratio simplification (16:9). Where else in UI code?")],
 ['tuple', 'swap', 'fibonacci'], 'tuples')
E['dictionary-unique-keys'] = ('e', """`Dictionary(uniqueKeysWithValues:)` **traps** on duplicate keys, while `Object.fromEntries` in JS just lets the last one win. The `uniquingKeysWith:` variant makes you decide the merge rule.""",
 [('js', "`Object.fromEntries` silently keeps the last duplicate. Is trapping better for data you believe is unique?"),
  ('edge', "Why is trapping here a design choice rather than throwing?"),
  ('contrast', "`Dictionary(grouping:)` vs `uniquingKeysWith:`: when do you want all values vs one merged value?"),
  ('practice', "Server data with duplicate IDs happens. What should the app do, and should it log?")],
 ['dictionary', 'duplicate', 'unique'], 'dictionaries')
E['zip-enumerated'] = ('e', """`zip(names, times)` pairs two arrays and stops at the shorter, like lodash `zip` but without `undefined` padding. `enumerated()` gives `(offset, element)`, like JS's `entries()`.""",
 [('js', "lodash `zip` pads with `undefined`. Swift `zip` truncates. Which is safer?"),
  ('edge', "`enumerated()` offsets on an `ArraySlice` start at 0, not at the slice's index. Why does that bite?"),
  ('contrast', "`zip(a.indices, a)` vs `enumerated()`: which gives real indices?"),
  ('practice', "Parallel arrays are a smell. When would you refactor into `[Runner]` structs instead?")],
 ['zip', 'enumerated', 'pairs'], 'collections')
E['stdio-bank-ledger'] = ('e', """Command processing with an error enum and a `do/catch` per line. The Swift equivalent of a JS REPL loop with `try/catch`, but with typed error cases the catch can pattern-match.""",
 [('contrast', "Throwing per command vs returning `Result` per command: which is easier to log?"),
  ('js', "In JS, you'd `throw new Error('insufficient')`. What information does `insufficient(needed:)` carry that a message string loses?"),
  ('edge', "What happens with `withdraw 1e3`, or `deposit -0`? Where should parsing reject input?"),
  ('practice', "Ledgers in real apps must be append-only and idempotent. What does that change?")],
 ['error', 'catch', 'command'], 'errors')
E['protocol-default-args'] = ('e', """Protocol requirements can't declare default argument values, so you add an overload in a protocol extension that forwards with the default. TS interfaces can mark parameters optional (`urgent?: boolean`), which Swift can't express in a protocol.""",
 [('js', "TS `send(msg: string, urgent?: boolean)` in an interface. Why can't Swift protocols have defaults?"),
  ('edge', "If a conforming type also defines `send(_:)` with one argument, which one runs through an `any Notifier`?"),
  ('contrast', "Extension overload vs a `SendOptions` struct parameter with defaults: which evolves better?"),
  ('practice', "This pattern shows up in logging and analytics protocols. Where have you seen it?")],
 ['protocol', 'default', 'argument'], 'protocols')
E['diag-protocol-default-arg'] = ('e', """The compiler forbids default arguments in protocol requirements, because defaults are a caller-side convenience and the requirement is the implementation contract. Use a protocol extension overload instead.""",
 [('js', "Why can TS optional parameters live in interfaces while Swift defaults can't live in protocols?"),
  ('contrast', "Default value in the implementing type vs in an extension overload: which does an `any P` caller see?"),
  ('edge', "Can a protocol requirement have a default *implementation* but not a default *argument*? What's the difference?"),
  ('practice', "When designing a protocol for mocking in tests, how do defaults affect your mocks?")],
 ['default argument', 'protocol', 'requirement'], 'protocols')
E['diag-weak-let'] = ('c', """A `weak` reference must be an optional `var`, because ARC sets it to `nil` automatically when the object dies. JS `WeakRef` is similar (`deref()` can return `undefined`), but Swift makes the nil-ing visible in the type.""",
 [('js', "JS `WeakRef.deref()` may return `undefined`. How does Swift's `weak var x: T?` express the same thing in the type?"),
  ('contrast', "`weak` vs `unowned`: which one crashes if the object is gone? When is `unowned` justified?"),
  ('edge', "Can a `weak` reference point to a struct? Why not?"),
  ('practice', "`weak var delegate` is idiomatic. What goes wrong if you forget `weak`?")],
 ['weak', 'optional', 'var'], 'memory')
E['queue-two-stacks'] = ('e', """The classic amortised O(1) queue. The Swift twist: `peek` must be non-mutating, which forces you to reason about which stack holds the front without moving elements. A JS class wouldn't enforce that.""",
 [('contrast', "Two-stack queue vs `removeFirst()` on an array (O(n)) vs swift-collections `Deque`: which would you ship?"),
  ('edge', "Why does making `peek` a non-mutating computed property complicate the design?"),
  ('js', "JS `array.shift()` is O(n) too (usually). Does V8 optimise it?"),
  ('practice', "Upload queues and message queues in apps: which operations dominate?")],
 ['queue', 'stack', 'amortized'], 'data-structures')
E['fix-force-unwrap'] = ('c', """`!` force-unwraps an optional and **crashes** on `nil`. It's the equivalent of JS code that assumes a value exists and throws `TypeError: cannot read property of undefined`, except Swift makes every such spot visible with `!`.""",
 [('js', "Every property access in JS is an implicit `!`. What does it mean that Swift makes you *write* the `!`?"),
  ('practice', "Is `!` ever acceptable in production code: `IBOutlet`s, `URL(string: \"https://apple.com\")!`? What's your rule?"),
  ('contrast', "`guard let` + skip vs `compactMap` vs throwing a parse error: which is right for malformed input lines?"),
  ('edge', "Crash logs for force-unwrap show \"Unexpectedly found nil\". How do you find which line in a release build (symbolication)?")],
 ['force unwrap', 'crash', 'nil'], 'optionals')
E['checkpoint-6-car'] = ('e', """A struct with `let` constants, `private(set)` state and a `mutating` method that validates. Encapsulation in Swift is compile-time and costs nothing at runtime, unlike JS `#private`.""",
 [('js', "Write this with JS `#gear`. Which invalid states can JS code still create that Swift's compiler prevents?"),
  ('contrast', "Returning `Bool` from `changeGear` vs throwing vs `precondition`: what should an invalid gear change do?"),
  ('edge', "`private(set)` on a `let`: meaningful? Why or why not?"),
  ('practice', "Where do you see `private(set)` in view models (`@Published private(set) var`)?")],
 ['private set', 'struct', 'mutating'], 'structs')
E['checkpoint-7-animals'] = ('e', """Class hierarchies with overrides and custom initialisers, as in JS `class Dog extends Animal`. Swift adds rules: designated initialisers, `super.init`, `override` and `final`. They feel heavy because Swift steers you towards protocols and structs.""",
 [('js', "How many of Swift's class rules have no JS equivalent? Which one catches the most bugs?"),
  ('contrast', "Rewrite with a protocol `Animal` and structs. What do you lose? (Shared stored `legs`.)"),
  ('edge', "Does `Poodle` inherit `Dog`'s initialisers automatically? When would it stop?"),
  ('practice', "Why are deep class hierarchies rare in modern Swift apps?")],
 ['inheritance', 'subclass', 'override'], 'classes')
E['checkpoint-8-building'] = ('e', """A protocol with a default `salesSummary()` in an extension. This is protocol-oriented programming, sharing behaviour across `House` and `Office` structs without a base class. TS would use an abstract class or a mixin.""",
 [('js', "TS abstract class vs Swift protocol extension: which lets `House` also conform to other protocols freely?"),
  ('contrast', "Put `salesSummary` in the extension vs as a requirement: how does that change dispatch (recall the dispatch trap)?"),
  ('edge', "How do you get the type name (`House`) generically: `String(describing: Self.self)`?"),
  ('practice', "Protocol-oriented design is a Swift talking point (WWDC 2015). Where does it go too far?")],
 ['protocol', 'extension', 'building'], 'protocols')
E['checkpoint-9-optional-random'] = ('e', """One line: `(array?.randomElement()) ?? Int.random(in: 1...100)`, mixing optional chaining, a method that itself returns an optional, and `??`. In JS: `arr?.[Math.floor(...)] ?? ...`.""",
 [('js', "Write the JS version. How many edge cases (empty array, undefined) does it handle implicitly vs explicitly?"),
  ('edge', "`array?.randomElement()` is `Int?`, not `Int??`. Why does optional chaining flatten?"),
  ('contrast', "Deterministic tests need injected randomness. How would you inject a `RandomNumberGenerator`?"),
  ('practice', "Where do apps use randomness (shuffle, A/B) and why should tests control it?")],
 ['optional', 'random', 'nil coalescing'], 'optionals')
E['stdlib-my-map'] = ('e', """Writing `map` yourself shows what JS's `Array.prototype.map` hides: `reserveCapacity(underestimatedCount)` avoids reallocations, `rethrows` propagates errors, and generics keep it type-safe for any `Sequence`.""",
 [('js', "JS `map` exists only on arrays (plus typed arrays). What does writing it on `Sequence` give you?"),
  ('edge', "Why `underestimatedCount` and not `count`? What sequences can't know their count?"),
  ('contrast', "Eager `map` vs `lazy.map`: when does each run the closure?"),
  ('practice', "Reading standard library source (github.com/swiftlang/swift) is a great learning move. What surprised you?")],
 ['map', 'sequence', 'generic'], 'generics')
E['stdlib-my-compactmap'] = ('e', """`compactMap` is `map` + `filter(x => x != null)` in one pass, typed so the result is non-optional. JS has no equivalent. `flatMap` with an empty array return is the usual hack.""",
 [('js', "JS: `arr.flatMap(x => { const n = parse(x); return n == null ? [] : [n] })`. Why is Swift's version cleaner?"),
  ('edge', "What's the result type of `compactMap` on `[Int??]`? Does it unwrap one level or two?"),
  ('contrast', "`compactMap` vs `flatMap` history: why was `flatMap` for optionals renamed in Swift 4.1?"),
  ('practice', "Parsing API arrays leniently (skip bad elements) vs strictly: where do you want each?")],
 ['compactmap', 'optional', 'nil'], 'generics')
E['stdlib-my-flatmap'] = ('e', """Same as JS `flatMap`: map each element to a sequence, then concatenate. Swift's generic signature `<S: Sequence>(…) -> [S.Element]` accepts any sequence type, not just arrays.""",
 [('js', "JS `flatMap` only flattens one level of arrays. Is Swift's the same?"),
  ('contrast', "`flatMap` vs `joined()` vs `reduce([], +)`: which is O(n²)?"),
  ('edge', "Can the transform return a `String` (a sequence of `Character`s)? What would you get?"),
  ('practice', "Flattening sections into rows for a list is flatMap. Where else?")],
 ['flatmap', 'sequence', 'flatten'], 'generics')
E['stdlib-my-contains'] = ('e', """Two overloads: `contains(where:)` for any element, and `contains(_:)` only `where Element: Equatable`. This is **conditional API availability**, which JS/TS can only approximate with overloads on generic constraints.""",
 [('js', "TS can't add a method that exists only when `T extends Equatable`. What does Swift's constrained extension enable?"),
  ('edge', "If a type is `Equatable` and you pass a closure, which overload is chosen?"),
  ('contrast', "Constrained extension `where Element: Equatable` vs a generic function: which reads better at the call site?"),
  ('practice', "Look at `Array.firstIndex(of:)` vs `firstIndex(where:)` in the standard library. Same pattern?")],
 ['contains', 'equatable', 'where'], 'generics')
E['algorithms-chunked-by'] = ('e', """`chunked(on:)` groups **consecutive** elements with the same key, unlike `Dictionary(grouping:)`, which groups all of them. lodash has no direct equivalent. It comes from Apple's swift-algorithms package, Swift's \"lodash\".""",
 [('js', "Is swift-algorithms Swift's lodash? What does adding a package cost in an iOS app (binary size, build time)?"),
  ('contrast', "Consecutive grouping vs global grouping: which one does a chat UI's \"messages by day\" need?"),
  ('edge', "What's the return type in swift-algorithms (`ChunkedOnCollection`, lazy)? Why lazy?"),
  ('practice', "Grouping consecutive messages from the same sender into bubbles is exactly this. Try it.")],
 ['chunked', 'algorithms', 'group'], 'algorithms-pkg')
E['algorithms-uniqued'] = ('e', """`uniqued(on:)` keeps the first element per key, in order. It's lodash's `uniqBy`. Swift needs the key to be `Hashable`, which JS's `Set` doesn't check.""",
 [('js', "lodash `uniqBy(arr, 'id')` vs `uniqued(on: \\.id)`: what does the key path add?"),
  ('contrast', "`uniqued` vs `Set` vs `OrderedSet`: which preserves order and which lets you choose the key?"),
  ('edge', "Is `uniqued(on:)` stable? Which duplicate wins?"),
  ('practice', "Deduplicating paginated API results where pages overlap: this is exactly it.")],
 ['uniqued', 'unique', 'algorithms'], 'algorithms-pkg')
E['algorithms-windows'] = ('e', """`windows(ofCount:)` gives sliding windows as slices without copying, and `adjacentPairs()` gives neighbours. JS would loop with indices and `slice`, which copies every window.""",
 [('js', "JS `slice` for each window copies k elements. What does returning `SubSequence` avoid?"),
  ('contrast', "Sliding-window sum recomputed per window vs incrementally: O(nk) vs O(n)."),
  ('edge', "What does `windows(ofCount: 0)` or a count larger than the collection return?"),
  ('practice', "Moving averages for charts (heart rate, stock price) use windows. Where would you compute them?")],
 ['windows', 'adjacent', 'sliding'], 'algorithms-pkg')
E['closures-as-parameters'] = ('c', """Passing closures with parameters and return values is JS callbacks with types: `(String, Int) -> String`. Trailing-closure syntax is what makes SwiftUI's DSL read naturally.""",
 [('js', "Callback typing in TS (`(stop: string, leg: number) => string`) vs Swift: what's different about argument labels in closure types?"),
  ('edge', "Closure parameter types can't have argument labels. Why?"),
  ('contrast', "Closure parameter vs protocol with one method: when does each scale better?"),
  ('practice', "How many trailing closures does `Button(action:label:)` take, and how does multiple-trailing-closure syntax write it?")],
 ['closure', 'parameter', 'trailing'], 'closures')
E['returning-closures'] = ('c', """Returning closures from functions is JS's factory pattern: a function that returns a configured function. Captured values live on the heap, the same as in JS.""",
 [('js', "`const makeDiscount = code => price => …` in JS. What does Swift's `(Int) -> Int` return type make explicit?"),
  ('contrast', "Returning a closure vs returning an enum `Discount` with an `apply` method: which is easier to test and serialise?"),
  ('edge', "Returned closures escape. Why don't you write `@escaping` on a return type?"),
  ('practice', "Discount codes come from the server. Should they map to closures, or to data the client interprets?")],
 ['closure', 'return', 'function type'], 'closures')
E['typealias-closures'] = ('c', """A `typealias` for closure types is TS's `type Validator = (s: string) => string | null`. In Swift 6, storing closures in globals requires `@Sendable`, because globals are shared across threads.""",
 [('js', "Why doesn't JS care whether a callback is \"sendable\"? What's different about Swift's threading model?"),
  ('edge', "Remove `@Sendable` and read the Swift 6 error. What's the fix if the closure captures non-Sendable state?"),
  ('contrast', "Array of validator closures vs a `Validator` protocol with structs: which is easier to log or identify in errors?"),
  ('practice', "Form validation pipelines in real apps: where do validation rules live, and do they share code with the backend?")],
 ['typealias', 'closure', 'sendable'], 'closures')
E['models-sort-filter-map'] = ('c', """`filter`, `sorted(by:)` and `map` on an array of model structs is the bread and butter of view models. It's identical in spirit to JS array chains, but on value types with compile-time-checked properties.""",
 [('js', "In JS, a typo like `u.pionts` gives `undefined` silently. What does Swift do, and how much does that matter in view models?"),
  ('contrast', "Filtering in the view model vs in the query (SwiftData `#Predicate`, SQL): which scales to 10k items?"),
  ('edge', "Sorting by points desc then name asc: why is a tuple comparison the neat trick here?"),
  ('practice', "Where would you put this transform so SwiftUI doesn't recompute it on every render?")],
 ['sort', 'filter', 'map'], 'closures')
E['oop-bank-accounts'] = ('e', """Classic OOP in Swift: a base class with `private(set)` state, a `final` subclass overriding `withdraw`. It's familiar from JS classes. The Swift-specific parts are `override`, `final` and compile-time access control.""",
 [('js', "How would JS `#balance` interact with a subclass that needs to read it? What does Swift's `private(set)` allow instead?"),
  ('contrast', "Inheritance vs composition (`Account` holding a `WithdrawalPolicy`): which is easier to extend with new account types?"),
  ('edge', "`override func withdraw` calling `super.withdraw`: what if the base changes its rules?"),
  ('practice', "Should money-handling types be classes at all, or actors, given concurrent access?")],
 ['class', 'inheritance', 'private'], 'classes')
E['localized-error'] = ('c', """`LocalizedError` adds `errorDescription` and `recoverySuggestion` for user-facing messages, like giving JS `Error` a friendly `message` plus a hint. SwiftUI's `.alert(isPresented:error:)` reads these directly.""",
 [('js', "JS errors have one `message` for devs and users alike. Why separate developer description from user-facing text?"),
  ('practice', "How does SwiftUI's `alert(isPresented:error:actions:)` use `LocalizedError`?"),
  ('contrast', "`LocalizedError` vs `CustomNSError` vs plain `Error`: which does `error.localizedDescription` use?"),
  ('edge', "Errors thrown from `URLSession` are `URLError`. How do you map them to your own user-facing errors?")],
 ['localizederror', 'error description', 'alert'], 'errors')
E['result-map-flatmap'] = ('e', """Chaining `Result` with `map` and `flatMap` is railway-oriented programming: errors short-circuit, and success values flow on. It's like chaining `.then()` on Promises, but synchronous and with typed errors.""",
 [('js', "Promise `.then` flattens automatically. Why does Swift need both `map` and `flatMap` on `Result`?"),
  ('contrast', "`Result` chain vs `do/try` with throwing functions: which is more readable in 2026 Swift?"),
  ('edge', "What does `mapError` let you do at a module boundary?"),
  ('practice', "Where do `Result` chains still show up: Combine, completion handlers, stored outcomes?")],
 ['result', 'flatmap', 'map'], 'errors')
E['identifiable-dedupe'] = ('c', """`Identifiable` gives models a stable `id`, the Swift equivalent of React's `key` prop. SwiftUI's `ForEach` and `List` use it to diff rows. Updating by ID with `firstIndex(where:)` is the standard mutation pattern.""",
 [('js', "React's `key` prop and SwiftUI's `Identifiable`: what goes wrong in each when IDs are unstable (array index as key)?"),
  ('contrast', "`Identifiable` vs `Hashable` vs `Equatable`: what does each do for SwiftUI?"),
  ('edge', "Two items with the same `id` in a `ForEach`: what happens? (Undefined, logs a warning.)"),
  ('practice', "IDs: `UUID()` generated client-side vs server IDs. What breaks when you create an item offline?")],
 ['identifiable', 'id', 'foreach'], 'protocols')
E['comparable-enum-synthesis'] = ('e', """Enums without raw values get `Comparable` synthesised from **declaration order** (Swift 5.3). TS enums compare by their numeric values, and string enums alphabetically, which is rarely what you want.""",
 [('js', "TS numeric enums compare by value. Swift compares by declaration order. What happens if someone reorders the cases?"),
  ('edge', "Can an enum with associated values be `Comparable` automatically? What's compared?"),
  ('contrast', "Declaration-order `Comparable` vs an explicit `rank: Int`: which is more robust to refactoring?"),
  ('practice', "Priority sorting in a task app: where should priority order be defined, client or server?")],
 ['comparable', 'enum', 'order'], 'enums')
E['dictionary-transforms'] = ('e', """`mapValues` and `compactMapValues` transform values while keeping keys, which is `Object.fromEntries(Object.entries(o).map(…))` in one call. `filter` on a dictionary returns a dictionary, where JS `Object.entries().filter()` gives an array.""",
 [('js', "How many intermediate arrays does the JS `Object.entries → map → fromEntries` pipeline create? And the Swift version?"),
  ('contrast', "`mapValues` vs `map` on a Dictionary: why does `map` return an array?"),
  ('edge', "Does `mapValues` keep the dictionary's hashing work (no re-hashing)? Why is it faster?"),
  ('practice', "Cleaning feature flags from remote config is this exact pipeline. Where would you log dropped values?")],
 ['mapvalues', 'dictionary', 'compactmapvalues'], 'dictionaries')
E['custom-string-interpolation'] = ('e', """Extending `String.StringInterpolation` with `appendInterpolation(cents:)` enables `"\\(cents: 1234)"`. It's like a JS tagged template, but per-argument and type-checked, and it's how SwiftUI's `Text` and `os.Logger` interpolation work.""",
 [('js', "JS tagged templates receive all parts at once. How does Swift's per-segment `appendInterpolation` differ?"),
  ('practice', "`Logger` uses custom interpolation for `privacy: .private`. How does that redact values in logs?"),
  ('edge', "Can you add an interpolation that throws? That takes a closure?"),
  ('contrast', "Custom interpolation vs a helper function `money(cents)`: which reads better?")],
 ['interpolation', 'appendinterpolation', 'string'], 'strings')
E['predict-swift-wtf'] = ('e', """Swift's surprises are different from JS's WTFs (`[] + {}`). They come from strictness: grapheme counting, value copies, overflow traps and optional printing. Each is a deliberate trade-off rather than an accident.""",
 [('js', "Pick one Swift WTF and one JS WTF. Which is the result of a deliberate safety trade-off, and which is historical baggage?"),
  ('edge', "Which of these would be a *compile* error in Swift 6 but only a warning in Swift 5?"),
  ('contrast', "Are Swift's surprises easier or harder to debug than JS's? Why?"),
  ('practice', "Which of these have you actually hit in app code?")],
 ['surprising', 'swift', 'behavior'], 'basics')
