E = {}
E['class-copying-predict'] = ('c', """Copying an array of **class** instances copies the references, so both arrays point at the same objects, exactly like JS arrays of objects. An array of **structs** copies the values. The array's own semantics are value semantics, but its elements keep theirs.""",
 [('js', "`const b = [...a]` in JS is a shallow copy. Is Swift's `var b = a` for `[SomeClass]` the same? For `[SomeStruct]`?"),
  ('edge', "Does copy-on-write copy the objects themselves, or only the buffer of references?"),
  ('contrast', "How would you deep-copy an array of class instances? Why is that awkward (`NSCopying`)?"),
  ('practice', "A view model exposing `[Item]` where `Item` is a class: what can a view accidentally mutate?")],
 ['class', 'array', 'reference'], 'value-types')
E['self-instance'] = ('e', """`self` is JS's `this`, except it's never ambiguous: it always means the instance, with no `bind` or arrow-function issues. In a `mutating` method you can even reassign `self` wholesale (`self = Vector(…)`).""",
 [('js', "JS `this` depends on how a function is called. Does Swift `self` ever change meaning inside a method? Inside a closure?"),
  ('edge', "Reassigning `self = …` in a mutating method: what does that do to observers and `didSet` on the owner?"),
  ('contrast', "When must you write `self.` explicitly (initialiser shadowing, escaping closures), and when is it optional?"),
  ('practice', "Swift style guides disagree on explicit `self.`. What's your rule, and why?")],
 ['self', 'instance', 'mutating'], 'structs')
E['protocols-pop-swiftful'] = ('c', """Injecting a protocol-typed dependency into a view model is TS \"program to an interface\", constructor-injecting `ButtonTextProvider`. Swift's nominal protocols make the seams explicit, and mocks become tiny structs.""",
 [('js', "In TS you might just pass an object literal matching the interface. In Swift you need a type that declares conformance. Is that friction worth it?"),
  ('practice', "How would you swap a real data service for a mock in SwiftUI previews using this pattern?"),
  ('contrast', "Protocol injection vs closure injection (`let fetch: () async -> [Item]`): which is lighter for small dependencies?"),
  ('edge', "`any ButtonTextProtocol` vs a generic `ViewModel<T: ButtonTextProtocol>`: what changes for performance and flexibility?")],
 ['protocol', 'dependency', 'inject'], 'protocols')
E['failable-throwing-init'] = ('c', """`init?` returns `nil` on bad input, and `init() throws` explains *why*. JS constructors can only throw, so the \"return nil\" option is Swift-specific and ideal when the caller doesn't care about the reason.""",
 [('js', "JS constructors can't return null. Would you rather have `Email.parse()` return null or throw? How does Swift let the caller choose?"),
  ('contrast', "`init?` vs `init() throws` vs a static `validate() -> Result`: which gives the best form UX?"),
  ('edge', "Can a failable init delegate to a throwing init? With `try?`?"),
  ('practice', "`URL(string:)` is failable, while `JSONDecoder().decode` throws. Why did Apple choose differently?")],
 ['failable', 'throws', 'init'], 'structs')
E['enum-computed-properties'] = ('e', """Enums can have computed properties, static members and methods, like a TS enum merged with a namespace of helpers, but type-safe and exhaustive.""",
 [('js', "TS: `enum Planet {}` plus `namespace Planet { export function … }`. What's cleaner about Swift?"),
  ('edge', "Can an enum have stored properties? What's the workaround (associated values, computed)?"),
  ('contrast', "Enum with computed properties vs a struct with static instances (`Planet.mercury`): which is extensible by others?"),
  ('practice', "App tabs, themes and API environments are often enums with computed properties. Name one in your app.")],
 ['enum', 'computed', 'static'], 'enums')
E['protocol-associated-default'] = ('e', """`associatedtype` makes a protocol generic over a type chosen by the conformer, which TS interfaces do with generic parameters (`Scorer<Item>`). The Swift difference is that the conformer picks it, and callers can constrain it with `where`.""",
 [('js', "TS `interface Scorer<T>` vs Swift `protocol Scorer { associatedtype Item }`: who decides `T` in each?"),
  ('contrast', "Associated types vs generic protocols: why doesn't Swift have `protocol Scorer<Item>` like TS? (Primary associated types in 5.7 do something related.)"),
  ('edge', "Why can't you write `[any Scorer]` and call `score` on each without knowing `Item`?"),
  ('practice', "`Collection.Element` and `Identifiable.ID` are associated types you use daily. Spot them.")],
 ['associated type', 'protocol', 'generic'], 'generics')
E['access-control-module'] = ('e', """`private` in Swift is scoped to the declaration **plus its extensions in the same file**, not the whole class like TS `private`, and not the whole file like `fileprivate`. The file boundary matters in Swift, which JS modules only approximate.""",
 [('js', "A JS module (file) scope is like which Swift access level?"),
  ('contrast', "`private` vs `fileprivate`: when did Swift 4 change `private` to include same-file extensions, and why?"),
  ('edge', "Can a nested type access its outer type's `private` members?"),
  ('practice', "Splitting a big type into extensions across files forces `private` → `internal`. How do you keep encapsulation?")],
 ['private', 'fileprivate', 'extension'], 'access')
E['closure-multiple-params'] = ('e', """Operators are functions in Swift, so you can pass `+` or `max` directly as a `(Int, Int) -> Int` closure: `zipWith(a, b, +)`. In JS you'd write `(x, y) => x + y`, because `+` isn't a value.""",
 [('js', "JS can't pass `+` as a function. What does it mean that Swift operators are just functions?"),
  ('edge', "Why does passing `max` sometimes need a type annotation (overload ambiguity)?"),
  ('contrast', "`zip(a, b).map(+)`: does that work? Why or why not (tuple splat)?"),
  ('practice', "Where would a higher-order `zipWith` show up in UI code: chart series, diffing?")],
 ['closure', 'operator', 'function'], 'closures')
E['generic-swap-and-stack'] = ('c', """`struct Stack<Element>` is TS's `class Stack<T>`, but Swift generics are **reified and specialised**: `Stack<Int>` and `Stack<String>` can compile to specialised code, with no type erasure at runtime (unlike TS, whose generics vanish).""",
 [('js', "TS generics are erased at compile time. Swift's exist at runtime (`Stack<Int>.self`). What can you do with that?"),
  ('java', "Java generics are erased too, so `List<int>` is impossible. Why can Swift put `Int` in a generic without boxing?"),
  ('contrast', "Generic `Stack<Element>` vs `Stack` of `Any`: what do you lose with `Any`?"),
  ('edge', "Generic code across module boundaries may not be specialised. What does `@inlinable` do?")],
 ['generic', 'stack', 'element'], 'generics')
E['generic-constraints-max'] = ('c', """`<T: Hashable & Comparable>` constrains a generic with protocol composition, like TS `<T extends A & B>`. The constraint unlocks operations (`<`, dictionary keys) inside the function body.""",
 [('js', "TS `<T extends Comparable>` is structural. What does a nominal `T: Comparable` require of callers?"),
  ('contrast', "`some Hashable & Comparable` in parameter position vs `<T: …>`: same thing?"),
  ('edge', "Why can't you pass a mixed `[any Hashable]` to this function?"),
  ('practice', "Where do constrained generics appear in SwiftUI (`ForEach<Data, ID: Hashable, Content: View>`)?")],
 ['generic', 'constraint', 'hashable'], 'generics')
E['where-clause-extension'] = ('c', """`extension Collection where Element: BinaryInteger` adds `average` only to collections of integers, a **constrained extension**. TS can't add methods conditionally to `Array<number>` without declaration merging hacks.""",
 [('js', "How would you add `.average()` only to `number[]` in TS? Why is it awkward?"),
  ('edge', "Two constrained extensions both apply (a type that's both integer and floating point, hypothetically): which wins?"),
  ('contrast', "Constrained extension vs free generic function `average<C: Collection>(_:)`: which is more discoverable?"),
  ('practice', "`Array where Element == String` extensions are common. What's the risk of too many?")],
 ['where', 'extension', 'constraint'], 'generics')
E['associated-type-container'] = ('e', """The Swift book's `Container` protocol: an associated `Item`, plus generic functions constrained on it. It's the foundation of how `Collection` works. TS would write `interface Container<Item>`, and Swift infers `Item` from the conformer's methods.""",
 [('js', "In TS, `IntBag implements Container<number>` states the type. How does Swift infer `Item` from `append(_:)`?"),
  ('edge', "What happens if inference is ambiguous? How do you state `typealias Item = Int` explicitly?"),
  ('contrast', "`func allMatch<C1: Container, C2: Container>(…) where C1.Item == C2.Item`: why do you need the `where`?"),
  ('practice', "Would you design your own container protocol in app code, or just use `Collection`?")],
 ['associated type', 'container', 'protocol'], 'generics')
E['opaque-some-return'] = ('c', """`some Drawable` means \"one specific type I'm not telling you\". The compiler knows it, callers don't. It's how SwiftUI's `some View` works. TS has no equivalent: returning an interface type loses the concrete type entirely, which is `any` in Swift terms.""",
 [('js', "TS returning `Drawable` = Swift's `any Drawable`. What does `some Drawable` keep that `any` loses (static type, performance)?"),
  ('contrast', "`some View` vs `AnyView`: why does Apple warn against `AnyView`?"),
  ('edge', "Why can't a `some Drawable` function return a `Triangle` on one branch and a `Square` on another?"),
  ('practice', "Every SwiftUI `body` is `some View`. What is its real type for a `VStack` with two `Text`s?")],
 ['some', 'opaque', 'return type'], 'opaque')
E['type-erasure-any-shape'] = ('e', """Type erasure (`AnyTransformer<In, Out>`) wraps a protocol with associated types in a concrete generic box, like `AnyPublisher` and `AnyView`. It's a Swift-specific pattern, needed because PATs couldn't be used as types before `any P`.""",
 [('js', "TS never needs type erasure. Why does Swift (associated types + no structural typing)?"),
  ('contrast', "Hand-written `AnyTransformer` vs `any Transformer<String, Int>` (primary associated types, Swift 5.7): is manual erasure still needed?"),
  ('edge', "How does the box store the transform: closures capturing the original, or a subclass?"),
  ('practice', "`eraseToAnyPublisher()` in Combine is type erasure. Why do Combine APIs return `AnyPublisher`?")],
 ['type erasure', 'any', 'wrapper'], 'opaque')
E['phantom-types-ids'] = ('e', """A phantom type parameter (`Length<Meters>`) exists only at compile time, so mixing meters and feet is a type error. TS approximates this with branded types (`number & {__brand: 'm'}`). Swift's version is first-class and free at runtime.""",
 [('js', "TS branded types need casts to create. What makes Swift phantom types more ergonomic?"),
  ('contrast', "Phantom types vs Foundation's `Measurement<UnitLength>`: when would you use each?"),
  ('edge', "Can `Length<Meters>` and `Length<Feet>` be added accidentally? What about through `Any`?"),
  ('practice', "`Tagged<User, UUID>` IDs (Point-Free's swift-tagged) prevent passing a `PostID` where a `UserID` is expected. Worth it in your app?")],
 ['phantom', 'type', 'unit'], 'generics')
E['conditional-conformance-pair'] = ('e', """`extension Pair: Equatable where A: Equatable, B: Equatable` makes a generic type conform only when its parameters do. It's how `[Int]` is `Equatable` but `[() -> Void]` isn't. TS gets this structurally, while Swift states it explicitly.""",
 [('js', "In TS, is `Pair<A,B>` \"equatable\"? What does Swift's conditional conformance give you that TS can't express?"),
  ('edge', "Swift 4.1+ synthesises `==` in conditional conformances. What do you still write by hand?"),
  ('contrast', "Conditional conformance vs a separate `EquatablePair` type: which scales?"),
  ('practice', "Why can you compare `[String: [Int]]` with `==` out of the box?")],
 ['conditional conformance', 'where', 'equatable'], 'generics')
E['dynamic-member-lookup'] = ('e', """`@dynamicMemberLookup` lets `config.host` compile to a `subscript(dynamicMember:)` call, like a JS `Proxy` with a `get` trap, but resolved at compile time and optionally typed via key paths.""",
 [('js', "JS `Proxy` intercepts property access at runtime. What's the equivalent Swift mechanism, and what does it cost in type safety?"),
  ('contrast', "String-based dynamic members vs key-path-based (`KeyPath<Wrapped, T>`): which catches typos?"),
  ('edge', "What does Xcode autocomplete show for a dynamic member? Why does that matter for team code?"),
  ('practice', "SwiftUI's `Binding` and `@Observable` wrappers use key-path dynamic member lookup. Find where.")],
 ['dynamic member', 'lookup', 'subscript'], 'advanced')
E['keypath-writable'] = ('e', """`WritableKeyPath<T, V>` is a typed, first-class reference to a settable property: generic setters like `update(&profile, \\.name, to: "Ana")`. JS would use string keys (`obj[key] = v`), with no type checking.""",
 [('js', "`obj[key] = value` in TS needs `keyof` and indexed access types. How does a Swift key path compare?"),
  ('contrast', "`WritableKeyPath` vs `ReferenceWritableKeyPath`: why does a class property need the second?"),
  ('edge', "Can you store `[PartialKeyPath<Profile>]` and iterate over them? What do you lose?"),
  ('practice', "Form editing with a generic `TextField` bound to `\\.name`: how does `Binding` + key paths make this concise?")],
 ['key path', 'writable', 'inout'], 'keypaths')
E['custom-subscript-matrix'] = ('e', """Custom subscripts with two parameters (`m[row: 1, col: 2]`) have no JS equivalent (only `m[1][2]` or Proxy tricks). `precondition` checks bounds and traps like Swift's own array subscript.""",
 [('js', "JS nested arrays `m[r][c]` vs a flat array with a subscript: which is faster, and why?"),
  ('contrast', "`precondition` vs returning optional vs `assert`: which fits a subscript?"),
  ('edge', "Can subscripts be generic? Static? Throw?"),
  ('practice', "Image pixel buffers and game boards are flat arrays with 2-D subscripts. Where else?")],
 ['subscript', 'matrix', 'precondition'], 'advanced')
E['custom-operator-vector'] = ('e', """Operator overloading (`static func +`) lets vectors add naturally. JS can't overload operators at all (`valueOf` hacks aside). Custom operators like `•` need a declared precedence group.""",
 [('js', "JS has no operator overloading. What libraries (gl-matrix) do instead? What's more readable?"),
  ('edge', "Why must you define `*` twice for scalar × vector and vector × scalar?"),
  ('contrast', "Custom `•` operator vs a `dot(_:)` method: which would you allow in a code review?"),
  ('practice', "`CGPoint` and `CGSize` arithmetic extensions are everywhere in drawing code. Useful or dangerous?")],
 ['operator', 'overloading', 'vector'], 'operators')
E['pattern-match-operator'] = ('e', """Overloading `~=` teaches `switch` new pattern types, such as prefix structs or predicate closures. That has no JS equivalent, since JS `switch` only uses `===`.""",
 [('js', "How close can JS `switch(true)` get to custom patterns? What's missing?"),
  ('edge', "Which argument of `~=` is the pattern and which is the value? What happens if you swap them?"),
  ('contrast', "Custom `~=` vs `case let x where x.hasPrefix(…)`: when is the overload worth it?"),
  ('practice', "Matching HTTP status ranges (`case 200..<300`) uses built-in `~=`. What custom pattern would help your networking code?")],
 ['pattern', 'switch', '~='], 'advanced')
E['custom-sequence-fibonacci'] = ('e', """Conforming to `Sequence` with an `IteratorProtocol` is JS's `[Symbol.iterator]()` returning `{ next() }`. Swift's iterator returns `Element?` (`nil` ends it) instead of `{done, value}`, and `lazy` gives you JS generator-style pipelines.""",
 [('js', "JS generators (`function*`) make infinite sequences easy. What's the Swift equivalent (`sequence(first:next:)`, `AnyIterator`)?"),
  ('edge', "Calling `Array(Fibonacci())` on an infinite sequence: what happens?"),
  ('contrast', "`lazy.filter.prefix(while:)` vs eager `filter`: why is lazy mandatory here?"),
  ('practice', "Paging through an API is naturally an `AsyncSequence`. How does that relate to this sync version?")],
 ['sequence', 'iterator', 'lazy'], 'collections-deep')
E['custom-collection-ring'] = ('e', """Conforming to `Collection` (`startIndex`, `endIndex`, `index(after:)`, `subscript`) gives you `map`, `filter`, `first`, `contains` and slicing for free, the power of protocol extensions. JS iterables only get `for…of` and spread.""",
 [('js', "A JS iterable gets `for…of`. What does a Swift `Collection` get for implementing four requirements?"),
  ('edge', "Must `Collection` indices be integers? Why is `String.Index` not an `Int`?"),
  ('contrast', "`Collection` vs `Sequence` vs `RandomAccessCollection`: what does each promise?"),
  ('practice', "A ring buffer for the last N log lines or sensor samples: where would you use one in an app?")],
 ['collection', 'index', 'ring buffer'], 'collections-deep')
E['copy-on-write'] = ('c', """Copy-on-write is how Swift arrays can be value types without copying on every assignment: shared storage plus `isKnownUniquelyReferenced` before mutating. Immutable.js and Immer do structural sharing to get a similar effect in JS.""",
 [('js', "Immer gives you \"mutate a draft, get a new object\". How is Swift CoW similar, and how is it different (no proxies, reference-count based)?"),
  ('edge', "Why must the storage be a `final class` for `isKnownUniquelyReferenced` to work?"),
  ('contrast', "Your own structs don't get CoW automatically. When should a big struct implement it?"),
  ('practice', "Passing a 10k-element array to a function and mutating it inside: how many copies happen?")],
 ['copy on write', 'unique', 'storage'], 'collections-deep')
E['indirect-enum-expression'] = ('e', """`indirect enum Expr` is a recursive discriminated union (an AST), like TS `type Expr = {k:'num',v:number} | {k:'add',l:Expr,r:Expr}`. `indirect` boxes the recursive cases so the enum has a finite size.""",
 [('js', "TS recursive union types need no `indirect`. Why does Swift need it (value types have a fixed size)?"),
  ('contrast', "Indirect enum AST vs class hierarchy AST: which makes adding a new *operation* (pretty-print) easier?"),
  ('edge', "Can you mark only some cases `indirect`? What's the memory difference?"),
  ('practice', "Where do trees appear in apps: JSON, Markdown, view hierarchies, rich-text documents?")],
 ['indirect', 'enum', 'expression'], 'enums-deep')
E['indirect-linked-list'] = ('e', """An immutable linked list as `indirect enum List<T>` is a persistent data structure: prepending shares the tail. That's like functional JS lists (Immutable.js `List`) but built into the type system.""",
 [('js', "Why are linked lists rare in JS app code? Are they any more common in Swift?"),
  ('contrast', "Linked list prepend O(1) vs array insert at 0 O(n): when does that actually matter?"),
  ('edge', "Deallocating a very long indirect list recursively can overflow the stack. Why?"),
  ('practice', "Undo history with structural sharing: would you use this, or snapshots?")],
 ['linked list', 'indirect', 'node'], 'enums-deep')
E['equatable-hashable-custom'] = ('c', """Custom `==` and `hash(into:)` must agree: equal values **must** have equal hashes. JS `Set`/`Map` can't use custom equality at all (identity or primitives only). Swift lets you define identity for your domain, like Gmail-style email rules.""",
 [('js', "JS devs normalise to a string key for Map lookups. When is a custom `Hashable` better than storing a normalised string?"),
  ('java', "Java's `equals`/`hashCode` contract is the same. What's the classic bug when you override only one?"),
  ('edge', "Hash on the normalised form but keep the original for display. What if two different originals are \"equal\"? Which one does the `Set` keep?"),
  ('practice', "Deduplicating contacts by normalised phone number: where does normalisation belong?")],
 ['hashable', 'hash', 'equatable'], 'hashable')
E['predict-self-vs-Self'] = ('e', """`self` is the instance, `Self` is the instance's type (dynamic in classes), and `type(of:)` gets the runtime type. JS has `this` and `this.constructor`, and Swift's `Self` is the typed version of the latter.""",
 [('js', "`this.constructor.name` in JS vs `type(of: self)` in Swift: same idea?"),
  ('edge', "In a class, is `Self` the static or the dynamic type? In a protocol extension?"),
  ('contrast', "`Self.self` vs `type(of: self)` vs `Swift.type(of:)`: when do they differ?"),
  ('practice', "`static func make() -> Self` factories: why are they handy in class hierarchies?")],
 ['self', 'Self', 'type of'], 'classes')
E['retain-cycle-parent-child'] = ('c', """Parent ↔ child strong references leak under ARC, because neither count reaches zero. JS's GC collects cycles, so JS devs never think about this. In Swift, the child's back-reference must be `weak` (or `unowned`).""",
 [('js', "JS mark-and-sweep GC frees cycles. What does ARC gain in exchange for not doing that?"),
  ('java', "Java's GC also handles cycles. Name one Swift benefit of ARC (deterministic deinit, no pauses) over GC."),
  ('contrast', "`weak var parent` vs `unowned let parent`: which crashes if you're wrong about lifetimes?"),
  ('practice', "How do you find this leak in Xcode (Memory Graph debugger)? What does it look like?")],
 ['retain cycle', 'weak', 'parent'], 'memory')
E['closure-retain-cycle'] = ('c', """A class storing a closure that captures `self` strongly is the #1 Swift leak. `[weak self]` breaks the cycle. JS never needs this because GC handles it, but in Swift you must think about capture ownership.""",
 [('js', "`this.onTick = () => this.count++` never leaks in JS. Why does the Swift equivalent leak?"),
  ('contrast', "`[weak self]` + `guard let self` vs `[unowned self]`: when is `unowned` acceptable?"),
  ('edge', "Do non-escaping closures (like `map`) need `[weak self]`? Does `Task { }` retain self? Until when?"),
  ('practice', "Combine `sink { self.x = $0 }` stored in `cancellables` is the same cycle. How do you fix it?")],
 ['weak self', 'closure', 'retain cycle'], 'memory')
E['unowned-customer-card'] = ('e', """`unowned` is a non-owning reference that is **assumed** to always be valid. It's non-optional, and it crashes if the object is gone. JS has no equivalent, since `WeakRef` is always \"maybe gone\".""",
 [('js', "JS `WeakRef` is like Swift `weak`. Why would anyone want the crash-if-wrong `unowned`?"),
  ('edge', "`unowned(unsafe)` exists too. What does it skip?"),
  ('contrast', "When does the Swift book choose `unowned` over `weak` (the lifetimes relationship)?"),
  ('practice', "Would you allow `unowned` in your codebase, or ban it for `weak` everywhere?")],
 ['unowned', 'reference', 'customer'], 'memory')
E['noncopyable-file-handle'] = ('e', """`~Copyable` types have **unique ownership**: they can't be copied, only moved or borrowed, and `consuming` methods end their life. That's Rust-like ownership in Swift, with no JS equivalent. It suits resources like file handles and locks.""",
 [('js', "How do JS devs ensure a file handle is closed exactly once (try/finally, `using`)? What does `~Copyable` enforce at compile time instead?"),
  ('contrast', "`~Copyable` struct with `deinit` vs a class with `deinit`: what's different about sharing?"),
  ('edge', "Can a `~Copyable` value go into an `Array`? (It can't yet.) Why is that hard?"),
  ('practice', "Would you use `~Copyable` in app code today, or is it mostly for systems and library code?")],
 ['noncopyable', 'consuming', 'ownership'], 'ownership')
E['diag-noncopyable-use-after-move'] = ('e', """After `let b = a` for a `~Copyable` value, `a` is **consumed** and using it is a compile error. That's Rust's move semantics. JS can't even express it: every value can be referenced from anywhere.""",
 [('js', "What JS bugs (double-close, use-after-close) would move semantics catch?"),
  ('edge', "Does `borrowing` let you read `a` without consuming it? How does the call site look?"),
  ('contrast', "Swift's `consume` operator on normal copyable values: what's the point (performance)?"),
  ('practice', "Where in Apple's SDK do noncopyable types appear (`Mutex`, `Atomic` in the Synchronization module)?")],
 ['consume', 'noncopyable', 'move'], 'ownership')
E['diag-exclusivity'] = ('e', """The **law of exclusivity**: while an `inout` access is in progress, nothing else may access that variable. JS has no such rule. Swift enforces it at compile time where it can and at runtime otherwise, which prevents a class of aliasing bugs.""",
 [('js', "Can a JS function receive the same object twice and get confused by aliasing? What does Swift prevent?"),
  ('edge', "Runtime exclusivity violations: when does the compiler defer to a runtime check (class properties, globals)?"),
  ('contrast', "Why does `swap(&a[0], &a[1])` fail but `a.swapAt(0, 1)` work?"),
  ('practice', "Have you seen \"Simultaneous accesses to 0x…, but modification requires exclusive access\" in a crash? What caused it?")],
 ['exclusivity', 'inout', 'overlapping'], 'ownership')
E['memory-layout'] = ('e', """`MemoryLayout<T>.size/stride/alignment` shows how structs are laid out, with padding between fields. JS objects hide all of this. It matters for performance-sensitive Swift (large arrays of structs) and C interop.""",
 [('js', "JS objects have hidden classes and unknown layout. Why can Swift tell you exactly?"),
  ('edge', "Why is `MemoryLayout<String>.size` 16 no matter how long the string is?"),
  ('contrast', "`size` vs `stride`: which one determines array memory?"),
  ('practice', "When does field ordering actually matter in an app (millions of elements, Metal buffers)?")],
 ['memory layout', 'size', 'alignment'], 'ownership')
E['async-await-basics'] = ('c', """Swift `async`/`await` looks like JS's, but the concurrency is real: `async let` runs child tasks **in parallel** on multiple threads. `Promise.all` interleaves on one thread; Swift's version can use every core.""",
 [('js', "`await Promise.all(ids.map(fetchUser))` vs `async let` / task groups: what's different about *where* the work runs?"),
  ('contrast', "Sequential `await`s vs `async let` vs `withTaskGroup`: when is each right?"),
  ('edge', "What happens to an `async let` you never await? (Implicitly cancelled and awaited at scope end.)"),
  ('practice', "Loading a profile screen needs user + posts + followers. Sketch it with `async let`.")],
 ['async let', 'await', 'concurrent'], 'concurrency')
E['actor-bank'] = ('c', """An `actor` serialises access to its state, like a JS object that only ever runs on one event loop, but in a multithreaded world. Every outside call is `await`ed, and the compiler forbids unsynchronised access.""",
 [('js', "Why don't JS objects need actors (single-threaded event loop)? What changes once Web Workers share memory (`SharedArrayBuffer`)?"),
  ('edge', "Actor **reentrancy**: during an `await` inside an actor method, other calls can run. How can that break an invariant?"),
  ('java', "Java `synchronized` vs Swift `actor`: what does each protect, and which can deadlock?"),
  ('practice', "Would you make an image cache an actor? What about a view model (`@MainActor` instead)?")],
 ['actor', 'isolation', 'await'], 'concurrency')
E['task-cancellation'] = ('c', """Swift task cancellation is **cooperative**: `cancelAll()` sets a flag and tasks must check `Task.isCancelled` or call a throwing API. JS's `AbortController` works the same way, since you pass a signal and code must check it.""",
 [('js', "`AbortController.signal` vs `Task.isCancelled`: what's the equivalent of `signal.throwIfAborted()`?"),
  ('edge', "Does cancelling a parent task cancel children automatically? Unstructured `Task { }` inside?"),
  ('contrast', "Structured cancellation (task groups) vs manual `Task` handles: which leaks less?"),
  ('practice', "SwiftUI's `.task` cancels on disappear. What must your networking code do for that to actually stop work?")],
 ['cancel', 'task group', 'cancellation'], 'concurrency')
E['async-sequence'] = ('c', """`AsyncStream` + `for await` is JS's async iterators (`for await…of` over an async generator). Swift adds typed continuations for bridging callback APIs, plus buffering policies.""",
 [('js', "`async function*` in JS vs `AsyncStream { continuation in … }`: which is more natural for bridging event emitters?"),
  ('contrast', "`AsyncStream` vs Combine `PassthroughSubject`: which does Apple push in 2026?"),
  ('edge', "What happens if nobody iterates the stream but you keep yielding (buffering policy)?"),
  ('practice', "Bridging `CLLocationManager` delegate callbacks into an `AsyncStream`: sketch it.")],
 ['asyncstream', 'for await', 'yield'], 'concurrency')
E['diag-sendable-race'] = ('c', """Swift 6 **compile-time data-race safety**: sharing a non-`Sendable` mutable class across tasks is a compile error. JS never needs this (single thread), and most languages only find races at runtime (TSan).""",
 [('js', "JS is race-free by being single-threaded. Swift 6 is race-free by construction with multiple threads. What's the price (annotations, `Sendable`)?"),
  ('contrast', "Fixes: make it an `actor`, make it `final class: Sendable` with immutable state, or `@MainActor`. When is each right?"),
  ('edge', "`@unchecked Sendable`: when is it legitimate, and why is it an escape hatch?"),
  ('practice', "Migrating an app to Swift 6 mode: which warnings dominate, and what's the strategy?")],
 ['sendable', 'data race', 'swift 6'], 'concurrency')
E['main-actor-isolation'] = ('c', """`@MainActor` pins code to the main thread, where UI must run, like everything in JS running on the UI thread. `nonisolated` opts a member out so pure helpers can run anywhere.""",
 [('js', "In JS, everything is on the main thread, so heavy work blocks the UI. How does `@MainActor` + `nonisolated` let Swift split UI and work?"),
  ('edge', "Does calling an `async` function from a `@MainActor` method move work off the main thread? (Only if the callee isn't main-actor isolated.)"),
  ('contrast', "`@MainActor` class vs `DispatchQueue.main.async`: why is the annotation safer?"),
  ('practice', "Swift 6.2's default main-actor isolation for app targets: what does it change for view models?")],
 ['mainactor', 'nonisolated', 'main thread'], 'concurrency')
E['property-wrapper-clamped'] = ('c', """Property wrappers (`@Clamped`) package get/set logic for reuse, like decorators on class fields in TS (`@observable`, or validation decorators). `@State`, `@Published` and `@AppStorage` are all property wrappers, and `$name` is the projected value.""",
 [('js', "TS/MobX decorators (`@observable x`) vs Swift property wrappers: which runs at compile time?"),
  ('contrast', "Property wrapper vs `didSet` on each property: when is the wrapper worth it?"),
  ('edge', "What does `$volume` give you, and how does SwiftUI's `$state` produce a `Binding`?"),
  ('practice', "Which property wrappers do you use daily in SwiftUI? Can you explain what each expands to?")],
 ['property wrapper', 'wrappedvalue', 'projected'], 'property-wrappers')
E['result-builder-html'] = ('c', """Result builders turn a block of expressions into a value, which is how SwiftUI's `VStack { Text(); Text() }` works. They're Swift's JSX: a compile-time transform with no runtime parser.""",
 [('js', "JSX compiles to `createElement` calls. What do result builders compile to (`buildBlock`, `buildEither`)?"),
  ('edge', "Why do `if` statements in a builder need `buildEither`/`buildOptional`? What does `for` need?"),
  ('contrast', "SwiftUI's `ViewBuilder` vs JSX: which one supports `switch` natively?"),
  ('practice', "Why did SwiftUI's 10-child limit exist, and how did parameter packs remove it?")],
 ['result builder', 'buildblock', 'dsl'], 'result-builders')
E['codable-snake-case'] = ('c', """`Codable` is typed `JSON.parse`/`stringify`: the compiler generates the parsing from your struct. `keyDecodingStrategy = .convertFromSnakeCase` maps `user_id` to `userId`, which in JS you'd do by hand or with zod plus a transform.""",
 [('js', "`JSON.parse` gives you `any`, and zod validates at runtime. How does `Codable` give you both typing and validation?"),
  ('edge', "Which wins: `convertFromSnakeCase` or explicit `CodingKeys`? What about `e-mail`?"),
  ('contrast', "Missing key → decoding error, unless the property is optional. Is that stricter or looser than zod's defaults?"),
  ('practice', "When an API adds a field, does your app break? When it removes one?")],
 ['codable', 'snake case', 'coding keys'], 'codable')
E['codable-custom-init'] = ('c', """A custom `init(from:)` handles messy JSON, like numbers-or-strings, defaults and nested keys. It's the equivalent of a hand-written zod `preprocess` or `transform`, and it's how real apps survive real APIs.""",
 [('js', "zod `z.union([z.number(), z.string().transform(Number)])` vs a Swift `singleValueContainer` attempt: which is clearer?"),
  ('edge', "`decodeIfPresent` vs `try?` decode: which hides a *type* mismatch you'd want to know about?"),
  ('contrast', "Custom `init(from:)` vs an intermediate DTO struct that you map into your model: which scales?"),
  ('practice', "Where should API-quirk handling live: the model, a DTO layer, or the backend team?")],
 ['decodable', 'init from', 'container'], 'codable')
E['codable-round-trip'] = ('e', """Swift synthesises `Codable` even for enums with associated values, producing JSON like `{"purchase":{"item":"pen","cents":150}}`. A TS discriminated union needs a hand-written serialiser or a library.""",
 [('js', "How would you serialise a TS discriminated union? Does `JSON.stringify` preserve the tag?"),
  ('edge', "What's the synthesised JSON shape for `case logout` (no payload)? Is it stable across Swift versions?"),
  ('contrast', "Synthesised enum coding vs a custom `type` discriminator field: which is friendlier to a backend?"),
  ('practice', "Persisting analytics events offline as JSON: is synthesised coding good enough?")],
 ['codable', 'enum', 'round trip'], 'codable')
E['regex-extract'] = ('e', """Swift regex literals (`/(\\d{4})-(\\d{2})-(\\d{2})/`) are compile-time checked and **typed**: captures become a tuple of `Substring`s. JS regexes give untyped `string[]` matches.""",
 [('js', "JS `match[1]` is `string | undefined`. What does a typed Swift capture tuple give you?"),
  ('edge', "Why validate month/day numerically after matching instead of in the regex?"),
  ('contrast', "Regex literal vs `NSRegularExpression` vs `RegexBuilder`: when would you use each?"),
  ('practice', "Should an app parse dates with regex at all? What does `Date.ISO8601FormatStyle` give you?")],
 ['regex', 'capture', 'match'], 'regex')
E['regex-builder-log'] = ('e', """`RegexBuilder` is a result-builder DSL for regexes (`Capture { … }`, `TryCapture` with transforms), readable where regex literals get cryptic. JS has nothing comparable built in.""",
 [('js', "Have you seen unreadable regexes in JS code reviews? What does a DSL buy, and what does it cost?"),
  ('contrast', "Regex literal vs `RegexBuilder` for the same pattern: which would you want to maintain?"),
  ('edge', "`TryCapture` transforms and can fail the match. How is that different from a `Capture` followed by `Int()` later?"),
  ('practice', "Parsing logs or deep-link paths on-device: good use of regex, or overkill?")],
 ['regexbuilder', 'capture', 'regex'], 'regex')
E['sha256-hash'] = ('e', """`SHA256.hash(data:)` from CryptoKit is Node's `crypto.createHash('sha256')`. Unlike `hashValue`, a cryptographic hash is stable across launches and machines, so use it for checksums and cache keys.""",
 [('js', "Node `crypto` vs Web Crypto (`subtle.digest`, async) vs CryptoKit (sync). Why is CryptoKit's sync API fine here?"),
  ('contrast', "`hashValue` vs SHA-256: list three differences (stability, collision resistance, speed)."),
  ('edge', "Hashing a `String`: which encoding do you hash? What goes wrong if client and server differ?"),
  ('practice', "Never store passwords as plain SHA-256. What should you use instead, and should the client hash at all?")],
 ['sha256', 'cryptokit', 'hash'], 'foundation')
E['uuid-and-identifiable'] = ('e', """`UUID()` is JS's `crypto.randomUUID()`. `UUID(uuidString:)` is a failable parser, and `.uuidString` is uppercase, which is a classic mismatch with lowercase UUIDs from JS backends.""",
 [('js', "`crypto.randomUUID()` gives lowercase. Swift's `uuidString` is uppercase. Where can this break equality checks?"),
  ('contrast', "Client-generated UUIDs vs server IDs: which enables offline creation and optimistic UI?"),
  ('edge', "Is `UUID` `Codable`? What string does it encode to?"),
  ('practice', "`Identifiable` with `let id = UUID()` in a model: why does regenerating it on every decode break SwiftUI animations?")],
 ['uuid', 'identifier', 'random'], 'foundation')
E['file-manager-listing'] = ('e', """`FileManager` is Node's `fs`: create directories, write files, list contents. iOS apps are **sandboxed**, so you work inside your container's Documents, Caches and tmp folders, never arbitrary paths.""",
 [('js', "Node `fs` can touch the whole disk. What can an iOS app see, and where should each kind of file go (Documents vs Caches vs tmp)?"),
  ('edge', "`contentsOfDirectory` order: is it sorted? Why must you sort for stable output?"),
  ('contrast', "`FileManager` + `Data.write` vs SwiftData or Core Data: when is plain files the right persistence?"),
  ('practice', "Which folder gets backed up to iCloud, and which can the system purge under storage pressure?")],
 ['filemanager', 'directory', 'files'], 'foundation')
E['compiler-directives'] = ('e', """`#if os(macOS)`, `#if swift(>=6)` and `#if DEBUG` are compile-time conditions, like build-time `process.env.NODE_ENV` checks that bundlers strip. `#available` is the **runtime** OS-version check.""",
 [('js', "`if (process.env.NODE_ENV === 'production')` is removed by bundlers. How is `#if DEBUG` similar, and different?"),
  ('contrast', "`#if os(iOS)` (compile-time) vs `if #available(iOS 17, *)` (runtime): when do you need each?"),
  ('edge', "Code inside a false `#if` block: is it type-checked? Parsed?"),
  ('practice', "Where do you use `#if DEBUG` in an app: mock data, logging, debug menus?")],
 ['#if', 'compile', 'available'], 'advanced')
E['diag-error-directive'] = ('e', """`#error("…")` fails the build with your message, for missing configuration and similar. JS would fail at runtime or use a build-script check. Swift can enforce it in the compiler.""",
 [('js', "How do JS projects enforce \"API_KEY must be set\" (build-time env check)? Is compile-time better?"),
  ('contrast', "`#error` vs `#warning` vs a runtime `fatalError`: which fits which situation?"),
  ('edge', "Can `#error` appear inside a function body? In an `#else` branch?"),
  ('practice', "Should API keys be compiled into apps at all? Where do secrets belong?")],
 ['#error', 'compile', 'directive'], 'advanced')
E['diag-main-attribute'] = ('e', """A program has exactly one entry point: either top-level code in `main.swift`, or a type marked `@main`. Node's entry is simply the file you run. SwiftUI apps use `@main struct MyApp: App`.""",
 [('js', "Node's entry point is whatever file you run. What decides the entry point in a Swift executable?"),
  ('practice', "What does `@main` on `struct MyApp: App` actually generate?"),
  ('edge', "Can a library target have `@main`? What about a package with multiple executables?"),
  ('contrast', "`main.swift` top-level code vs `@main` with `static func main() async`: which to use for a CLI?")],
 ['@main', 'entry point', 'main.swift'], 'advanced')
E['assert-precondition'] = ('c', """`assert` checks only in debug builds, `precondition` checks in release too, and `fatalError` always crashes. In JS, `console.assert` only logs. Swift's assertions actually stop the program, which is the point.""",
 [('js', "`console.assert` doesn't stop execution. Why are Swift's assertions designed to crash?"),
  ('contrast', "`assert` vs `precondition` vs `throw`: which for programmer errors, and which for bad user input?"),
  ('edge', "What does `-Ounchecked` do to `precondition`? Why is that dangerous?"),
  ('practice', "Where do you put `assertionFailure` in app code so debug builds catch impossible states but users don't crash?")],
 ['precondition', 'assert', 'fatalerror'], 'errors')
E['lru-cache'] = ('c', """An O(1) LRU needs a dictionary plus a doubly linked list. JS's `Map` preserves insertion order, so JS devs cheat with delete-then-set. Swift's `Dictionary` is unordered, so you build the list yourself, with `weak`/`unowned` back-links.""",
 [('js', "The JS `Map` delete-and-reinsert trick gives LRU for free. Why doesn't it work in Swift?"),
  ('contrast', "Hand-rolled LRU vs `NSCache` (auto-evicts under memory pressure): which for images?"),
  ('edge', "Doubly linked nodes create reference cycles. How do you avoid leaking them?"),
  ('practice', "Should an LRU be an actor if multiple image loads hit it concurrently?")],
 ['lru', 'cache', 'evict'], 'caching')
E['memoization'] = ('e', """Memoising with a captured dictionary is the same closure trick as a JS `memoize`. The recursion-friendly signature (`body` receives the memoised function) is the Y-combinator pattern, with generics keeping it typed.""",
 [('js', "lodash `memoize` keys by the first argument's identity or string. What does `Hashable` give Swift here?"),
  ('edge', "Is this memoiser thread-safe? What happens in Swift 6 if two tasks call it?"),
  ('contrast', "Memoised recursion vs bottom-up DP: which is easier to reason about for stack depth?"),
  ('practice', "Caching expensive formatting or layout calculations: where does memoisation help in UI code?")],
 ['memoize', 'cache', 'recursive'], 'caching')
E['dependency-injection'] = ('c', """Injecting a `Clock` protocol instead of reading `Date()` makes time testable, just like injecting a clock in JS tests (or using `jest.useFakeTimers`). Swift does it with protocols or closures, and there's no module mocking to reach for.""",
 [('js', "JS tests can monkey-patch `Date.now` or mock modules. Swift can't. Is that a weakness or a design pressure toward DI?"),
  ('contrast', "Protocol injection vs closure injection vs `swift-dependencies`: which scales in a big app?"),
  ('edge', "Default parameter `clock: Clock = SystemClock()`: convenient, or a hidden global?"),
  ('practice', "Apple's `Clock` protocol (Swift 5.7) and `ContinuousClock`: how would you inject one for `Task.sleep` in tests?")],
 ['dependency injection', 'protocol', 'mock'], 'design')
E['valid-parentheses'] = ('e', """The classic stack problem. In Swift, `[Character]` works as the stack (`append`/`popLast`), and a `[Character: Character]` map pairs brackets. `popLast()` returns an optional where JS `pop()` returns `undefined`.""",
 [('js', "JS `pop()` on an empty array returns `undefined`. Swift `popLast()` returns `nil` while `removeLast()` crashes. Which do you want here?"),
  ('contrast', "Stack + map vs a counter per bracket type: why does the counter fail for `([)]`?"),
  ('edge', "Unicode brackets like `「」`: does your map handle them? Should it?"),
  ('practice', "Where does bracket matching show up in apps: code editors, Markdown parsing?")],
 ['stack', 'brackets', 'parentheses'], 'algorithms')
E['generic-binary-search'] = ('e', """Writing `binarySearch` once on `RandomAccessCollection where Element: Comparable` makes it work on arrays, slices and any random-access type. JS has no protocol to target, so you'd write it for arrays only.""",
 [('js', "A JS `binarySearch(arr, x)` works on arrays. What extra types does the Swift generic cover (`ArraySlice`, `ContiguousArray`, custom)?"),
  ('edge', "Why must you use `Index` and `index(_:offsetBy:)` rather than `Int` arithmetic? When do slices break `Int` assumptions?"),
  ('contrast', "Why `RandomAccessCollection` and not `Collection` for binary search?"),
  ('practice', "Swift's standard library still has no `binarySearch`. What does swift-algorithms offer (`partitioningIndex`)?")],
 ['binary search', 'generic', 'comparable'], 'algorithms')
E['merge-intervals'] = ('e', """Sort by start, then sweep and merge. Identical to JS. Swift's `sorted { $0[0] < $1[0] }` and `last`/`removeLast` make the sweep concise.""",
 [('js', "JS devs write `intervals.sort((a,b) => a[0]-b[0])`. What does Swift's Bool comparator change?"),
  ('edge', "Should `[1,4]` and `[4,5]` merge? How do you express closed vs half-open intervals in Swift types?"),
  ('contrast', "Arrays `[Int]` vs `ClosedRange<Int>` for intervals: which gives `overlaps(_:)` for free?"),
  ('practice', "Calendar busy-time merging is exactly this. Where does time-zone handling come in?")],
 ['intervals', 'merge', 'sort'], 'algorithms')
E['top-k-frequent'] = ('e', """Count with a dictionary, then sort by `(-count, word)` using tuple comparison. The same shape as JS, with a `Hashable` dictionary key and lexicographic tuple ordering standing in for comparator juggling.""",
 [('js', "The JS comparator `b.count - a.count || a.word.localeCompare(b.word)` vs a Swift tuple compare: which is harder to get wrong?"),
  ('contrast', "Full sort O(n log n) vs a heap of size k O(n log k): when does it matter?"),
  ('edge', "Should tie-breaking use `<` on Strings or `localizedStandardCompare`? What's the difference?"),
  ('practice', "\"Trending tags\" in an app: compute on device or server?")],
 ['frequency', 'top k', 'sort'], 'algorithms')
E['number-of-islands'] = ('e', """BFS over a grid, passing the grid `inout` so the helper can sink visited land in place. In JS the grid would be mutated through a shared reference; in Swift the `inout` makes that explicit.""",
 [('js', "Your JS BFS mutates the grid argument freely. Why must Swift mark it `inout` and pass `&grid`?"),
  ('contrast', "BFS with an array-as-queue (`removeFirst` is O(n)) vs an index pointer: which is really O(n)?"),
  ('edge', "Recursive DFS on a 1000×1000 island: what happens to the stack?"),
  ('practice', "Flood fill in a drawing app is this algorithm. Where else?")],
 ['bfs', 'grid', 'islands'], 'algorithms')
E['design-trie'] = ('e', """A trie with `final class Node { var children: [Character: Node] }`. Classes are needed because nodes are shared and mutated through references. `Character` keys handle emoji and accents correctly.""",
 [('js', "A JS trie with `{}` children vs Swift's `[Character: Node]`: what does grapheme-aware keying fix?"),
  ('contrast', "Class nodes vs an indirect enum for a trie: why are classes simpler here?"),
  ('edge', "Memory: a trie of 100k words has many small dictionaries. What would a compact representation look like?"),
  ('practice', "Search-as-you-type suggestions: trie on device, or a server endpoint?")],
 ['trie', 'prefix', 'node'], 'algorithms')
E['longest-unique-substring'] = ('e', """Sliding window + `[Character: Int]` of last positions. In Swift, walk `Array(s)` for integer indices, because `String` indices aren't integers. Emoji then count as single characters for free.""",
 [('js', "Your JS solution with `s[i]` breaks on emoji. Why does converting to `[Character]` fix it in Swift?"),
  ('contrast', "`Array(s)` (O(n) memory) vs walking `String.Index`: which would you pick for a 1 MB string?"),
  ('edge', "Should `\"e\\u{301}\"` and `\"é\"` count as the same character? What does Swift say?"),
  ('practice', "Where do sliding windows appear in app code: rate limiting, recent-activity windows?")],
 ['sliding window', 'substring', 'unique'], 'algorithms')
E['product-except-self'] = ('e', """Prefix and suffix products in two passes, the same as JS. The Swift wrinkle: products overflow `Int` and **trap**, where JS silently loses precision. Test inputs must stay in range, or use `&*` deliberately.""",
 [('js', "In JS a large product silently becomes imprecise. In Swift it crashes. Which failure would you rather see in production?"),
  ('contrast', "Division-based O(n) vs prefix/suffix: why is division banned (zeros)?"),
  ('edge', "What does `multipliedReportingOverflow` return? How would you surface overflow to the caller?"),
  ('practice', "Is overflow realistic in app metrics (likes × shares)? Where would you use `Int64` or `Decimal`?")],
 ['prefix', 'product', 'array'], 'algorithms')
E['max-subarray'] = ('e', """Kadane's algorithm as a single `reduce` over a `(current, best)` tuple, functional and allocation-free. In JS the same `reduce` would allocate an array or object per step, while Swift tuples are free.""",
 [('js', "JS `reduce((acc, x) => [..], [..])` allocates each step. Does the Swift tuple accumulator allocate?"),
  ('contrast', "`reduce` with a tuple vs a `for` loop with two `var`s: which would your team read faster?"),
  ('edge', "All-negative input: what should the initial value be? Why not 0?"),
  ('practice', "Best streak or best trading window in a finance app: same algorithm?")],
 ['kadane', 'subarray', 'reduce'], 'algorithms')
E['coin-change'] = ('e', """Bottom-up DP with `[Int?]` where `nil` means unreachable. That's more honest than JS's `Infinity` sentinel, because the optional forces you to handle the unreachable case explicitly.""",
 [('js', "JS DP often uses `Infinity` as a sentinel. What bug does Swift's `Int?` prevent (`Infinity + 1`)?"),
  ('contrast', "`[Int?]` vs `[Int]` filled with `Int.max`: which risks overflow?"),
  ('edge', "What's the complexity? When does `amount` large enough make memory the issue?"),
  ('practice', "Change-making for a POS app: is greedy ever correct? For which coin systems?")],
 ['dynamic programming', 'coins', 'optional'], 'algorithms')
E['permutations'] = ('e', """Backtracking with a nested recursive function and `inout` state (path, used). Nested functions capture the result array, so JS closures over an outer array work the same way.""",
 [('js', "JS backtracking pushes and pops a shared array. What does Swift's `inout` add?"),
  ('contrast', "Nested function capturing `result` vs passing `inout result`: which is cleaner?"),
  ('edge', "n! grows fast. At what n does this blow the judge's time limit?"),
  ('practice', "swift-algorithms has `permutations()` and `combinations(ofCount:)`. When would you reach for them?")],
 ['permutations', 'backtracking', 'recursive'], 'algorithms')
E['heap-kth-largest'] = ('e', """Swift's standard library has **no heap** (swift-collections has `Heap`), and neither does JS. A generic `Heap<Element>` storing a comparator closure works for min- and max-heaps alike.""",
 [('js', "Neither JS nor the Swift standard library ship a heap. Why might that be?"),
  ('contrast', "Stored comparator closure vs `Element: Comparable` + a min/max flag: which is more flexible?"),
  ('edge', "Min-heap of size k for kth largest: why min, not max?"),
  ('practice', "Priority queues in apps: scheduling downloads, merging timelines. Would you add swift-collections?")],
 ['heap', 'priority queue', 'kth'], 'algorithms')
