E = {}
E['dijkstra'] = ('e', """The same algorithm as in JS, but Swift's standard library has no priority queue (JS has none either). The O(V²) version with a `visited` array is fine for small graphs, and `Int?` distances make \"unreachable\" explicit instead of `Infinity`.""",
 [('js', "JS uses `Infinity` for unreachable distances. What does `[Int?]` force you to handle that `Infinity` hides?"),
  ('contrast', "O(V²) array scan vs a binary heap (swift-collections `Heap`): at what graph size does the heap win?"),
  ('edge', "Why does Dijkstra break with negative edge weights? What would you use instead?"),
  ('practice', "Routing in MapKit is done for you (`MKDirections`). When would an app still run its own shortest path (games, indoor maps)?")],
 ['dijkstra', 'shortest path', 'graph'], 'algorithms')
E['course-schedule'] = ('e', """Kahn's algorithm: in-degree counts + a queue of ready nodes. Identical to JS. Picking the smallest ready course needs a sorted structure; with no heap in the standard library, `min()` over a set is the simple choice.""",
 [('js', "How would you get the \"smallest available\" node efficiently in JS? Same problem in Swift?"),
  ('contrast', "Kahn's (BFS) vs DFS-based topological sort: which detects cycles more naturally?"),
  ('edge', "What should the function return when there's a cycle? Empty array, optional, or throw?"),
  ('practice', "Build systems and SPM resolve dependency order this way. Where else in apps (onboarding steps, migrations)?")],
 ['topological', 'in-degree', 'graph'], 'algorithms')
E['binary-tree-level-order'] = ('e', """Trees as `indirect enum Tree { case empty; case node(Tree, Int, Tree) }` make the null child a real case, like a TS union `Tree = null | {l, v, r}`, but with exhaustive pattern matching on every traversal.""",
 [('js', "TS `type Tree = null | {left: Tree, val: number, right: Tree}` vs Swift's indirect enum: what does pattern matching give you?"),
  ('contrast', "Enum trees (immutable, value) vs class nodes (mutable, shared): which is easier for building from level order?"),
  ('edge', "Deep, skewed trees make recursive traversal overflow the stack. How deep before it crashes?"),
  ('practice', "Where do trees appear in app work: comment threads, file browsers, `OutlineGroup` in SwiftUI?")],
 ['binary tree', 'level order', 'enum'], 'algorithms')
E['roman-numerals'] = ('e', """An ordered array of `(value, symbol)` tuples drives a greedy loop. The JS version is identical with arrays of pairs. Swift tuples with labels (`(value: 900, symbol: \"CM\")`) read better and cost nothing.""",
 [('js', "JS: `[[1000,'M'],…]`. Swift: `[(value: Int, symbol: String)]`. What do labels buy you?"),
  ('contrast', "Why must this be an array, not a dictionary? (Order.)"),
  ('edge', "What's the reverse (Roman → Int) trick with the subtractive pairs?"),
  ('practice', "Foundation can't format Roman numerals, but `NumberFormatter` does spell-out. When would an app need either?")],
 ['roman', 'tuples', 'greedy'], 'algorithms')
E['rotate-matrix'] = ('e', """Transpose then reverse rows, in place via `inout [[Int]]`. The Swift nuance: `matrix[i].reverse()` mutates the nested array in place without copying, thanks to in-place mutation through subscripts.""",
 [('js', "In JS, `matrix[i].reverse()` mutates the inner array object. Does Swift's `matrix[i].reverse()` copy the row first?"),
  ('edge', "`swapAt` vs `(a[i][j], a[j][i]) = (a[j][i], a[i][j])`: which triggers exclusivity errors and which doesn't?"),
  ('contrast', "`[[Int]]` vs a flat `[Int]` with index maths: which is faster for images?"),
  ('practice', "Rotating images in iOS is done with `CGImage`/`UIImage.Orientation`, not arrays. Why?")],
 ['matrix', 'rotate', 'transpose'], 'algorithms')
E['lcs'] = ('e', """Classic 2-D DP, converting both strings to `[Character]` first so you can index by `Int`, which Swift strings don't allow. The DP table is `[[Int]]`, the same as in JS.""",
 [('js', "In JS you'd index `a[i-1]` directly. Why must Swift convert to `[Character]`, and what does it cost?"),
  ('contrast', "Full 2-D table vs two rolling rows: memory O(nm) vs O(min(n,m)). When does it matter?"),
  ('edge', "Should emoji and accented characters compare as graphemes or as scalars in a diff?"),
  ('practice', "LCS powers text diffing. Swift has `CollectionDifference` (`a.difference(from: b)`). Try it on two arrays.")],
 ['subsequence', 'dynamic programming', 'lcs'], 'algorithms')
E['wc-stdio'] = ('e', """A tiny `wc`: count lines, words and characters from stdin. The Swift twist is what \"character\" means. Swift counts graphemes, while Unix `wc -m` counts code points and `wc -c` bytes.""",
 [('js', "Node: `data.length` counts UTF-16 units. Swift `count` counts graphemes. Which matches `wc -m`?"),
  ('edge', "Does `readLine()` preserve the final line if the input has no trailing newline? Does that change the line count vs `wc -l`?"),
  ('contrast', "Reading line by line vs reading all of stdin at once (`FileHandle.standardInput.readDataToEndOfFile()`): memory trade-off?"),
  ('practice', "Word and character counts in a notes app: which count do users expect for emoji?")],
 ['word count', 'lines', 'characters'], 'io')
E['csv-column-sums-stdio'] = ('e', """Split on commas, parse with `Double(_:)`, sum per column. The same as JS's `split(',')` + `parseFloat`, except failures give `nil` instead of `NaN`. Real CSV (quoted commas) needs a real parser, in any language.""",
 [('js', "`parseFloat('3abc')` is 3 in JS. What is `Double(\"3abc\")` in Swift, and which is safer for data import?"),
  ('edge', "What does naive `split(separator: \",\")` do to `\"Smith, John\",42`?"),
  ('contrast', "`split(separator:)` vs `components(separatedBy:)` for trailing empty fields: which keeps them?"),
  ('practice', "Importing a CSV into an app: would you use `TabularData` (Apple's `DataFrame`) instead?")],
 ['csv', 'parse', 'sum'], 'io')
E['sort-names-stdio'] = ('e', """Sort by last name, then first name, case-insensitively, with a tuple key and `lowercased()`. For real names, `localizedStandardCompare` and `PersonNameComponentsFormatter` are the Foundation answer.""",
 [('js', "JS `localeCompare` with `{sensitivity: 'base'}` vs Swift `localizedCaseInsensitiveCompare`: equivalent?"),
  ('edge', "\"van Gogh\", \"O'Brien\", single names, three-part names: how does \"last name\" break down?"),
  ('contrast', "Tuple of lowercased strings vs `KeyPathComparator` with `.localized`: which handles accents correctly?"),
  ('practice', "Contact lists sort by family name in some locales and given name in others. What does `CNContactFormatter` do?")],
 ['sort', 'names', 'case insensitive'], 'io')
E['matrix-transpose-stdio'] = ('e', """Parse rows with `split` + `compactMap(Int.init)`, then transpose with `(0..<cols).map { c in rows.map { $0[c] } }`, the same nested-map idiom as in JS.""",
 [('js', "JS `rows[0].map((_, c) => rows.map(r => r[c]))`. Is the Swift version any different?"),
  ('edge', "What happens with ragged rows? Where should validation happen?"),
  ('contrast', "Nested `map` vs a preallocated `[[Int]](repeating:count:)` with index writes: which is faster?"),
  ('practice', "Charts often need data transposed (series vs categories). Where have you done that?")],
 ['transpose', 'matrix', 'rows'], 'io')
E['gradebook-stdio'] = ('e', """Aggregate per student with `[String: [Int]]`, skip malformed lines with `guard`, then sort keys for output. It's `Map` + `reduce` in JS. The Swift parts are the `guard let` validation and `default:` subscripts.""",
 [('js', "JS: `scores[name] ??= []; scores[name].push(s)`. Swift: `scores[name, default: []].append(s)`. Same thing?"),
  ('edge', "Average of integer scores: integer or floating-point division? What rounding does the output need?"),
  ('contrast', "Store all scores vs running (count, sum): which scales, and which lets you compute a median?"),
  ('practice', "Validation messages for malformed input: silently skip, or report line numbers?")],
 ['grades', 'dictionary', 'average'], 'io')
E['serial-queue-counter'] = ('e', """Before actors, a **serial `DispatchQueue`** guarded shared state: every read and write went through `queue.sync`. JS never needed this (single thread). It's the mutex pattern. `@unchecked Sendable` tells Swift 6 \"trust me, I synchronise\".""",
 [('js', "Node's single thread makes counters trivially safe. What changes the moment you have two threads writing?"),
  ('contrast', "Serial queue vs `NSLock` vs `Mutex` (Synchronization) vs `actor`: which does 2026 Swift recommend?"),
  ('edge', "Calling `queue.sync` from code already running on that queue: what happens?"),
  ('java', "Java `synchronized` blocks vs a serial queue: which one can deadlock more easily?")],
 ['serial queue', 'sync', 'thread safe'], 'concurrency')
E['async-let'] = ('c', """`async let` starts child tasks immediately and you `await` them later, like starting promises before awaiting: `const a = f(); const b = g(); await a; await b`. In Swift they truly run in parallel, and they're structured, so they're cancelled if the scope exits early.""",
 [('js', "`const p = fetchA(); const q = fetchB(); await p; await q` vs `async let`: what does structured concurrency add (automatic cancellation, no leaks)?"),
  ('edge', "If `profile` throws, what happens to `feed` and `notifications` still running?"),
  ('contrast', "`async let` (fixed number) vs `withTaskGroup` (dynamic number): when do you need the group?"),
  ('practice', "A home screen loading three sections: should one failure blank the whole screen? How do you make them independent?")],
 ['async let', 'parallel', 'await'], 'concurrency')
E['checked-continuation'] = ('c', """`withCheckedThrowingContinuation` wraps a callback API into `async`, which is exactly `new Promise((resolve, reject) => legacy(cb))` in JS. \"Checked\" means Swift catches the classic bug of resuming twice, or never.""",
 [('js', "`new Promise(res => api(res))` in JS: what happens if the callback fires twice? What does Swift's checked continuation do?"),
  ('edge', "What if the callback never fires? (A leaked continuation warning, and the task hangs forever.)"),
  ('contrast', "Checked vs unsafe continuations: when is `withUnsafeContinuation` justified?"),
  ('practice', "Which Apple APIs still use completion handlers you'd need to wrap? (Many now have async overloads.)")],
 ['continuation', 'resume', 'callback'], 'concurrency')
E['actor-nonisolated'] = ('e', """Actor members are isolated (so callers must `await`), but `nonisolated` members that only touch immutable `let` state can be called synchronously. That's the escape hatch for things like `description` or IDs.""",
 [('js', "In JS, reading an object's constant field never needs `await`. Why does Swift need `nonisolated` to allow it on actors?"),
  ('edge', "Can a `nonisolated` method read a `var`? Why is `let name` fine?"),
  ('contrast', "`nonisolated let` vs `nonisolated func` vs making the whole type `Sendable`: which is the right tool?"),
  ('practice', "Conforming an actor to `Hashable` or `CustomStringConvertible` needs `nonisolated`. Why?")],
 ['nonisolated', 'actor', 'isolation'], 'concurrency')
E['global-actor'] = ('e', """`@globalActor` creates a named isolation domain like `@MainActor`, but for your own subsystem (analytics, database). Everything annotated with it runs serialised on that actor. JS has no analogue, since there's only one thread there.""",
 [('js', "A dedicated Web Worker for analytics is the closest JS analogue. How is a global actor lighter?"),
  ('contrast', "Custom global actor vs a plain `actor` instance: when do you want the annotation-based isolation?"),
  ('edge', "Calling `@AnalyticsActor` code from `@MainActor` code needs `await`. Why?"),
  ('practice', "Would you create global actors in an app, or is `@MainActor` + plain actors enough?")],
 ['global actor', 'isolation', 'actor'], 'concurrency')
E['sendable-value-snapshot'] = ('c', """Passing **value snapshots** (`struct: Sendable`) between tasks instead of shared objects is how Swift 6 avoids data races. It's like `postMessage` structured-cloning data to a Web Worker, except Swift's copy is free (CoW).""",
 [('js', "`postMessage` clones data between workers. What makes Swift's struct copies cheaper?"),
  ('contrast', "Sending a `struct` snapshot vs sending an `actor` reference: which one needs `await` to read?"),
  ('edge', "A `struct` containing a non-Sendable class: is it `Sendable`? What does the compiler say?"),
  ('practice', "Model types that cross into background tasks: should they all be `Sendable` structs?")],
 ['sendable', 'snapshot', 'struct'], 'concurrency')
E['predict-struct-class-actor'] = ('c', """Three kinds of type: **struct** (copied, like JS primitives), **class** (shared reference, like JS objects) and **actor** (a shared reference with serialised access, which JS doesn't have). Knowing which to choose is a core senior-level Swift skill.""",
 [('js', "JS only has the class-like option. For each of struct, class and actor, what's one bug it prevents or allows?"),
  ('contrast', "Your default choice for models, view models and caches: struct, `@MainActor class`, or actor? Why?"),
  ('edge', "Can an actor be subclassed? Can it conform to protocols with sync requirements?"),
  ('practice', "When would making something an actor be *worse* than a `@MainActor` class (UI state, needless `await`s)?")],
 ['struct', 'class', 'actor'], 'concurrency')
E['weak-self-task'] = ('c', """A `Task { }` retains `self` until it finishes. `[weak self]` plus cancellation in `onDisappear` lets a view model go away mid-download. JS never worries about this, since GC and promises don't keep objects \"alive\" in a leak-visible way.""",
 [('js', "A pending `fetch` in a React component after unmount: warning, but no leak. Why is a Swift `Task` capturing `self` different?"),
  ('edge', "With `[weak self]`, where do you `guard let self`: at the start, or after each `await`?"),
  ('contrast', "`[weak self]` vs storing the task and cancelling it vs SwiftUI's `.task` modifier: which is simplest?"),
  ('practice', "When is a short-lived strong capture in a `Task` perfectly fine?")],
 ['weak self', 'task', 'cancel'], 'memory')
E['mvvm-async-viewmodel'] = ('c', """MVVM in SwiftUI: a `@MainActor` view model owns state and calls an injected async service. It maps onto React's hooks-plus-services pattern (a custom hook calling an API client), with the view model as a testable class.""",
 [('js', "Custom React hook + API client vs SwiftUI view model + service protocol: what's the equivalent of `useEffect` for loading?"),
  ('contrast', "MVVM vs putting logic directly in the view with `@State` + `.task`: when is a view model overkill?"),
  ('edge', "Why `@MainActor` on the view model? What goes wrong if state is mutated from a background task?"),
  ('practice', "How would you unit-test the view model's loading, success and error states with a mock service?")],
 ['mvvm', 'view model', 'async'], 'architecture')
E['async-throwing-stream'] = ('e', """`AsyncThrowingStream` yields values over time and can end with an error, like an async generator that throws, or an RxJS observable with an error channel. `for try await` consumes it.""",
 [('js', "`async function*` that throws midway vs `AsyncThrowingStream`: same consumer experience?"),
  ('contrast', "Progress as a stream vs a `Progress` object vs a callback: which fits SwiftUI best?"),
  ('edge', "Values yielded before `finish(throwing:)`: does the consumer see them all?"),
  ('practice', "Upload progress in an app: where do you get real progress from `URLSession` (delegates, `bytes`)?")],
 ['asyncthrowingstream', 'progress', 'yield'], 'concurrency')
E['task-timeout'] = ('e', """Racing work against a sleep in a throwing task group is Swift's `Promise.race([work, timeout])`. The group cancels the loser, which a JS race doesn't do (the losing promise keeps running).""",
 [('js', "`Promise.race` leaves the loser running. What does `group.cancelAll()` do for the Swift loser?"),
  ('edge', "If `work` ignores cancellation, does the timeout still return on time? Does the group still wait?"),
  ('contrast', "Task-group timeout vs `URLRequest.timeoutInterval`: which to use for network calls?"),
  ('practice', "Where would you put a timeout in an app: network, Bluetooth, user-perceived loading?")],
 ['timeout', 'task group', 'race'], 'concurrency')
E['task-local'] = ('e', """`@TaskLocal` values flow down to child tasks automatically, like Node's `AsyncLocalStorage` for request IDs in logs.""",
 [('js', "Node `AsyncLocalStorage` vs Swift `@TaskLocal`: do both propagate into child tasks and callbacks?"),
  ('edge', "Does a detached task (`Task.detached`) inherit task-locals? An unstructured `Task { }`?"),
  ('contrast', "Task-local vs passing a `context` parameter everywhere: which is more explicit?"),
  ('practice', "Tracing request IDs through logs in an app: is this worth it on the client?")],
 ['tasklocal', 'propagate', 'context'], 'concurrency')
E['actor-request-coalescing'] = ('c', """Actor **reentrancy**: while one call is `await`ing a download, another call can enter the actor. Store the in-flight `Task` in a dictionary so duplicate requests await the same task. It's the JS pattern of caching the *promise*, not the result.""",
 [('js', "The JS trick: `cache[key] ??= fetch(key)` caches the promise. What's the Swift equivalent with `Task`?"),
  ('edge', "Why doesn't \"check cache, then download, then store\" work inside an actor? Walk through the interleaving."),
  ('contrast', "Caching `Task<Image, Error>` vs caching `Image`: what about failures? Should a failed task stay cached?"),
  ('practice', "Image lists requesting the same avatar 20 times: which libraries (Kingfisher, Nuke) do this for you?")],
 ['reentrancy', 'actor', 'in-flight'], 'concurrency')
E['check-cancellation'] = ('e', """`try Task.checkCancellation()` throws `CancellationError` if cancelled, and `Task.yield()` gives other tasks a turn. It's like calling `signal.throwIfAborted()` in a long JS loop and adding `await null` to yield to the event loop.""",
 [('js', "`await new Promise(r => setTimeout(r))` yields in JS. Is `Task.yield()` the same thing?"),
  ('contrast', "`checkCancellation()` (throws) vs checking `Task.isCancelled` (returns partial results): which suits which job?"),
  ('edge', "Does a CPU-bound loop with no `await`s ever notice cancellation?"),
  ('practice', "Image processing or search indexing in the background: where would you put cancellation checks?")],
 ['checkcancellation', 'yield', 'cancel'], 'concurrency')
E['custom-async-sequence'] = ('e', """Conforming to `AsyncSequence` with an `AsyncIterator` whose `next() async` returns values is JS's `[Symbol.asyncIterator]()` protocol. Returning `nil` ends the sequence, where JS returns `{done: true}`.""",
 [('js', "JS: `{ async next() { return {value, done} } }`. Swift: `mutating func next() async -> Int?`. What does the optional replace?"),
  ('contrast', "Custom `AsyncSequence` vs `AsyncStream`: when is writing the type yourself worth it?"),
  ('edge', "Why is `next()` `mutating`? What if two tasks iterate the same iterator?"),
  ('practice', "Paginated API results as an `AsyncSequence` of items: sketch the iterator's state.")],
 ['asyncsequence', 'iterator', 'next'], 'concurrency')
E['duration-components'] = ('e', """`Duration` is a typed time span (seconds + attoseconds) used by clocks and `Task.sleep(for:)`, so there are no more bare `ms` numbers like JS's `setTimeout(fn, 500)`. Units are explicit in the type.""",
 [('js', "`setTimeout(fn, 500)`: is 500 ms or seconds? How does `.milliseconds(500)` make that impossible to confuse?"),
  ('contrast', "`Duration` vs `TimeInterval` (a `Double` of seconds): why did Swift add a new type?"),
  ('edge', "What precision does `Duration` have? Why attoseconds?"),
  ('practice', "`ContinuousClock` vs `SuspendingClock`: which keeps counting while the device sleeps, and which one do you want for a timer UI?")],
 ['duration', 'clock', 'milliseconds'], 'concurrency')
E['parameter-packs'] = ('e', """Parameter packs (`<each T>`) are variadic generics, functions over any number of differently-typed arguments. TS has variadic tuple types (`[...T]`) for the same idea. They're how SwiftUI dropped its 10-view limit.""",
 [('js', "TS `function f<T extends unknown[]>(...args: T)` vs Swift `repeat each T`: what's similar and what isn't?"),
  ('edge', "Can you iterate a pack with a `for` loop? (Pack iteration arrived in Swift 6.0.)"),
  ('contrast', "Parameter packs vs `[Any]`: what type information survives?"),
  ('practice', "Would you use packs in app code, or mainly in library and framework APIs?")],
 ['parameter pack', 'variadic generics', 'each'], 'evolution')
E['noncopyable-generics'] = ('e', """Generics that accept `~Copyable` types can hold unique resources in containers without copying. There's no JS parallel. It's Rust-style ownership reaching generic code.""",
 [('js', "No JS equivalent exists. What problem (unique ownership of resources) is this solving?"),
  ('edge', "Why must a generic opt in with `~Copyable`? What would break if all generics accepted noncopyable types?"),
  ('contrast', "`Optional<T: ~Copyable>`: how does the standard library support noncopyable optionals?"),
  ('practice', "Library authors, not app authors, benefit most. Agree or disagree?")],
 ['noncopyable', 'generics', 'ownership'], 'ownership')
E['diag-consume-operator'] = ('e', """`consume x` ends a variable's lifetime early, even for copyable types, so using `x` afterwards is a compile error. It's a performance and ownership tool with no JS equivalent (JS can only `x = null`).""",
 [('js', "Setting `x = null` in JS helps the GC maybe. What does `consume` guarantee that nulling doesn't?"),
  ('contrast', "`consume` vs letting the optimiser figure out last use: why make it explicit?"),
  ('edge', "Can you `consume` a global or a class property? Why not?"),
  ('practice', "Large buffers passed into a function that takes ownership: where would `consume` avoid a copy?")],
 ['consume', 'lifetime', 'ownership'], 'ownership')
E['primary-associated-types'] = ('e', """`some Collection<Int>` constrains an opaque type's element, like TS `Iterable<number>`. Primary associated types (Swift 5.7) make protocol generics feel like TS generic interfaces.""",
 [('js', "`Iterable<number>` in TS vs `some Collection<Int>` in Swift: what does the Swift version add (opaque identity, performance)?"),
  ('contrast', "`some Collection<Int>` vs `any Collection<Int>` vs `[Int]`: which to use for a function parameter?"),
  ('edge', "Can you declare your own protocol with a primary associated type? What does the syntax look like?"),
  ('practice', "APIs accepting `some Sequence<String>` let callers pass arrays, sets or lazy views. Worth it?")],
 ['primary associated type', 'some', 'collection'], 'opaque')
E['call-as-function'] = ('e', """`callAsFunction` makes a value callable like a function: `polynomial(2)`. JS gets this naturally (functions are objects with properties). Swift gives structs this ability while keeping their stored data typed.""",
 [('js', "A JS function with extra properties (`fn.coefficients = …`) vs a Swift struct with `callAsFunction`: which is type-safe?"),
  ('contrast', "`callAsFunction` vs just storing a closure: when does a callable struct make sense?"),
  ('edge', "`@dynamicCallable` vs `callAsFunction`: which is for dynamic-language interop?"),
  ('practice', "SwiftUI's `DismissAction` is called like `dismiss()`. What mechanism makes that work?")],
 ['callasfunction', 'callable', 'dynamic'], 'advanced')
E['predict-count-where'] = ('e', """Newer standard library APIs like `count(where:)`, `firstRange(of:)` and `split(separator:)` on strings fill gaps JS devs might fill with lodash. Knowing the modern API saves writing `filter().count`.""",
 [('js', "`arr.filter(p).length` allocates. Does `count(where:)` in Swift allocate?"),
  ('contrast', "`filter { }.count` vs `count(where:)` vs `reduce`: which communicates intent best?"),
  ('edge', "Which of these APIs need a newer OS at runtime vs just a newer compiler?"),
  ('practice', "How do you keep up with standard library additions (Swift Evolution, release notes)?")],
 ['count where', 'standard library', 'new api'], 'evolution')
E['diag-existential-equatable'] = ('e', """`==` on two `any Equatable` values doesn't compile. Equatable's `Self` requirement means both sides must be the **same** concrete type, which the existential can't prove. JS `===` compares anything with anything.""",
 [('js', "JS `a === b` works across types (always false). Why can't Swift even ask the question for `any Equatable`?"),
  ('contrast', "Workarounds: open the existential with a generic, or `AnyHashable`. How does `AnyHashable` compare mixed types?"),
  ('edge', "Why can you put mixed types in `[AnyHashable]` but not compare `any Equatable` values directly?"),
  ('practice', "Diffing heterogeneous rows in a list: how does `AnyHashable` in diffable data sources help?")],
 ['equatable', 'existential', 'Self requirement'], 'opaque')
E['diag-actor-isolation'] = ('c', """Reading actor state from synchronous code is a compile error: you must `await`. JS never forces `await` to read a property. Swift does because the actor might be busy on another thread.""",
 [('js', "Reading `obj.value` in JS is always synchronous. What guarantee is Swift giving you by forcing `await`?"),
  ('contrast', "Fixes: make the function `async`, use `nonisolated`, or snapshot the value. When does each apply?"),
  ('edge', "Inside the actor's own methods, do you need `await` to read `value`? Why not?"),
  ('practice', "UI code wants actor data synchronously for rendering. What's the usual pattern (copy into `@MainActor` state)?")],
 ['actor isolation', 'await', 'synchronous'], 'concurrency')
E['diag-captured-var-mutation'] = ('c', """Swift 6 rejects a `Task` mutating a captured `var` that the enclosing function also mutates, a data race caught at compile time. JS closures mutate captured variables freely, because there's no parallelism.""",
 [('js', "The same code in JS is fine. Why? (One thread, run-to-completion.)"),
  ('contrast', "Fixes: an actor, a `Mutex`, or awaiting the task's result instead of sharing state. Which is simplest?"),
  ('edge', "Is capturing a `let` in a `Task` fine? What about a `var` that's never mutated after the capture?"),
  ('practice', "How many Swift 6 migration errors come from exactly this pattern in older code?")],
 ['captured var', 'data race', 'sendable'], 'concurrency')
E['opening-existentials'] = ('e', """Swift 5.7 **implicitly opens** an `any Shape` when you pass it to a generic `<S: Shape>` function, so inside, you know the concrete type. It's the bridge between existentials and generics. TS has no equivalent because it has no existentials.""",
 [('js', "TS never needs to \"open\" a type. What is Swift's existential box hiding that TS doesn't have?"),
  ('contrast', "Opening via a generic function vs downcasting with `as?`: which is type-safe?"),
  ('edge', "When does opening fail (the result type depends on `S`)? What does the compiler do then?"),
  ('practice', "Where have you had an `any P` and needed to call something generic on it?")],
 ['opening', 'existential', 'generic'], 'opaque')
E['keypath-member-lookup'] = ('e', """Key-path `@dynamicMemberLookup` forwards `audited.name` to `subscript(dynamicMember: KeyPath<Value, T>)`, a **typed** proxy. It's like a JS `Proxy`, but typos are compile errors and autocomplete works.""",
 [('js', "JS `Proxy` loses types. How does the key-path version keep full type checking and autocomplete?"),
  ('contrast', "String-based vs key-path-based dynamic member lookup: when would you ever want strings?"),
  ('edge', "Can the subscript be writable (`WritableKeyPath`) so `audited.name = x` records writes?"),
  ('practice', "`Binding<Model>` → `$model.name` uses exactly this. Explain how the projection works.")],
 ['dynamic member lookup', 'key path', 'proxy'], 'keypaths')
E['builtin-macros'] = ('e', """`#fileID`, `#function`, `#line` and `#column` are compile-time expression macros, captured at the **call site** when used as default arguments. JS has no equivalent; you'd parse `new Error().stack`.""",
 [('js', "JS logging libraries parse stack traces to get file and line. Why is `#line` as a default argument better?"),
  ('edge', "Why does `logged(\"x\")` report the *caller's* line, not the line inside `logged`?"),
  ('contrast', "`#file` vs `#fileID` vs `#filePath`: which leaks your machine's directory structure into a release binary?"),
  ('practice', "`Logger` from `os` records this metadata for you. When would you still pass `#function` yourself?")],
 ['fileID', 'function', 'line'], 'evolution')
E['missing-number'] = ('e', """Two classic tricks: the sum formula `n(n+1)/2 − sum`, and XOR of all indices and values. In Swift, the sum can overflow `Int` and trap, which is why XOR (or `&+`) matters more than in JS.""",
 [('js', "In JS the sum formula silently loses precision past 2^53. In Swift it traps. Which failure mode is better?"),
  ('contrast', "Sum formula vs XOR vs `Set` difference: complexity and overflow risk of each?"),
  ('edge', "Why does XOR work? What property makes `a ^ a == 0` useful here?"),
  ('practice', "Finding gaps in sequence numbers (missed messages, dropped packets) is this problem.")],
 ['missing', 'xor', 'sum'], 'interview')
E['string-compression'] = ('e', """Run-length encoding by walking characters and counting runs. In Swift, iterate `Character`s so emoji stay whole, and build with `String` appends, which are amortised O(1) like JS array `join`.""",
 [('js', "JS devs build an array and `join('')` to avoid O(n²) concatenation. Is Swift `String +=` O(n²)?"),
  ('edge', "Should `\"👍👍\"` compress to `\"👍2\"`? Does your loop treat it as one character?"),
  ('contrast', "Iterating `Character`s vs `unicodeScalars` vs `utf8`: which gives correct runs for emoji?"),
  ('practice', "Is RLE used anywhere in app work (image formats, simple protocols)?")],
 ['compression', 'run length', 'characters'], 'interview')
E['max-profit-stock'] = ('e', """One pass tracking the minimum price so far and the best profit, which reads nicely as a `reduce` over a `(minPrice, best)` tuple. JS would use two `let`s or an object accumulator.""",
 [('js', "Two `let` variables vs a tuple `reduce`: which do you find clearer?"),
  ('contrast', "O(n) one pass vs checking all pairs O(n²): how big must n be before O(n²) is noticeable on-device?"),
  ('edge', "Empty or single-price arrays: what should the profit be?"),
  ('practice', "Stocks and crypto apps compute ranges like this for charts. Where else?")],
 ['profit', 'min', 'one pass'], 'interview')
E['majority-element'] = ('e', """Boyer–Moore voting finds a candidate in O(1) space, then a second pass verifies it. Returning `Int?` makes \"no majority\" explicit, instead of JS's `undefined` or `-1`.""",
 [('js', "Returning `-1` for \"none\" in JS clashes with a real `-1` value. How does `Int?` fix that?"),
  ('contrast', "Boyer–Moore vs a dictionary count: O(1) vs O(n) space. Does space matter on a phone?"),
  ('edge', "Why is the verification pass required? Give an input where the candidate isn't a majority."),
  ('practice', "Consensus among sensor readings or votes: where could majority logic appear in an app?")],
 ['majority', 'voting', 'boyer-moore'], 'interview')
E['spiral-matrix'] = ('e', """Shrinking four boundaries (`top`, `bottom`, `left`, `right`) is the same as in JS. Swift traps on any off-by-one index where JS returns `undefined`, so boundary mistakes show up immediately.""",
 [('js', "An off-by-one in JS gives `undefined` in the output. In Swift it crashes. Which is easier to debug?"),
  ('edge', "Single-row and single-column matrices: which loop condition breaks first?"),
  ('contrast', "Boundary shrinking vs a direction vector with a `visited` grid: which is simpler to get right?"),
  ('practice', "Where do spiral or zigzag traversals appear (image processing, game boards)?")],
 ['spiral', 'matrix', 'boundaries'], 'interview')
E['array-intersection-counts'] = ('e', """Count one array into a `[Int: Int]`, then walk the other, decrementing. The JS `Map` version is identical. Swift's `default:` subscript makes the counting a one-liner.""",
 [('js', "`counts.set(x, (counts.get(x) ?? 0) + 1)` vs `counts[x, default: 0] += 1`: which is clearer?"),
  ('contrast', "Dictionary counting vs sorting both arrays + two pointers: memory vs time trade-off?"),
  ('edge', "Which array should you count, the bigger or the smaller? Why?"),
  ('practice', "Shopping cart vs inventory reconciliation is multiset intersection. Where else?")],
 ['intersection', 'counts', 'dictionary'], 'interview')
E['dedupe-sorted-inplace'] = ('e', """A read/write two-pointer pass over an `inout` array, then `removeLast(k)` to truncate. JS mutates arrays in place freely, while Swift requires `inout` and `&` to make that visible.""",
 [('js', "JS `arr.length = k` truncates in place. What's the Swift equivalent, and is it O(1)?"),
  ('contrast', "In-place two pointers vs `Array(Set(nums)).sorted()`: which preserves stability and memory?"),
  ('edge', "What does `removeSubrange(k...)` do to capacity? Does the buffer shrink?"),
  ('practice', "Does in-place mutation ever matter in app code, or only in interviews?")],
 ['duplicates', 'in place', 'two pointers'], 'interview')
E['linked-list-reverse'] = ('e', """Class-based nodes with `var next: ListNode?`: reversing relinks references in place, exactly as in JS. ARC frees nodes as soon as nothing points to them, so there's no GC pause.""",
 [('js', "The JS iterative reverse is identical. What does ARC do to the old nodes as you relink them?"),
  ('edge', "A 1 million-node list: can deallocation recurse and overflow the stack? Why?"),
  ('contrast', "Class nodes (in-place reverse) vs an indirect enum list (build a new reversed list): which is idiomatic Swift?"),
  ('practice', "Linked lists are rare in Swift apps. What do you use instead, and why (cache locality)?")],
 ['linked list', 'reverse', 'next'], 'interview')
E['linked-list-cycle'] = ('e', """Floyd's tortoise and hare, comparing nodes with `===` (identity). A cyclic list is also a **retain cycle** under ARC, so without breaking it the nodes leak, which JS's GC would clean up.""",
 [('js', "JS's GC frees an unreachable cyclic list. What happens under ARC?"),
  ('contrast', "Floyd's O(1) space vs a `Set<ObjectIdentifier>` of visited nodes: which is easier to explain?"),
  ('edge', "Why `===` and not `==` for comparing nodes?"),
  ('practice', "How would you make a cyclic data structure that doesn't leak (weak/unowned back-links)?")],
 ['cycle', 'tortoise', 'identity'], 'interview')
E['validate-bst'] = ('e', """Recursive validation passing optional `min`/`max` bounds: `nil` means \"unbounded\", which is cleaner than JS's `-Infinity`/`Infinity` for integers.""",
 [('js', "JS uses `-Infinity`/`Infinity` as bounds. Why can't Swift do that for `Int`, and why is `Int?` better anyway?"),
  ('contrast', "Bounds recursion vs in-order traversal checking sortedness: which is easier to prove correct?"),
  ('edge', "Duplicate values: allowed on the left, the right, or neither? The problem statement decides."),
  ('practice', "Where do sorted-tree invariants matter in real code (indexes, interval trees)?")],
 ['bst', 'bounds', 'recursive'], 'interview')
E['throttle-events'] = ('c', """Throttle vs debounce are the JS interview classics (lodash). Here they're pure functions over timestamps. In an app you'd use Combine's `.debounce`/`.throttle` or an `AsyncSequence` algorithm (swift-async-algorithms).""",
 [('js', "lodash `debounce` vs Combine `.debounce(for:scheduler:)`: what's the Swift equivalent of `leading`/`trailing` options?"),
  ('contrast', "Throttle vs debounce: which for search-as-you-type, which for scroll handlers?"),
  ('edge', "Is the last event in a burst always delivered by throttle? By debounce?"),
  ('practice', "In SwiftUI, how would you debounce a `TextField` search: `.task(id:)` + `Task.sleep`, or Combine?")],
 ['debounce', 'throttle', 'events'], 'interview')
E['flatten-nested'] = ('e', """Decoding heterogeneous JSON (`[1, [2, 3]]`) into `indirect enum Nested` with a custom `init(from:)` that tries `Int` first, then `[Nested]`. JS's `JSON.parse` + `flat(Infinity)` does it untyped in one line.""",
 [('js', "`arr.flat(Infinity)` is one line in JS. What does the typed Swift version protect you from?"),
  ('contrast', "Try-decode-then-fallback vs a discriminator field: which is more robust to API changes?"),
  ('edge', "What does `singleValueContainer().decode(Int.self)` throw on `2.5`? On `\"2\"`?"),
  ('practice', "APIs returning \"either a string or an array of strings\": how do you model that in `Codable`?")],
 ['flatten', 'nested', 'decode'], 'interview')
E['reverse-string-ways'] = ('e', """`String(s.reversed())` reverses **graphemes**, so emoji and accents survive. JS's `s.split('').reverse().join('')` breaks surrogate pairs. Three agreeing implementations are a mini property test.""",
 [('js', "`'👨‍👩‍👧'.split('').reverse().join('')` in JS produces garbage. What does Swift's `reversed()` produce, and why?"),
  ('contrast', "`reversed()` (a lazy view) vs building a new `String`: when is the lazy view enough?"),
  ('edge', "Reversing `unicodeScalars` vs `Character`s: which breaks flags like 🇬🇧?"),
  ('practice', "Is string reversal ever needed in apps? What about right-to-left text (it's not reversal)?")],
 ['reverse', 'string', 'grapheme'], 'interview')
E['inline-array'] = ('e', """`InlineArray<4, Int>` (Swift 6.2) is a fixed-size array stored inline, with no heap allocation and no CoW. It's like JS typed arrays of a fixed length, but generic and stack-allocated.""",
 [('js', "`new Int32Array(4)` in JS still heap-allocates. What does \"inline\" mean for Swift?"),
  ('contrast', "`InlineArray` vs `Array` vs a tuple `(Int, Int, Int, Int)`: when would you pick each?"),
  ('edge', "Can an `InlineArray` grow? Is it `Collection`? (It isn't, deliberately.) Why?"),
  ('practice', "Where would a fixed-size, allocation-free array matter: audio, graphics, parsing hot loops?")],
 ['inlinearray', 'fixed size', 'stack'], 'evolution')
E['span-safe-views'] = ('e', """`Span<Element>` is a bounds-checked, non-escapable view over contiguous memory, a safe `UnsafeBufferPointer`. It's like JS's `TypedArray.subarray` views, but the compiler proves it never outlives the storage.""",
 [('js', "`subarray` views in JS share memory safely because of the GC. How does Swift prove a `Span` doesn't dangle without a GC?"),
  ('contrast', "`Span` vs `ArraySlice` vs `UnsafeBufferPointer`: safety and cost of each?"),
  ('edge', "Why can't you return a `Span` from a function or store it in a property?"),
  ('practice', "Parsing binary data (images, network packets) without copies: where would `Span` help?")],
 ['span', 'non-escapable', 'memory view'], 'evolution')
E['raw-identifiers'] = ('e', """Swift 6.2 raw identifiers allow almost any text in backticks as a name, like `` func `test adding two items`() ``. JS allows only computed property names (`obj['any text']`).""",
 [('js', "JS test names are strings (`it('adds two items')`). How does Swift Testing use raw identifiers to get the same readability?"),
  ('edge', "Can you name an enum case `` `1st` ``? Why was that previously impossible?"),
  ('contrast', "Raw identifiers vs the `@Test(\"display name\")` argument: which would you use?"),
  ('practice', "Would you allow raw identifiers outside tests? Where could they hurt?")],
 ['raw identifier', 'backticks', 'name'], 'evolution')
E['int128'] = ('e', """`Int128` (Swift 6) gives 128-bit integers with the same trap-on-overflow rules. JS `BigInt` is arbitrary-precision (never overflows) but slower. Swift gives you fixed headroom at native speed.""",
 [('js', "`BigInt` never overflows. `Int128` does, just much later. When would you prefer each?"),
  ('contrast', "`Int128` vs `Decimal` vs a BigInt package: which for money, which for cryptography?"),
  ('edge', "At what n does n! overflow `Int128`? How does `multipliedReportingOverflow` tell you?"),
  ('practice', "Does 128-bit arithmetic come up in app work (UUID maths, large IDs)?")],
 ['int128', 'overflow', 'factorial'], 'evolution')
E['predict-viewbuilder-types'] = ('c', """A SwiftUI `body` compiles to one concrete nested generic type (`TupleView`, `_ConditionalContent`). It's like JSX compiling to `createElement` calls, except Swift keeps the whole tree's **type**, which is how SwiftUI diffs without a virtual DOM.""",
 [('js', "React diffs virtual DOM *values* at runtime. What does SwiftUI get from knowing the view tree's *type* at compile time?"),
  ('edge', "Why do `if/else` branches become `_ConditionalContent<A, B>`? What happens to state when you switch branches?"),
  ('contrast', "`if` in a builder vs `.opacity(show ? 1 : 0)`: which preserves view identity and state?"),
  ('practice', "A view \"resets\" its state when a condition toggles. How does this type structure explain it?")],
 ['viewbuilder', 'tupleview', 'conditional'], 'swiftui-composition')
E['predict-modifier-order'] = ('c', """Each modifier **wraps** the view in `ModifiedContent<Inner, Modifier>`, so `padding().background()` and `background().padding()` are different trees. CSS applies properties to one box; SwiftUI builds nested boxes in order.""",
 [('js', "In CSS, `padding` and `background` are properties of one box. Why does order matter in SwiftUI but not in CSS?"),
  ('contrast', "`.frame().background()` vs `.background().frame()`: sketch both results."),
  ('edge', "Do all modifiers wrap? (Some, like `.font`, flow down the environment.) How do you tell?"),
  ('practice', "When a tap area is too small, which modifier order usually fixes it (`.contentShape`, `.padding` before `.onTapGesture`)?")],
 ['modifier', 'order', 'modifiedcontent'], 'swiftui-composition')
E['predict-anyview-foreach'] = ('c', """`AnyView` erases the type, and SwiftUI loses the structural identity it uses for diffing and animation. `Group` and `ForEach` keep types. It's like losing React `key`s: it works, but updates get more expensive.""",
 [('js', "React without keys still renders but re-mounts more. What does `AnyView` cost SwiftUI in the same way?"),
  ('contrast', "`AnyView` vs `@ViewBuilder` func vs `some View` return: which should you reach for?"),
  ('edge', "Is `ForEach` a view or a view builder? What type does `ForEach(0..<3) { Text(\"\\($0)\") }` have?"),
  ('practice', "Where is `AnyView` genuinely justified (heterogeneous plugin views, type-erased routers)?")],
 ['anyview', 'foreach', 'type erasure'], 'swiftui-composition')
E['diag-state-needed'] = ('c', """A SwiftUI view is a struct, and `body` isn't `mutating`, so `count += 1` can't compile. `@State` moves the storage outside the struct, which is SwiftUI's `useState`. Like React, the view is recreated often and state must live elsewhere.""",
 [('js', "Why can't a React component keep state in a local variable either? How is `@State` like `useState`?"),
  ('contrast', "`@State` vs `@Binding` vs `@Observable` model: who owns the data in each?"),
  ('edge', "Why must `@State` be `private` by convention? What happens if a parent passes an initial value?"),
  ('practice', "Initialising `@State` from a parameter only takes effect once. Why, and what's the fix (`.onChange`, `id`)?")],
 ['state', 'mutating', 'struct'], 'swiftui-state')
E['diag-opaque-mismatch'] = ('c', """`some View` must be **one** concrete type, so returning `Text` in one branch and `Image` in another fails. `@ViewBuilder` wraps branches into `_ConditionalContent`. JSX never has this issue because elements share one runtime type.""",
 [('js', "A React function can return `<Text/>` or `<Image/>` freely. Why can't a Swift `some View` function?"),
  ('contrast', "Fixes: `@ViewBuilder`, `Group { if … }`, or `AnyView`. Which is cheapest?"),
  ('edge', "Why does `body` not need `@ViewBuilder` written explicitly? (The `View` protocol declares it.)"),
  ('practice', "Helper functions returning views: do you mark them `@ViewBuilder` by habit?")],
 ['some view', 'opaque', 'viewbuilder'], 'swiftui-composition')
E['shape-triangle'] = ('e', """A `Shape` is a struct with `path(in: CGRect) -> Path`: pure geometry, resolution-independent. It's like drawing on an SVG `<path>` or Canvas, but declarative and animatable.""",
 [('js', "SVG `<path d=\"M…L…Z\">` vs Swift `Path { move(to:); addLine(to:); closeSubpath() }`: same model?"),
  ('contrast', "`Shape` vs `Canvas` vs an SF Symbol: when would you draw your own?"),
  ('edge', "Why is `path(in:)` given a rect instead of fixed coordinates?"),
  ('practice', "Custom badges, chat bubble tails, chart markers: where have you needed a custom shape?")],
 ['shape', 'path', 'triangle'], 'swiftui-drawing')
E['shape-star'] = ('e', """Alternating outer and inner points with trigonometry. It's the same maths as a Canvas star in JS. `stride(from:to:by:)` over angles and `CGPoint` arithmetic keep it concise.""",
 [('js', "JS Canvas: `Math.cos`/`Math.sin` over angles. Is anything different in Swift besides `CGFloat`?"),
  ('edge', "Why start at −π/2? What changes if you start at 0?"),
  ('contrast', "Computing points each `path(in:)` call vs caching: does SwiftUI call `path(in:)` often?"),
  ('practice', "Rating stars in an app: custom `Shape`, SF Symbol `star.fill`, or an image?")],
 ['star', 'shape', 'trigonometry'], 'swiftui-drawing')
E['shape-progress-ring'] = ('e', """A progress ring is a circle trimmed to a fraction with `trimmedPath(from:to:)`, or `.trim` on a `Shape`. SVG's `stroke-dasharray` trick does the same in the browser.""",
 [('js', "SVG `stroke-dasharray`/`stroke-dashoffset` vs SwiftUI `.trim(from:to:)`: which is simpler?"),
  ('edge', "Where does a circle's path start (3 o'clock)? How do you make progress start at 12 o'clock?"),
  ('contrast', "`Circle().trim()` vs `Gauge` vs `ProgressView(value:)` with a circular style: when to hand-roll?"),
  ('practice', "Activity rings: how would you animate progress changes smoothly?")],
 ['trim', 'progress ring', 'circle'], 'swiftui-drawing')
E['animatable-shape'] = ('e', """SwiftUI animates a shape by setting `animatableData` to interpolated values every frame and re-calling `path(in:)`. It's like a JS `requestAnimationFrame` tween driving an SVG path, but declarative.""",
 [('js', "In JS you'd tween a number with rAF and redraw. What does `animatableData` let SwiftUI do for you?"),
  ('edge', "What if a shape has two animatable properties? (`AnimatablePair`.)"),
  ('contrast', "`animatableData` vs the `@Animatable` macro (iOS 26): what does the macro remove?"),
  ('practice', "Why does a shape snap instead of animating when you forget `animatableData`?")],
 ['animatabledata', 'animation', 'interpolate'], 'swiftui-animation')
E['animatable-pair'] = ('e', """`AnimatablePair<A, B>` bundles two animatable values via `VectorArithmetic` (`+`, `-`, `scale(by:)`). Interpolation is vector maths, the same as interpolating `{x, y}` objects in a JS tween library.""",
 [('js', "GSAP tweens many properties at once. How does SwiftUI's `VectorArithmetic` compose multiple values?"),
  ('edge', "Nesting `AnimatablePair<AnimatablePair<A,B>,C>` for three values: ugly. What's the modern alternative?"),
  ('contrast', "Implementing `VectorArithmetic` yourself vs using `AnimatablePair`: when is custom worth it?"),
  ('practice', "Animating a chart's multiple bars at once: which approach?")],
 ['animatablepair', 'vectorarithmetic', 'interpolate'], 'swiftui-animation')
E['color-hex-resolve'] = ('e', """`Color(hex:)` is a failable extension init that parses `#RRGGBB`. `Color.resolve(in:)` gives the actual components for the current environment (light or dark). CSS parses hex natively; SwiftUI needs you to add it.""",
 [('js', "CSS understands `#ff8800` natively. Why doesn't SwiftUI ship `Color(hex:)`?"),
  ('contrast', "Hex colours in code vs asset catalog colours: which supports dark mode and high contrast automatically?"),
  ('edge', "sRGB vs Display P3: can a hex string express P3 colours?"),
  ('practice', "Server-driven theme colours as hex: how do you handle dark mode?")],
 ['hex', 'color', 'resolve'], 'swiftui-drawing')
E['binding-custom-get-set'] = ('c', """`Binding(get:set:)` is a two-way reference made of two closures, like a React controlled input's `value` + `onChange` pair packaged together. Custom bindings let you transform or validate on the way in.""",
 [('js', "A controlled input needs `value` and `onChange`. How does a `Binding` package both?"),
  ('contrast', "Custom `Binding(get:set:)` vs `@Bindable` on an `@Observable` model: when is each right?"),
  ('edge', "A custom binding capturing a class: does the view update when the class changes? (Only if observed.)"),
  ('practice', "Clamping a slider value, or converting units for a `TextField`: where do custom bindings shine?")],
 ['binding', 'get set', 'two-way'], 'swiftui-state')
E['binding-keypath-projection'] = ('c', """`$profile.name` derives a `Binding<String>` from a `Binding<Profile>` through key-path dynamic member lookup. There's no React equivalent (you'd write `onChange={v => setProfile({...profile, name: v})}`). Swift generates that plumbing.""",
 [('js', "Write the React code for editing `profile.name` in a nested state object. How much does `$profile.name` save?"),
  ('edge', "What's the type of `$profile.address.city`? How deep can projections go?"),
  ('contrast', "`$profile.name` on `@State var profile: Profile` vs `@Bindable var model` with `$model.name`: same mechanism?"),
  ('practice', "Form editing a struct with 10 fields: one `@State` struct with projections vs 10 `@State` vars?")],
 ['binding', 'projection', 'key path'], 'swiftui-state')
E['observable-tracking'] = ('c', """`@Observable` tracks **which properties `body` actually reads** and only re-renders for those, like MobX or Vue reactivity, and finer-grained than React's `useState`, which re-renders the component on any update.""",
 [('js', "MobX/Vue track property access during render. How does `@Observable` do the same (the macro plus `withObservationTracking`)?"),
  ('contrast', "`@Observable` vs `ObservableObject` + `@Published`: which invalidates views that didn't read the changed property?"),
  ('edge', "What does `@ObservationIgnored` do, and when should analytics or caches be ignored?"),
  ('practice', "Why can switching from `ObservableObject` to `@Observable` improve performance in large screens?")],
 ['observable', 'tracking', 'observation'], 'swiftui-state')
