E = {}
E['list-offsets'] = ('c', """SwiftUI's `List` hands you an `IndexSet` for deletes and `(IndexSet, Int)` for moves, and `Array.remove(atOffsets:)` / `move(fromOffsets:toOffset:)` apply them. In React you'd splice or filter by index yourself. Here the framework standardises the edit protocol.""",
 [('js', "React drag-reorder libraries give you `(from, to)` indices. Why does SwiftUI use an `IndexSet` (multiple selection)?"),
  ('edge', "`move(fromOffsets:toOffset:)`: is `toOffset` the index *before* or *after* removal? Try moving item 0 to offset 2."),
  ('contrast', "Deleting by offsets vs deleting by ID: which is safe if the list is filtered or sorted in the UI?"),
  ('practice', "With SwiftData `@Query`, how do you delete from `onDelete`? Why do offsets need mapping to model objects?")],
 ['ondelete', 'onmove', 'indexset'], 'swiftui-lists')
E['searchable-scopes'] = ('c', """`.searchable(text:)` plus search scopes filter a list by text and category. It's the React pattern of controlled search input plus derived filtered array, with SwiftUI supplying the search bar UI and scope picker.""",
 [('js', "React: `const visible = useMemo(() => items.filter(...), [query])`. Where should the filtering live in SwiftUI: `body`, a computed property, or the model?"),
  ('contrast', "Filtering in memory vs a SwiftData `#Predicate` query: at what size do you move filtering into the store?"),
  ('edge', "Case- and diacritic-insensitive search: `localizedStandardContains` vs `lowercased().contains`. Try \"José\"."),
  ('practice', "Debouncing search input: needed for local filtering? For network search?")],
 ['searchable', 'scope', 'filter'], 'swiftui-lists')
E['sectioned-list'] = ('e', """Grouping into sections is `Dictionary(grouping:)` plus sorted keys, then `ForEach` over sections. The same data prep as a React `SectionList`, where the view just renders pre-shaped data.""",
 [('js', "React Native's `SectionList` wants `[{title, data}]`. What shape does a SwiftUI `List` with `Section`s want?"),
  ('edge', "Sorting \"Émile\" and \"Zoë\" into letter sections: which collation does the user's locale expect?"),
  ('contrast', "Precomputing sections in the model vs computing them in `body`: when does recomputation become visible?"),
  ('practice', "Contacts-style index bars (A–Z on the side): what API supports that (`.listSectionIndexVisibility`)?")],
 ['section', 'grouping', 'list'], 'swiftui-lists')
E['navigation-path'] = ('c', """`NavigationStack(path:)` with a `NavigationPath` of `Hashable` routes is data-driven navigation, like React Router's history stack but as state you own. Push = append, pop = removeLast, and `Codable` routes make restoration possible.""",
 [('js', "React Router keeps history in the URL. SwiftUI keeps it in a path you own. What's easier: deep links, restoration, or testing?"),
  ('contrast', "`NavigationPath` (type-erased) vs `[Route]` (typed array): when do you need the erased version?"),
  ('edge', "Restoring a saved path after an app update removed a route case: what happens when decoding fails?"),
  ('practice', "Popping to root after checkout: what's the one-line change to the path?")],
 ['navigationstack', 'path', 'route'], 'swiftui-navigation')
E['deep-link-router'] = ('c', """Parsing a URL into a route stack is the router's job, like matching paths in React Router, except iOS delivers links via `.onOpenURL` and you convert them into `NavigationPath` state.""",
 [('js', "React Router matches `/profile/:id` declaratively. In SwiftUI you parse `URLComponents` yourself. What do you gain (type-safe routes)?"),
  ('edge', "Invalid IDs, unknown paths, extra query items: what should the app do (ignore, error screen, home)?"),
  ('contrast', "Custom scheme (`myapp://`) vs universal links (`https://`): which is safer, and why?"),
  ('practice', "A deep link arrives while a modal sheet is open. Who dismisses the sheet before navigating?")],
 ['deep link', 'onopenurl', 'router'], 'swiftui-navigation')
E['preference-key-reduce'] = ('e', """`PreferenceKey` sends values **up** the view tree (children → ancestor), combined by `reduce`. React has no direct equivalent; you'd lift state with callbacks or context. It's the upward twin of `Environment`.""",
 [('js', "In React, a child reporting its size up needs a callback prop or context. How does `PreferenceKey` avoid plumbing?"),
  ('edge', "Why must `reduce` handle many children? What's `defaultValue` used for?"),
  ('contrast', "`PreferenceKey` vs `onGeometryChange` (iOS 18) for reading sizes: which is simpler now?"),
  ('practice', "Syncing a header's height to a scroll offset, or collecting child anchors for overlays: where have you needed this?")],
 ['preferencekey', 'reduce', 'bubble up'], 'swiftui-composition')
E['environment-key'] = ('c', """Custom `EnvironmentValues` (now one line with `@Entry`) pass values **down** the tree implicitly. It's React Context: `.environment(\\.accentName, "red")` is the Provider and `@Environment(\\.accentName)` is `useContext`.""",
 [('js', "React Context re-renders all consumers on change. Does SwiftUI's environment invalidate every child that reads the key?"),
  ('contrast', "Environment value vs passing a parameter vs an `@Observable` object in the environment: which for theme, which for services?"),
  ('edge', "What does `@Entry` generate compared with the old `EnvironmentKey` + extension boilerplate?"),
  ('practice', "Injecting a mock service via the environment for previews: sketch it.")],
 ['environment', 'entry', 'context'], 'swiftui-state')
E['flow-layout-rows'] = ('e', """A custom `Layout` implements flow wrapping: measure children and place them left to right, breaking lines when the width runs out. CSS gives you `flex-wrap: wrap` for free; SwiftUI makes you write the algorithm, but only once.""",
 [('js', "CSS `flex-wrap: wrap` is one line. Why doesn't SwiftUI ship a flow layout, and what does writing `Layout` teach you?"),
  ('edge', "A single tag wider than the container: clip it, shrink it, or let it overflow?"),
  ('contrast', "`Layout` protocol vs `GeometryReader` hacks vs `ViewThatFits`: which is the right tool for wrapping?"),
  ('practice', "Tag chips, filter pills, hashtag lists: where does your app need wrapping?")],
 ['flow layout', 'wrap', 'layout'], 'swiftui-layout')
E['adaptive-grid-columns'] = ('e', """`GridItem(.adaptive(minimum:))` fits as many columns as possible, the same as CSS Grid `repeat(auto-fill, minmax(m, 1fr))`. The column-count maths is identical.""",
 [('js', "CSS `grid-template-columns: repeat(auto-fill, minmax(120px, 1fr))` vs `GridItem(.adaptive(minimum: 120))`: are the results the same?"),
  ('contrast', "`.adaptive` vs `.flexible` vs `.fixed`: which for a photo grid, which for a calendar?"),
  ('edge', "What happens when the container is narrower than `minimum`?"),
  ('practice', "`LazyVGrid` vs `Grid`: which is lazy, and which aligns cells across rows?")],
 ['lazyvgrid', 'adaptive', 'columns'], 'swiftui-layout')
E['unit-curve'] = ('e', """`UnitCurve` exposes the timing functions behind SwiftUI animations (`easeIn`, `easeOut`, custom bezier). They're CSS `cubic-bezier()` timing functions, sampled as values you can inspect.""",
 [('js', "CSS `ease-in-out` is `cubic-bezier(0.42, 0, 0.58, 1)`. Is SwiftUI's `easeInOut` the same curve?"),
  ('contrast', "Timing curves vs spring animations: why does Apple default to springs (`.smooth`, `.snappy`)?"),
  ('edge', "Can a curve's value go below 0 or above 1 (overshoot)? What would that look like?"),
  ('practice', "When would you pick a custom curve over a spring in product UI?")],
 ['animation curve', 'ease', 'bezier'], 'swiftui-animation')
E['form-validation-viewmodel'] = ('c', """An `@Observable` model with computed validation properties drives a `Form`, like React Hook Form or Formik with derived `errors` and `isValid`. It's plain Swift properties rather than a library.""",
 [('js', "Formik/React Hook Form track touched and errors. What do you need to add to a Swift model to show errors only after the user edits a field?"),
  ('contrast', "Computed `isValid` vs validating on submit vs validating each keystroke: which gives the best UX?"),
  ('edge', "Email validation by regex vs `contains(\"@\")` vs letting the server decide: how strict should a client be?"),
  ('practice', "Sharing validation rules with the backend: duplicate them, or fetch rules from the server?")],
 ['form', 'validation', 'observable'], 'swiftui-controls')
E['focus-field-order'] = ('e', """`@FocusState` with an enum drives which field has keyboard focus, and `.onSubmit` moves to the next. It's `ref.focus()` in React, but declarative: you set state, and SwiftUI moves focus.""",
 [('js', "React: `nextInputRef.current.focus()`. SwiftUI: `focused = .email`. What does declarative focus make easier (tests, restoration)?"),
  ('edge', "What does setting focus to `nil` do? How do you dismiss the keyboard?"),
  ('contrast', "`@FocusState var focused: Field?` vs one `Bool` per field: why does the enum scale better?"),
  ('practice', "Which `submitLabel` (`.next`, `.done`, `.go`) would you use for each field in a sign-up form?")],
 ['focusstate', 'focus', 'onsubmit'], 'swiftui-controls')
E['predict-text-concatenation'] = ('e', """Some modifiers return `Text` itself (`bold()`, `foregroundStyle` on Text), so you can concatenate styled pieces with `+`. Like spans inside a `<p>`, but checked by the type system.""",
 [('js', "`<p>Hello <b>world</b></p>` in JSX. What's the SwiftUI equivalent, and why does it need `Text`-returning modifiers?"),
  ('edge', "Why does `Text(\"a\").padding() + Text(\"b\")` fail to compile?"),
  ('contrast', "`Text + Text` vs `AttributedString` vs Markdown in `Text`: which is best for localised styled strings?"),
  ('practice', "Text concatenation breaks localisation word order. What should you do for translated UI?")],
 ['text', 'concatenation', 'modifier'], 'swiftui-composition')
E['predict-property-wrapper-types'] = ('c', """`count` is the `wrappedValue` and `$count` is the `projectedValue`. For `@State` that's an `Int` and a `Binding<Int>`. React has `const [count, setCount]`, and Swift folds the pair into one declaration with a `$` prefix.""",
 [('js', "`const [count, setCount] = useState(0)` vs `@State var count = 0`: what's `$count` in React terms?"),
  ('edge', "What's the type of `_count` (the underscore)? When would you touch it (`init`)?"),
  ('contrast', "`@State`'s projected value is a `Binding`. What's `@Bindable`'s? What about `@Environment`?"),
  ('practice', "Passing `$count` to a child `Toggle`: what does the child receive, and who owns the data?")],
 ['projected value', 'binding', 'state'], 'swiftui-state')
E['dynamic-type-sizes'] = ('c', """`DynamicTypeSize` is the user's text-size setting (`xSmall` … `accessibility5`). It's `Comparable`, so layouts can switch at a threshold. It's like responding to browser zoom or rem scaling, but it's a first-class OS setting users actually change.""",
 [('js', "The web scales with `rem` and browser zoom. What does iOS scale, and why must layouts reflow (not just scale)?"),
  ('edge', "At `accessibility3`, a horizontal row no longer fits. How do you switch to a vertical stack?"),
  ('contrast', "Fixed font sizes vs `.font(.body)` vs `@ScaledMetric`: which respect Dynamic Type?"),
  ('practice', "How do you preview all sizes at once in Xcode (Variants, Dynamic Type preview)?")],
 ['dynamic type', 'accessibility', 'text size'], 'swiftui-accessibility')
E['swipe-card-decision'] = ('e', """Deciding a swipe from `translation` and `predictedEndTranslation` is the Tinder-card logic. On the web you'd compute velocity from pointer events yourself; SwiftUI's `DragGesture` predicts the end for you.""",
 [('js', "With pointer events you'd track timestamps to get velocity. What does `predictedEndTranslation` give you?"),
  ('edge', "A slow drag to 60% of the threshold vs a fast flick to 20%: which should count as a swipe?"),
  ('contrast', "Deciding in `.onEnded` vs updating live in `.onChanged`: which state belongs where (`@GestureState`)?"),
  ('practice', "Accessibility: how does a VoiceOver user \"swipe\" a card? What actions should you add?")],
 ['drag gesture', 'swipe', 'translation'], 'swiftui-gestures')
E['magnification-clamp'] = ('e', """Pinch-zoom keeps a committed scale plus a live gesture scale, clamped to limits. It's the same pattern as web pinch-zoom with pointer events, minus the maths of tracking two touch points.""",
 [('js', "On the web you compute pinch scale from two pointers' distance. What does `MagnifyGesture` hide?"),
  ('edge', "Why clamp the *product* `lastScale * magnification`, not each separately?"),
  ('contrast', "`@GestureState` (auto-resets) vs `@State` for the live scale: which is less error-prone?"),
  ('practice', "Double-tap to reset zoom: how do you combine it with the pinch gesture?")],
 ['magnify', 'zoom', 'clamp'], 'swiftui-gestures')
E['rotation-snap'] = ('e', """Snapping rotation to the nearest 90° and normalising into 0..<360 is plain maths with `Angle`. Working in a typed `Angle` (degrees and radians) avoids the JS unit-confusion bug (`Math.sin` wants radians).""",
 [('js', "`Math.sin(90)` in JS is a radians bug. How does SwiftUI's `Angle` type prevent it?"),
  ('edge', "Normalising −30°: does Swift's `%` give 330 or −30? What's the fix (`truncatingRemainder` + adjust)?"),
  ('contrast', "Snapping on gesture end vs continuous snapping during the gesture: which feels better?"),
  ('practice', "Photo editors snap rotation. Where else would snapping help (sliders, positions)?")],
 ['rotation', 'snap', 'angle'], 'swiftui-gestures')
E['long-press-progress'] = ('e', """Hold-to-confirm maps elapsed hold time to progress, and completes at the threshold. The web does this with `setInterval` during `pointerdown`; SwiftUI's `LongPressGesture(minimumDuration:)` plus `onPressingChanged` manage it.""",
 [('js', "A JS hold-to-confirm button needs timers and cleanup. What does the SwiftUI gesture handle for you?"),
  ('edge', "Finger moves while holding: should that cancel? What's `maximumDistance`?"),
  ('contrast', "Hold-to-confirm vs a confirmation dialog: which is more accessible?"),
  ('practice', "Destructive actions (delete account): which confirmation pattern do Apple's HIG recommend?")],
 ['long press', 'progress', 'hold'], 'swiftui-gestures')
E['scroll-parallax'] = ('e', """Parallax and fade driven by scroll offset, as with `visualEffect` or `scrollTransition`. The web does this with scroll listeners or scroll-driven CSS animations, and SwiftUI gives you the geometry per frame declaratively.""",
 [('js', "CSS scroll-driven animations (`animation-timeline: scroll()`) vs SwiftUI `.scrollTransition`: same idea?"),
  ('edge', "Overscroll (pulling down past the top): what should a stretchy header do?"),
  ('contrast', "`visualEffect` vs `GeometryReader` + `onChange`: which avoids re-running `body`?"),
  ('practice', "Reduce Motion is on. What should parallax do (`accessibilityReduceMotion`)?")],
 ['parallax', 'scroll', 'visualeffect'], 'swiftui-layout')
E['paging-target'] = ('e', """Choosing the target page from release offset and velocity is what a paging scroll behaviour computes. CSS `scroll-snap` decides it for you on the web, while a custom `ScrollTargetBehavior` lets you write the rule.""",
 [('js', "CSS `scroll-snap-type: x mandatory` decides pages automatically. When would you need custom paging logic?"),
  ('edge', "A fast flick from page 0: can it skip to page 3, or at most one page?"),
  ('contrast', "`.scrollTargetBehavior(.paging)` vs `.viewAligned`: what's the difference?"),
  ('practice', "Onboarding carousels vs photo galleries: which paging rules suit each?")],
 ['paging', 'velocity', 'scroll'], 'swiftui-lists')
E['view-that-fits'] = ('e', """`ViewThatFits` tries children in order and shows the first that fits, a declarative media query per component. Container queries in CSS are the closest web analogue.""",
 [('js', "CSS container queries vs `ViewThatFits`: which one picks between entirely different layouts?"),
  ('edge', "If nothing fits, which child is shown? (The last one.)"),
  ('contrast', "`ViewThatFits` vs size classes vs `Layout`: which reacts to the *available* width?"),
  ('practice', "A button label with a long German translation: how would `ViewThatFits` save the layout?")],
 ['viewthatfits', 'fit', 'adaptive'], 'swiftui-layout')
E['sheet-item-state'] = ('c', """Driving sheets and alerts with one optional `Identifiable` item (`.sheet(item:)`) instead of many Booleans is the \"make impossible states impossible\" rule, the same as modelling a React modal with `selectedItem | null` rather than `isOpen` + `item`.""",
 [('js', "React: `const [editing, setEditing] = useState<Item | null>(null)`. Same idea as `.sheet(item:)`?"),
  ('edge', "Presenting a second sheet while one is open: what happens? How does one enum `ActiveSheet?` fix it?"),
  ('contrast', "`.sheet(isPresented:)` + separate item vs `.sheet(item:)`: which can show a sheet with a nil item?"),
  ('practice', "Alerts for errors: `alert(isPresented:error:)` with a `LocalizedError?`. Sketch it.")],
 ['sheet', 'item', 'optional'], 'swiftui-navigation')
E['tab-badges'] = ('e', """A `TabView` with `selection` bound to an enum, plus `.badge(count)`, is like a React tab bar with an active-tab state and notification counts, but native tab bars handle accessibility and overflow for you.""",
 [('js', "A web tab bar is a custom component. What do you get free with a native `TabView` (accessibility, iPad sidebar adaptation)?"),
  ('edge', "Badge value 0: does it show? What about 1,000 (\"999+\")?"),
  ('contrast', "Selection as an enum vs `Int` tags: which survives reordering tabs?"),
  ('practice', "Tapping the current tab should scroll to top and pop to root. How would you detect a re-tap?")],
 ['tabview', 'badge', 'selection'], 'swiftui-navigation')
E['countdown-viewmodel'] = ('e', """A timer-driven countdown in a view model: ticks come in from `Timer.publish` or `TimelineView`. React uses `setInterval` inside `useEffect` with cleanup, and SwiftUI's `.onReceive` ties the subscription to the view.""",
 [('js', "React `useEffect(() => { const id = setInterval(...); return () => clearInterval(id) })`. What's SwiftUI's cleanup story?"),
  ('edge', "The app goes to the background for 30 s. Does a `Timer` keep ticking? How do you stay accurate (store an end date)?"),
  ('contrast', "Counting ticks vs computing `endDate - now` each tick: which drifts?"),
  ('practice', "`TimelineView(.periodic(from:by:))` vs `Timer.publish`: which is better for a countdown label?")],
 ['timer', 'countdown', 'onreceive'], 'swiftui-state')
E['slider-stepper-snap'] = ('e', """`Slider(value:in:step:)` snaps to steps measured from the lower bound, like `<input type=range min step>`, where values snap to `min + k·step`, not to multiples of the step.""",
 [('js', "HTML range `min=3 step=5` snaps to 3, 8, 13… Is SwiftUI the same?"),
  ('edge', "Floating-point steps like 0.1: why can the value show 0.30000000000000004? How do you display it?"),
  ('contrast', "`Slider` vs `Stepper` vs a `TextField` with a formatter: which for precise values?"),
  ('practice', "Accessibility: how does VoiceOver adjust a slider? Why do step values matter?")],
 ['slider', 'stepper', 'step'], 'swiftui-controls')
E['observableobject-vs-observable'] = ('c', """`ObservableObject` + `@Published` invalidates **every** observing view when any published property changes, while `@Observable` tracks only the properties each view reads. The difference is Redux's `connect` without selectors vs MobX's fine-grained tracking.""",
 [('js', "Redux without selectors re-renders on any state change; MobX tracks reads. Which one is `ObservableObject`, and which `@Observable`?"),
  ('edge', "With `@Observable`, does reading a property inside a closure (a button action) subscribe the view?"),
  ('contrast', "`@StateObject`/`@ObservedObject` vs `@State` holding an `@Observable`: which ownership rules changed?"),
  ('practice', "Migrating a big app to `@Observable`: what's the minimum OS version, and what breaks in tests?")],
 ['observableobject', 'observable', 'published'], 'swiftui-state')
E['appstorage-onboarding'] = ('e', """`@AppStorage` is a view-aware `UserDefaults` value that re-renders on change, like a `useLocalStorage` hook in React, but synced across every view reading the same key.""",
 [('js', "A `useLocalStorage` hook in React doesn't sync between components unless you add events. Does `@AppStorage`?"),
  ('edge', "Which types can `@AppStorage` store directly? How do you store a `Codable` struct (`RawRepresentable`)?"),
  ('contrast', "`@AppStorage` vs `@SceneStorage` vs SwiftData: what belongs in each?"),
  ('practice', "Never store tokens in `UserDefaults`. Where do they go instead (Keychain)?")],
 ['appstorage', 'userdefaults', 'onboarding'], 'swiftui-state')
E['environment-shared-model'] = ('c', """Sharing one `@Observable` instance through `.environment(model)` and reading it with `@Environment(Model.self)` is React Context holding a store. Because it's a reference type, every reader sees the same object.""",
 [('js', "React Context + a store object vs SwiftUI environment + `@Observable`: which re-renders less, and why?"),
  ('edge', "Reading `@Environment(Model.self)` when no ancestor provided it: what happens at runtime?"),
  ('contrast', "Environment injection vs passing the model through initialisers: which is more explicit for a reader?"),
  ('practice', "App-wide session or cart models: environment, singleton, or dependency container?")],
 ['environment', 'observable', 'shared'], 'swiftui-state')
E['list-diffing-identity'] = ('c', """SwiftUI diffs lists by **identity** (`id`), the same as React's `key`. With stable IDs a row is updated in place (keeping its state and animating), and with unstable IDs it's removed and re-inserted.""",
 [('js', "Using array index as a React key causes what bugs on reorder? What's the SwiftUI equivalent mistake (`id: \\.self` on mutable values)?"),
  ('edge', "Two rows with the same `id`: undefined behaviour and console warnings. How would you detect it in tests?"),
  ('contrast', "Identity (`id`) vs equality (`==`): which decides insert/delete, and which decides update?"),
  ('practice', "Server returns new IDs after an edit. What happens to row animations and scroll position?")],
 ['identity', 'diffing', 'id'], 'swiftui-lists')
E['task-modifier-lifecycle'] = ('c', """`.task(id:)` starts async work when the view appears, cancels on disappear, and restarts when `id` changes. That's React's `useEffect` with a dependency array and an `AbortController` cleanup, built in.""",
 [('js', "`useEffect(() => { const c = new AbortController(); load(q, c.signal); return () => c.abort() }, [q])` vs `.task(id: q)`: what do you no longer write?"),
  ('edge', "If your loader ignores cancellation, what happens when `id` changes quickly (stale results)?"),
  ('contrast', "`.task` vs `.onAppear { Task { } }`: which cancels automatically?"),
  ('practice', "Search-as-you-type with `.task(id: query)` plus a short `Task.sleep` gives debouncing. Why does that work?")],
 ['task', 'cancel', 'restart'], 'swiftui-state')
E['scroll-reader-target'] = ('e', """`ScrollViewReader` scrolls to a view by **identity** (`proxy.scrollTo(id)`), like `element.scrollIntoView()` on the web but addressed by data ID instead of a DOM ref.""",
 [('js', "Web: `document.getElementById(id).scrollIntoView({block: 'end'})`. How does `scrollTo(id, anchor: .bottom)` compare?"),
  ('edge', "Scrolling to an ID that isn't rendered yet in a lazy stack: does it work?"),
  ('contrast', "`ScrollViewReader` vs `scrollPosition(id:)` (iOS 17): which is two-way?"),
  ('practice', "Chat apps: when should new messages auto-scroll, and when not (user reading history)?")],
 ['scrollviewreader', 'scrollto', 'anchor'], 'swiftui-lists')
E['phase-animator-sequence'] = ('e', """`PhaseAnimator` steps through an enum of phases on each trigger: multi-step animations as data. CSS `@keyframes` with percentages is the web equivalent, but phases here are typed enum cases.""",
 [('js', "CSS `@keyframes` vs `PhaseAnimator(Phase.allCases, trigger:)`: which lets each step have its own timing curve?"),
  ('edge', "What happens if the trigger changes mid-sequence?"),
  ('contrast', "`PhaseAnimator` vs `KeyframeAnimator`: when do you need per-property keyframe tracks?"),
  ('practice', "A \"like\" button bounce: which would you use?")],
 ['phaseanimator', 'phase', 'keyframes'], 'swiftui-animation')
E['scene-phase-autosave'] = ('c', """`@Environment(\\.scenePhase)` tells you when the app goes `active`/`inactive`/`background`, like the web's `visibilitychange` event. Saving on `background` is the iOS equivalent of saving on `pagehide`.""",
 [('js', "`document.visibilityState` and `pagehide` on the web: which scene phase maps to each?"),
  ('edge', "How much time does the app get after going to the background? Can a save be cut off?"),
  ('contrast', "Saving on every keystroke vs on `background`: trade-offs for data loss vs battery?"),
  ('practice', "SwiftData autosaves. When do you still need to save explicitly?")],
 ['scenephase', 'background', 'save'], 'swiftui-state')
E['contrast-ratio'] = ('e', """WCAG contrast is the same formula on the web and iOS. The iOS twist is **dynamic colours**: each colour has light, dark and increased-contrast variants, and every pair must pass in every mode.""",
 [('js', "On the web you check contrast in DevTools. What's the iOS equivalent (Accessibility Inspector)?"),
  ('edge', "Text on images or gradients: how do you guarantee contrast?"),
  ('contrast', "Semantic colours (`.primary`, `.secondary`) vs custom hex colours: which adapts automatically?"),
  ('practice', "When should an app honour \"Increase Contrast\" with different colours?")],
 ['contrast', 'wcag', 'accessibility'], 'swiftui-accessibility')
E['inflection-pluralization'] = ('e', """`^[\\(n) item](inflect: true)` makes Foundation pick the right grammatical form for the language. The web equivalent is `Intl.PluralRules` plus hand-written messages; Apple's version inflects the noun for you.""",
 [('js', "`Intl.PluralRules` tells you \"one\"/\"other\", and you still write both strings. What does Swift's automatic grammar agreement add?"),
  ('edge', "Which languages support automatic inflection? What happens in unsupported ones?"),
  ('contrast', "Inflection vs String Catalog plural variants: when do you need explicit variants?"),
  ('practice', "Gendered languages (\"1 new follower\"/\"una nueva seguidora\"): can inflection handle gender?")],
 ['inflect', 'plural', 'localization'], 'swiftui-accessibility')
E['format-currency-percent'] = ('c', """`value.formatted(.currency(code: "EUR"))` is `Intl.NumberFormat` in JS, the same ICU data underneath, with a Swift API that chains styles (`.precision`, `.notation(.compactName)`).""",
 [('js', "`new Intl.NumberFormat('de-DE', {style: 'currency', currency: 'EUR'})` vs `.formatted(.currency(code: \"EUR\").locale(...))`: same output?"),
  ('edge', "Should currency follow the user's locale or the product's currency? What about the symbol position?"),
  ('contrast', "`FormatStyle` vs `NumberFormatter`: why prefer the newer API?"),
  ('practice', "StoreKit gives you `product.displayPrice`. Why should you never format App Store prices yourself?")],
 ['formatted', 'currency', 'percent'], 'formatting')
E['format-measurement'] = ('e', """`Measurement<UnitLength>` converts and formats units with locale awareness (km vs miles by region). JS has `Intl.NumberFormat` with `style: 'unit'` for formatting, but no conversion.""",
 [('js', "`Intl.NumberFormat('en-US', {style: 'unit', unit: 'kilometer'})` formats. Where does JS do the conversion?"),
  ('edge', "`usage: .road` vs `.asProvided`: what changes for a UK user?"),
  ('contrast', "`Measurement` vs raw `Double`s with comments: which prevents unit mix-ups?"),
  ('practice', "Fitness apps: store in SI units, display in the user's locale. Where does conversion happen?")],
 ['measurement', 'unit', 'convert'], 'formatting')
E['format-bytes-lists-names'] = ('e', """`.formatted(.list(type: .and))`, `ByteCountFormatStyle` and `PersonNameComponents` cover formatting JS does with `Intl.ListFormat` and ad-hoc byte helpers. Foundation localises all three.""",
 [('js', "`new Intl.ListFormat('en', {type: 'conjunction'})` vs `.formatted(.list(type: .and))`: same Oxford comma behaviour?"),
  ('edge', "Bytes: 1000 vs 1024 (`.file` vs `.memory`). Which does Finder use?"),
  ('contrast', "Formatting names with `PersonNameComponents` vs string concatenation: what breaks for Japanese names?"),
  ('practice', "Showing storage usage in settings: which byte count style is least confusing?")],
 ['list format', 'bytes', 'names'], 'formatting')
E['parse-strategies'] = ('e', """Format styles also **parse** user input (`parseStrategy`), turning \"$1,234.50\" into a `Decimal`. JS has no built-in locale-aware parsing (`Intl` only formats), so apps hand-roll regexes.""",
 [('js', "How do you parse \"1.234,50 €\" in JS? Why is that a notorious gap?"),
  ('edge', "What should happen with \"1,2,3\" or \"$-5\"? Where does parsing fail?"),
  ('contrast', "`Decimal` vs `Double` for parsed money: which preserves exact cents?"),
  ('practice', "`TextField(value:format:)` parses for you. When does that behaviour surprise users?")],
 ['parse', 'parsestrategy', 'decimal'], 'formatting')
E['date-components-math'] = ('c', """Adding \"one month\" with `Calendar.date(byAdding: .month, …)` clamps Jan 31 → Feb 28/29. JS `Date` arithmetic overflows into March. Calendars are a Foundation strength, and JS only now gets `Temporal`.""",
 [('js', "`d.setMonth(d.getMonth() + 1)` on Jan 31 gives March 3 in JS. What does `Calendar` give, and why?"),
  ('edge', "DST transitions: is adding 1 day the same as adding 24 hours? When does it differ?"),
  ('contrast', "`Calendar` arithmetic vs `TimeInterval` arithmetic: which for \"same time tomorrow\"?"),
  ('practice', "Subscription renewal dates: whose calendar and time zone decides?")],
 ['calendar', 'adding months', 'date components'], 'dates')
E['days-between'] = ('e', """`calendar.dateComponents([.year, .day], from:to:)` answers \"how many years/days between\" correctly across leap years and DST. JS `(b - a) / 86400000` breaks on DST days.""",
 [('js', "Dividing ms by 86,400,000 in JS: when is the answer off by one?"),
  ('edge', "Birthday on Feb 29: when is the \"next birthday\" in a non-leap year?"),
  ('contrast', "`dateComponents(_:from:to:)` vs `DateInterval.duration`: which respects calendar days?"),
  ('practice', "Age gating (13+): compute in the user's time zone or UTC?")],
 ['days between', 'age', 'calendar'], 'dates')
E['iso8601-timezones'] = ('c', """`Date` is an absolute instant (like JS `Date`'s ms since epoch), and time zones only matter when formatting or doing calendar maths. `Date.ISO8601FormatStyle` parses offsets correctly.""",
 [('js', "JS `Date` is also an instant, but parsing \"2024-03-10\" is treated as UTC while \"2024-03-10T00:00\" is local. Does Foundation have such traps?"),
  ('edge', "\"01:30 on the DST-change day\" may not exist or may happen twice. What does formatting show?"),
  ('contrast', "Storing dates as ISO strings vs Unix timestamps vs `Date` in SwiftData: which avoids ambiguity?"),
  ('practice', "Show an event's time in the event's zone or the user's zone? Who decides in your product?")],
 ['iso8601', 'time zone', 'date'], 'dates')
E['date-interval-overlap'] = ('e', """`DateInterval` has `intersects` and `intersection`, typed interval maths. In JS you'd compare timestamps manually (`a.start < b.end && b.start < a.end`).""",
 [('js', "Write the JS overlap check. Is the Swift `intersects` inclusive of touching endpoints?"),
  ('edge', "A meeting ending at 10:00 and another starting at 10:00: overlap or not? What does `DateInterval` say?"),
  ('contrast', "Pairwise O(n²) checks vs sorting by start then sweeping: which scales to a year of meetings?"),
  ('practice', "Calendar apps use EventKit's `EKEvent`. Where would you still compute overlaps yourself?")],
 ['dateinterval', 'overlap', 'intersects'], 'dates')
E['codable-dates-strategies'] = ('c', """`dateDecodingStrategy` (`.iso8601`, `.secondsSince1970`, custom) tells `JSONDecoder` how dates look in JSON. JS `JSON.parse` leaves dates as strings, and revivers are manual.""",
 [('js', "JS: `JSON.parse(text, (k, v) => k === 'at' ? new Date(v) : v)`. What does a decoding strategy centralise?"),
  ('edge', "ISO strings with fractional seconds: does `.iso8601` accept them? What's the fix?"),
  ('contrast', "Global strategy on the decoder vs a custom `init(from:)` per type: when is each right?"),
  ('practice', "Backend sends milliseconds, not seconds. What bug do you see if you pick `.secondsSince1970`?")],
 ['date decoding', 'strategy', 'iso8601'], 'codable')
E['codable-unknown-enum'] = ('c', """Decoding unknown enum values into an `unknown` case keeps apps working when the server adds values. In TS a union type silently accepts any string at runtime; in Swift an unknown value fails the whole decode unless you handle it.""",
 [('js', "A TS `type Status = 'pending' | 'shipped'` accepts \"refunded\" at runtime silently. What does Swift do by default?"),
  ('edge', "Should `unknown` keep the raw string for logging? How would you model that (`case unknown(String)`)?"),
  ('contrast', "Custom `init(from:)` with a fallback vs making the property `String` and mapping later: which is cleaner?"),
  ('practice', "Old app versions stay in the wild for years. How does this pattern keep them from breaking?")],
 ['unknown', 'enum', 'decode'], 'codable')
E['codable-polymorphic'] = ('c', """A `type` discriminator in JSON decoded into an enum with associated values is the TS discriminated union parsed with zod's `discriminatedUnion`, written by hand in a custom `init(from:)`.""",
 [('js', "zod `z.discriminatedUnion('type', [...])` vs a Swift custom decoder: which is less code, and which is faster?"),
  ('edge', "Unknown `type` values: fail the whole feed, skip the item, or decode as `.unsupported`?"),
  ('contrast', "Enum with payloads vs a protocol with concrete types (`[any FeedItem]`): which is easier to render in SwiftUI?"),
  ('practice', "Server-driven UI feeds are exactly this. How do you version them?")],
 ['polymorphic', 'discriminator', 'type'], 'codable')
E['codable-encode-snake-sorted'] = ('e', """`JSONEncoder` with `.convertToSnakeCase`, `.sortedKeys` and `.prettyPrinted` controls output shape, like `JSON.stringify(obj, null, 2)` plus a key-transform step. Sorted keys make output deterministic for tests and signatures.""",
 [('js', "`JSON.stringify` has no key sorting. How do JS devs get deterministic JSON (for hashing, snapshots)?"),
  ('edge', "`nil` optionals: are they omitted or written as `null` by default?"),
  ('contrast', "`.convertToSnakeCase` vs explicit `CodingKeys`: what happens to acronyms like `userID`?"),
  ('practice', "Snapshot-testing request bodies: why are `.sortedKeys` essential?")],
 ['encode', 'snake case', 'sorted keys'], 'codable')
E['codable-nested-unkeyed'] = ('e', """`nestedContainer` and `unkeyedContainer` decode awkward shapes: envelopes and arrays-as-tuples like `[[0, 1.5]]`. In JS you'd destructure after `JSON.parse`, and in Swift you walk containers.""",
 [('js', "JS: `data.series.map(s => s.points.map(([x, y]) => ({x, y})))`. How many lines is the Swift decoder? Is it worth it?"),
  ('edge', "A point array with 3 elements instead of 2: what should the decoder do?"),
  ('contrast', "Custom containers vs decoding into a raw DTO then mapping: which is easier to maintain?"),
  ('practice', "Chart APIs often send compact arrays for size. When would you ask the backend to change the shape instead?")],
 ['nested container', 'unkeyed', 'decode'], 'codable')
E['url-components-builder'] = ('c', """`URLComponents` + `URLQueryItem` builds URLs with correct escaping, like JS's `URL` + `URLSearchParams`. It never string-concatenates query strings.""",
 [('js', "`new URL(base); url.searchParams.append('q', query)` vs `URLComponents.queryItems`: same escaping rules?"),
  ('edge', "What does `+` in a query value become? Does `URLComponents` encode it? (A classic gotcha.)"),
  ('contrast', "String interpolation into URLs vs `URLComponents`: which bugs does the latter prevent?"),
  ('practice', "Where do you centralise base URLs and paths: an `Endpoint` enum, a request builder?")],
 ['urlcomponents', 'query items', 'url'], 'networking')
E['urlsession-get-decode'] = ('c', """`let (data, response) = try await URLSession.shared.data(from: url)` then `JSONDecoder().decode(...)` is `await fetch(url)` then `await res.json()`, except Swift makes you check the status code (fetch doesn't throw on 404, and neither does URLSession).""",
 [('js', "`fetch` resolves on 404. Does `URLSession.data(from:)` throw on 404? What must you check?"),
  ('edge', "What happens if the response isn't JSON (an HTML error page)? Where does it fail?"),
  ('contrast', "`URLSession.shared` vs a configured session (timeouts, caching): when do you need your own?"),
  ('practice', "How do you mock `URLSession` in tests (`URLProtocol` subclass)? Why not a protocol wrapper?")],
 ['urlsession', 'fetch', 'decode'], 'networking')
E['urlsession-post-json'] = ('e', """`URLRequest` with `httpMethod = "POST"`, headers and `httpBody = try JSONEncoder().encode(body)` is `fetch(url, {method, headers, body: JSON.stringify(...)})` with typed encoding.""",
 [('js', "`fetch(url, {method: 'POST', headers, body: JSON.stringify(x)})`. Which part does Swift type-check?"),
  ('edge', "Forgetting `Content-Type: application/json`: what does the server see?"),
  ('contrast', "`URLSession.upload(for:from:)` vs `data(for:)` with `httpBody`: when does upload matter (large bodies, background)?"),
  ('practice', "Where should the auth token come from: a stored property, the Keychain, an interceptor-like wrapper?")],
 ['urlrequest', 'post', 'headers'], 'networking')
E['retry-with-backoff'] = ('c', """Retry with exponential backoff and a retryability check is the same as JS's `p-retry`, written as a generic `async` function with `Task.sleep`, which also respects cancellation.""",
 [('js', "`p-retry` in JS vs a hand-written Swift `retry`: what does `Task.sleep` give you that `setTimeout` promises don't (cancellation)?"),
  ('edge', "Which errors are retryable? A 400? A 503? `URLError.notConnectedToInternet`?"),
  ('contrast', "Exponential backoff vs adding jitter: why does jitter matter for millions of clients?"),
  ('practice', "Retrying a non-idempotent POST (payment): what could go wrong, and what's the fix (idempotency keys)?")],
 ['retry', 'backoff', 'exponential'], 'networking')
E['concurrent-downloads'] = ('c', """Fetching many resources concurrently with a task group and collecting results (skipping failures) is `Promise.allSettled` over many fetches, but with real parallelism and structured cancellation.""",
 [('js', "`Promise.allSettled(ids.map(fetchUser))` vs a Swift task group: how do you get \"settled\" semantics (per-task `Result`)?"),
  ('edge', "1,000 IDs: should you start 1,000 tasks at once? How would you limit concurrency?"),
  ('contrast', "Results in completion order vs input order: how do you restore input order?"),
  ('practice', "Loading avatars for a list: task group, per-row `.task`, or an image library?")],
 ['task group', 'concurrent', 'download'], 'networking')
E['nscache-image-cache'] = ('c', """`NSCache` is an in-memory cache that **evicts automatically** under memory pressure. There's no JS equivalent (a `Map` never evicts), and it's thread-safe too.""",
 [('js', "A JS `Map` cache grows forever. What does `NSCache` do when iOS warns about memory?"),
  ('edge', "Why must keys be `NSString`/objects, not Swift `String`? What does that say about its Objective-C roots?"),
  ('contrast', "`NSCache` vs a dictionary + manual LRU vs `URLCache`: which for decoded images, which for HTTP responses?"),
  ('practice', "`countLimit` and `totalCostLimit`: how would you set the cost for an image?")],
 ['nscache', 'cache', 'eviction'], 'persistence')
E['userdefaults-wrapper'] = ('c', """A `@propertyWrapper` around `UserDefaults` gives typed, defaulted settings, like wrapping `localStorage` with JSON (de)serialisation and defaults. Swift makes it declarative per property.""",
 [('js', "JS `localStorage` stores strings only; you JSON-wrap everything. How does `Codable` make the Swift wrapper generic?"),
  ('edge', "What happens if a stored value no longer decodes after a model change? What should the wrapper return?"),
  ('contrast', "Custom wrapper vs `@AppStorage`: when do you need the custom one (non-SwiftUI code, Codable types)?"),
  ('practice', "What must never go in `UserDefaults`? (Secrets. It's a plain plist on disk.)")],
 ['userdefaults', 'property wrapper', 'settings'], 'persistence')
E['combine-pipeline'] = ('c', """Combine publishers with `map`, `filter`, `scan` and `removeDuplicates` are RxJS observables. `scan` is RxJS `scan`, `removeDuplicates` is `distinctUntilChanged`. Apple's own reactive framework predates async sequences.""",
 [('js', "Map each Combine operator here to its RxJS name. Which one is named differently?"),
  ('contrast', "Combine vs `AsyncSequence` + swift-async-algorithms: which does Apple push for new code?"),
  ('edge', "Does a publisher do anything before a subscriber attaches (cold vs hot)?"),
  ('practice', "Where is Combine still the right tool in 2026 (`@Published` streams, UIKit bindings)?")],
 ['combine', 'publisher', 'map'], 'combine')
E['combine-subjects'] = ('c', """`PassthroughSubject` is RxJS `Subject` (no current value), and `CurrentValueSubject` is `BehaviorSubject` (holds and replays the latest value to new subscribers).""",
 [('js', "RxJS `Subject` vs `BehaviorSubject`: which Combine subject is which?"),
  ('edge', "A late subscriber to a `PassthroughSubject`: does it see past events?"),
  ('contrast', "Subjects vs `@Published` vs `AsyncStream`: which to use for a view model's event stream?"),
  ('practice', "Why are subjects often kept private and exposed as `AnyPublisher`?")],
 ['subject', 'passthrough', 'currentvalue'], 'combine')
E['combine-published-sink'] = ('c', """`@Published` + `$query.debounce(...).removeDuplicates().sink { }` is the classic search pipeline, like RxJS `fromEvent(input).pipe(debounceTime, distinctUntilChanged)`, with `$` giving you the publisher.""",
 [('js', "The RxJS search pipeline vs the Combine one: line-for-line, what's the same?"),
  ('edge', "`@Published` emits in `willSet`, before the value changes. What bug does that cause when reading the property in `sink`?"),
  ('contrast', "Combine debounce vs `.task(id:)` + `Task.sleep`: which is simpler in SwiftUI now?"),
  ('practice', "Storing `AnyCancellable`s in a `Set`: what happens if you forget to store it?")],
 ['published', 'sink', 'debounce'], 'combine')
E['combine-future'] = ('e', """`Future` runs its closure **immediately** and caches one result, exactly like a JS `Promise` (eager). Most Combine publishers are lazy, which makes `Future` the odd one out.""",
 [('js', "A JS Promise starts running when created. Does a Combine `Future`? What about `Deferred { Future { } }`?"),
  ('edge', "Subscribing twice to one `Future`: does the work run twice?"),
  ('contrast', "`Future` vs an `async` function: which should new code use?"),
  ('practice', "Bridging a callback API: `Future` or `withCheckedContinuation`?")],
 ['future', 'promise', 'combine'], 'combine')
E['combine-error-handling'] = ('e', """`tryMap`, `catch` and `replaceError` are RxJS's `map` + `catchError`. A failure **terminates** the stream in both, which is why recovery operators matter.""",
 [('js', "RxJS `catchError(() => of(-1))` vs Combine `.catch { _ in Just(-1) }`: same termination semantics?"),
  ('edge', "After an error, does the upstream keep emitting? How do you keep a long-lived stream alive (`flatMap` + `catch` inside)?"),
  ('contrast', "`replaceError(with:)` vs `catch` vs `retry(_:)`: which for which failure?"),
  ('practice', "A search stream dies on the first network error. How do you structure it so the next query still works?")],
 ['trymap', 'catch', 'replaceerror'], 'combine')
E['combine-combinelatest-zip'] = ('e', """`combineLatest` emits whenever either side changes (the latest pair), `zip` pairs values one-to-one, and `merge` interleaves same-typed streams. These are identical to RxJS's operators of the same names.""",
 [('js', "RxJS `combineLatest`/`zip`/`merge`: any behavioural differences in Combine?"),
  ('edge', "`combineLatest` before both sides have emitted once: does it emit?"),
  ('contrast', "Form validation from three fields: `combineLatest` or `zip`? Why is `zip` wrong here?"),
  ('practice', "Replacing these with `@Observable` computed properties: when does that remove the need for Combine?")],
 ['combinelatest', 'zip', 'merge'], 'combine')
E['combine-cancellation'] = ('c', """A subscription lives only as long as its `AnyCancellable`. Drop it and the subscription is cancelled. RxJS makes you call `unsubscribe()`, while Combine ties it to ARC ownership.""",
 [('js', "RxJS leaks if you forget `unsubscribe()`. What's the opposite Combine bug (it stops immediately because you didn't store the cancellable)?"),
  ('edge', "Does cancelling stop upstream work (a network request) or just delivery?"),
  ('contrast', "`Set<AnyCancellable>` on the owner vs `.store(in:)` vs `assign(to: &$prop)`: which avoids retain cycles?"),
  ('practice', "A view model's `sink { self.x = $0 }` stored in its own `cancellables`: cycle? How to fix?")],
 ['anycancellable', 'cancel', 'subscription'], 'combine')
E['combine-async-bridge'] = ('e', """Every publisher has `.values`, an `AsyncSequence`, so `for await v in publisher.values` bridges Combine into async/await. It's RxJS's `for await (const v of eachValueFrom(obs))`.""",
 [('js', "rxjs-for-await's `eachValueFrom(obs)` vs Combine `.values`: what happens to backpressure in each?"),
  ('edge', "Does a `for await` over `.values` of a `@Published` ever end? How do you stop it?"),
  ('contrast', "Keeping Combine at the edges with `.values` vs rewriting to `AsyncStream`: migration strategy?"),
  ('practice', "Observing `NotificationCenter` or `@Published` in a `.task` loop: which does the view cancel automatically?")],
 ['values', 'asyncpublisher', 'bridge'], 'combine')
E['coredata-crud'] = ('c', """Core Data is an **object graph manager** over SQLite: you mutate managed objects in a context, then `save()`. The closest JS analogue is an ORM with a unit of work (like MikroORM's `em.flush()`), and contexts are thread-confined.""",
 [('js', "An ORM unit of work (`em.persist(); em.flush()`) vs `context.insert; context.save()`: same model?"),
  ('edge', "Why must all context work happen inside `perform`? What happens when you touch a context from the wrong thread?"),
  ('contrast', "Core Data vs SwiftData: what does SwiftData remove (the model file, `NSManagedObject` subclasses), and what does it keep?"),
  ('practice', "Your app already ships Core Data. Migrate to SwiftData or keep it? What decides?")],
 ['core data', 'context', 'save'], 'coredata')
