E = {}
E['coredata-predicates'] = ('e', """`NSPredicate(format:)` is a string query language (`title CONTAINS[cd] %@`), like writing SQL `WHERE` clauses or a MongoDB filter. It's checked only at runtime, which is why SwiftData's typed `#Predicate` exists.""",
 [('js', "Prisma's typed `where: { title: { contains } }` vs `NSPredicate` format strings: which catches a typo at compile time?"),
  ('edge', "What do `[c]`, `[d]` and `[cd]` mean? What happens with an apostrophe in the search text if you interpolate instead of using `%@`?"),
  ('contrast', "`NSPredicate` vs `#Predicate`: which one can express subqueries and `ANY` on relationships today?"),
  ('practice', "Search across title and body with diacritic-insensitive matching: write the predicate.")],
 ['nspredicate', 'predicate', 'format'], 'coredata')
E['coredata-relationships'] = ('e', """Relationships with inverses and delete rules (cascade/nullify) are foreign keys with `ON DELETE CASCADE` / `SET NULL`. Core Data keeps both sides of the object graph in sync in memory, where SQL only enforces them on the database.""",
 [('js', "An ORM relation with `onDelete: 'cascade'` vs Core Data's cascade rule: where does each run (DB vs object graph)?"),
  ('edge', "Why does Core Data warn when a relationship has no inverse? What goes wrong?"),
  ('contrast', "Cascade vs nullify vs deny: which fits folder → notes, and which fits note → tags?"),
  ('practice', "A to-many relationship is an unordered `NSSet` by default. How do you keep notes in a user-defined order?")],
 ['relationship', 'cascade', 'inverse'], 'coredata')
E['coredata-pagination'] = ('e', """`fetchLimit` and `fetchOffset` are SQL `LIMIT`/`OFFSET`, and `count(for:)` is `SELECT COUNT(*)` without loading objects. `fetchBatchSize` adds faulting-based paging with no JS equivalent.""",
 [('js', "`LIMIT/OFFSET` pagination in your SQL or ORM vs `fetchLimit`/`fetchOffset`: same pitfalls with inserts between pages?"),
  ('edge', "Without a sort descriptor, is page order stable? Why must pagination always sort?"),
  ('contrast', "`fetchOffset` paging vs `fetchBatchSize` faulting vs cursor-based paging: which fits an infinite list?"),
  ('practice', "`@FetchRequest` in SwiftUI loads lazily already. When do you page manually?")],
 ['fetchlimit', 'offset', 'pagination'], 'coredata')
E['coredata-background-context'] = ('c', """Import on a background context, save, and let the main (view) context merge the changes. It's like doing heavy work in a Web Worker and posting results back, except Core Data merges object graphs, not messages.""",
 [('js', "Web Worker computes, posts a message, the main thread updates state. How is `automaticallyMergesChangesFromParent` like that?"),
  ('edge', "Passing an `NSManagedObject` across contexts crashes or corrupts. What do you pass instead (`NSManagedObjectID`)?"),
  ('contrast', "`newBackgroundContext()` vs `performBackgroundTask` vs `NSBatchInsertRequest`: which for 100k rows?"),
  ('practice', "Merge conflicts when both contexts edit the same object: what's `NSMergeByPropertyObjectTrumpMergePolicy`?")],
 ['background context', 'merge', 'perform'], 'coredata')
E['swiftdata-crud'] = ('c', """SwiftData's `@Model` turns a class into a persisted entity, and `ModelContext` inserts, fetches and saves. It's Prisma/TypeORM-level ergonomics on top of Core Data, with Swift macros instead of a schema file.""",
 [('js', "Prisma schema file + generated client vs SwiftData `@Model` macro: where does the schema live in each?"),
  ('edge', "Why must `@Model` types be classes, not structs?"),
  ('contrast', "SwiftData autosave vs calling `try context.save()`: when does unsaved data get lost?"),
  ('practice', "`@Query` in a view vs fetching in a view model: which does Apple's sample code prefer, and why do architecture purists object?")],
 ['swiftdata', 'model', 'modelcontext'], 'swiftdata')
E['swiftdata-predicates'] = ('c', """`#Predicate { $0.rating >= 4 }` is a **typed** query written in Swift and translated to SQL, the way Prisma's typed `where` object replaces string queries. Typos and type errors fail at compile time.""",
 [('js', "Prisma `where: { rating: { gte: 4 } }` vs `#Predicate { $0.rating >= 4 }`: which is more natural to write?"),
  ('edge', "Why can't a `#Predicate` call your own functions or computed properties? What does the macro translate to?"),
  ('contrast', "Filtering with `#Predicate` in the store vs `filter` in memory: when does the difference matter?"),
  ('practice', "Dynamic predicates (user-chosen filters) with `@Query`: how do you rebuild the query in a subview's `init`?")],
 ['predicate', 'query', 'swiftdata'], 'swiftdata')
E['swiftdata-relationships'] = ('e', """`@Relationship(deleteRule: .cascade, inverse:)` declares related models. SwiftData infers many inverses, and cascade deletes follow the graph, like ORM relations with `onDelete: cascade`.""",
 [('js', "Prisma requires both sides of a relation in the schema. What does SwiftData infer for you?"),
  ('edge', "Deleting an author with cascade: when is the book count updated (before or after save)?"),
  ('contrast', "Many-to-many in SwiftData vs a join table in SQL: what do you not have to write?"),
  ('practice', "Should an array relationship's order be relied on? (It isn't guaranteed.) What do you store instead?")],
 ['relationship', 'cascade', 'swiftdata'], 'swiftdata')
E['swiftdata-pagination-unique'] = ('e', """`@Attribute(.unique)` makes inserts **upsert** on a conflicting key, like SQL `INSERT … ON CONFLICT DO UPDATE`. `FetchDescriptor` with `fetchLimit`/`fetchOffset` pages results.""",
 [('js', "Postgres `ON CONFLICT (slug) DO UPDATE` vs `@Attribute(.unique)`: does SwiftData update or replace?"),
  ('edge', "What happens to relationships of the old object when a unique insert replaces it?"),
  ('contrast', "Unique attributes vs fetching first and updating manually: which is faster for syncing 1,000 items?"),
  ('practice', "Server sync: which field should be unique, the server ID or the local UUID?")],
 ['unique', 'upsert', 'fetchdescriptor'], 'swiftdata')
E['corelocation-distances'] = ('e', """`CLLocation.distance(from:)` computes great-circle distance in metres, the haversine formula JS devs copy from Stack Overflow, built in and accurate on the WGS-84 ellipsoid.""",
 [('js', "The JS haversine snippet assumes a spherical Earth. How accurate is it compared with `CLLocation.distance(from:)`?"),
  ('edge', "Distances across the antimeridian (±180° longitude): does your sorting still work?"),
  ('contrast', "Sorting places by distance on-device vs asking the server (geo index): when is each right?"),
  ('practice', "Showing \"1.2 km\" vs \"0.7 mi\": which formatter respects the user's region?")],
 ['cllocation', 'distance', 'coordinates'], 'location')
E['mapkit-region'] = ('e', """Fitting all annotations into a map region (center + span with padding) is the MapKit version of Leaflet/Google Maps `fitBounds`. In SwiftUI's `Map` you'd often use `.automatic` camera positioning instead.""",
 [('js', "Leaflet `map.fitBounds(bounds, {padding})` vs computing an `MKCoordinateRegion`: what does MapKit not do for you in the old API?"),
  ('edge', "A single annotation gives a zero span. What minimum span should you use?"),
  ('contrast', "`MKCoordinateRegion` (degrees) vs `MKMapRect` (projected points): which is correct near the poles?"),
  ('practice', "SwiftUI `Map(position: .constant(.automatic))`: when do you still compute regions yourself?")],
 ['mapkit', 'region', 'span'], 'location')
E['notificationcenter-async'] = ('e', """`NotificationCenter` is an app-wide event bus, like a global `EventEmitter` or DOM `CustomEvent`s. `notifications(named:)` turns it into an `AsyncSequence` you can `for await` over.""",
 [('js', "`window.dispatchEvent(new CustomEvent('chat.message'))` vs `NotificationCenter.default.post`: which is typed? (Neither, really.)"),
  ('edge', "Stringly-typed `userInfo` dictionaries: how do you make notification payloads type-safe?"),
  ('contrast', "NotificationCenter vs delegates vs closures vs `@Observable`: when is a global bus justified?"),
  ('practice', "System notifications you actually observe: keyboard frame, app lifecycle, `NSPersistentStoreRemoteChange`.")],
 ['notificationcenter', 'notification', 'observer'], 'foundation')
E['file-persistence-versioned'] = ('c', """Saving `Codable` data to the app's Documents directory as JSON, with a version number for migrations, is like persisting app state to IndexedDB or `localStorage` with a schema version and a migration step on load.""",
 [('js', "Redux-persist has `version` + `migrate`. What does your Swift loader need to do when `version` is old?"),
  ('edge', "Crash mid-write: how does `.atomic` writing prevent a corrupted file?"),
  ('contrast', "JSON files vs SwiftData: when is a single JSON file the better choice (small data, easy export)?"),
  ('practice', "Should app data live in Documents (visible in Files) or Application Support? Who decides?")],
 ['save', 'documents', 'codable'], 'persistence')
E['cryptokit-hmac-aes'] = ('e', """CryptoKit gives HMAC signatures, AES-GCM encryption and HKDF key derivation with safe defaults, the Swift counterpart of Node's `crypto` or WebCrypto, with a typed API (`SymmetricKey`, `SealedBox`).""",
 [('js', "WebCrypto's `subtle.encrypt({name: 'AES-GCM', iv})` vs `AES.GCM.seal(data, using: key)`: who manages the nonce?"),
  ('edge', "Reusing a nonce with the same key in AES-GCM: why is it catastrophic?"),
  ('contrast', "HMAC (integrity, shared key) vs a digital signature (P256, public key): which for verifying a server response?"),
  ('practice', "Where do keys live on iOS: Keychain, Secure Enclave? Why is deriving keys from a password risky?")],
 ['cryptokit', 'hmac', 'aes'], 'security')
E['attributed-string-runs'] = ('e', """`AttributedString` stores text plus attribute **runs** (ranges with styles). The web does this with nested `<span>`s. `Text` renders it natively, so highlighting search matches is just setting attributes on ranges.""",
 [('js', "Highlighting search terms on the web means splitting the string into spans. How does `AttributedString` avoid rebuilding the view tree?"),
  ('edge', "Case-insensitive ranges for \"Straße\" vs \"STRASSE\": do the ranges still line up with the original string?"),
  ('contrast', "`AttributedString` vs `NSAttributedString`: which is Swift-native and value-typed?"),
  ('practice', "Markdown in `Text(\"**bold**\")` creates an `AttributedString`. When is that enough?")],
 ['attributedstring', 'runs', 'highlight'], 'foundation')
E['repository-pattern'] = ('c', """A repository hides where data comes from (network, cache, DB) behind a protocol. It's the same pattern as a JS data-access layer or React Query's cache in front of fetchers, with Swift protocols making the seams testable.""",
 [('js', "React Query caches by key in front of fetchers. How is a Swift repository with a cache similar, and what does it not do (invalidation UI, retries)?"),
  ('edge', "Stale-while-revalidate: return the cache immediately and refresh in the background. How do you notify the UI of the fresh value?"),
  ('contrast', "Repository protocol vs calling `URLSession` in the view model: when is the extra layer worth it?"),
  ('practice', "Where does offline support fit: in the repository or a separate sync engine?")],
 ['repository', 'cache', 'protocol'], 'architecture')
E['coordinator-router'] = ('c', """A coordinator/router moves navigation decisions out of views into testable logic, like centralising route changes in a React Router action or a Redux navigation slice, instead of scattering `navigate()` calls.""",
 [('js', "`navigate('/checkout')` scattered in components vs a central router: which is easier to test and deep-link?"),
  ('edge', "A flow that ends by dismissing a sheet *and* popping to root: who owns that sequence?"),
  ('contrast', "UIKit coordinators vs SwiftUI `NavigationPath` owned by a router object: what carried over?"),
  ('practice', "Would you adopt a routing library (SwiftfulRouting) or keep a small in-house router?")],
 ['coordinator', 'router', 'navigation'], 'architecture')
E['dependency-container'] = ('e', """A tiny DI container registers factories by protocol type and resolves them. It's InversifyJS or NestJS's injector in miniature, and `ObjectIdentifier(T.self)` works as the key.""",
 [('js', "NestJS resolves by class or token. What's the Swift equivalent of a token (`ObjectIdentifier` of a protocol type)?"),
  ('edge', "Resolving an unregistered type: crash, optional, or throw? What do real containers do?"),
  ('contrast', "Runtime container vs compile-time DI (initialiser injection, `swift-dependencies`): which catches missing deps earlier?"),
  ('practice', "Is a DI container overkill for most iOS apps? When does it pay off?")],
 ['dependency', 'container', 'resolve'], 'architecture')
E['feature-flags'] = ('c', """Layered flags (code defaults < remote config < local overrides) are what LaunchDarkly or Firebase Remote Config give JS apps. Decoding them with `Codable` and falling back safely is the iOS client side.""",
 [('js', "LaunchDarkly's JS SDK evaluates flags with defaults. What must the iOS client do when remote config fails to load?"),
  ('edge', "A flag flips mid-session: should the UI change immediately or on next launch?"),
  ('contrast', "Feature flags vs A/B tests vs app version gating: which tool for which job?"),
  ('practice', "App Store review sees your app with some flag values. What's the risk of hiding features behind flags?")],
 ['feature flag', 'remote config', 'defaults'], 'architecture')
E['test-doubles-spy'] = ('c', """Stubs return canned data, spies record calls, fakes are working lightweight implementations. It's the same vocabulary as Jest mocks (`jest.fn()`), but in Swift you write small types conforming to a protocol, with no module mocking.""",
 [('js', "`jest.fn().mockResolvedValue(x)` vs a Swift `StubPaymentService`: which is more code, and which is clearer when reading a test?"),
  ('edge', "Spying on an `async` method from a `@MainActor` test: where do recorded calls need to be stored safely?"),
  ('contrast', "Stub vs spy vs fake vs mock: which do you need to test \"charge is called exactly once\"?"),
  ('practice', "Swift Testing's `#expect` vs XCTest's `XCTAssert`: which would you use for new tests?")],
 ['test double', 'spy', 'stub'], 'testing')
E['local-notification-triggers'] = ('e', """`UNCalendarNotificationTrigger` fires at the next date matching some `DateComponents`, like a cron expression for local notifications. The web has no reliable scheduled-notification equivalent.""",
 [('js', "Scheduling a notification for 9:00 every weekday on the web needs a push server. What can iOS do locally?"),
  ('edge', "The user changes time zone: does a calendar trigger fire at 9:00 local in the new zone?"),
  ('contrast', "Calendar trigger vs time-interval trigger vs location trigger: which for a medication reminder?"),
  ('practice', "iOS limits pending local notifications (64). How do you schedule a year of reminders?")],
 ['notification', 'trigger', 'datecomponents'], 'platform')
E['widget-timeline'] = ('e', """WidgetKit widgets don't run code on demand. You give the system a **timeline** of pre-rendered entries up front. It's closer to generating static pages with a revalidate schedule (ISR) than to a live React component.""",
 [('js', "Next.js ISR regenerates pages on a schedule. How is a widget timeline with a `.after(date)` reload policy similar?"),
  ('edge', "Why can't a widget show a live seconds counter by re-rendering? What does `Text(date, style: .timer)` do instead?"),
  ('contrast', "`.atEnd` vs `.after(date)` vs `.never` reload policies: which for a calendar widget?"),
  ('practice', "Updating the widget when the app's data changes: which API (`WidgetCenter.shared.reloadAllTimelines()`)?")],
 ['widgetkit', 'timeline', 'entry'], 'platform')
E['storekit-entitlements'] = ('c', """StoreKit 2 gives verified transactions; your app decides access, like a web app checking a subscription status from Stripe webhooks, except the source of truth is the signed on-device receipt (`Transaction.currentEntitlements`).""",
 [('js', "Stripe webhooks tell your server about subscriptions. Where does an iOS app get the truth, and can it work offline?"),
  ('edge', "Grace period, billing retry, refunded, upgraded mid-period: which transactions still grant access?"),
  ('contrast', "Checking entitlements on device vs App Store Server API on your backend: which do you trust for server-side features?"),
  ('practice', "Family Sharing: does a family member's purchase grant access? How do you know (`ownershipType`)?")],
 ['storekit', 'entitlement', 'transaction'], 'platform')
E['apns-payload'] = ('e', """Push payloads are JSON with a reserved `aps` dictionary plus your custom keys. Decoding them with `Codable` is like typing a Web Push payload, but Apple defines the `aps` part (alert, badge, sound, content-available).""",
 [('js', "Web Push payloads are free-form. Which parts of an APNs payload does iOS interpret for you?"),
  ('edge', "Silent pushes (`content-available: 1`): are they guaranteed to wake the app? (No, they're throttled.) Why?"),
  ('contrast', "Alert push vs silent push vs Notification Service Extension (mutable-content): which can modify the message?"),
  ('practice', "Deep-linking from a tapped notification: where do you read the payload and route?")],
 ['apns', 'payload', 'aps'], 'platform')
E['firestore-cursor-paging'] = ('c', """Cursor pagination (`startAfter(lastDoc)`) doesn't skip or duplicate items when new ones arrive, unlike offsets. It's the same as GraphQL Relay cursors or Firestore's JS SDK.""",
 [('js', "Relay `after: cursor` vs `offset`: which breaks when a new post is inserted at the top?"),
  ('edge', "Two posts with the same `createdAt`: why must the cursor include a tie-breaker (ID)?"),
  ('contrast', "Cursor paging vs `fetchOffset` paging in Core Data: when is offset still fine (local, static data)?"),
  ('practice', "Pull-to-refresh plus infinite scroll: how do you merge new items at the top with cursor pages below?")],
 ['cursor', 'pagination', 'firestore'], 'backend')
E['auth-state-machine'] = ('c', """Auth as an enum state machine (`signedOut`, `signingIn`, `signedIn(user)`, `error`) makes impossible states unrepresentable, the same idea as XState or a discriminated-union reducer in React.""",
 [('js', "React auth state as `{ user, loading, error }` allows `loading && user`. How does the Swift enum rule that out?"),
  ('edge', "Token refresh while `signedIn`: a new state, or a side effect? What happens to in-flight requests?"),
  ('contrast', "Enum state machine vs Firebase's auth listener callback: where does the listener feed events in?"),
  ('practice', "Sign in with Apple: which states and errors must the UI handle (cancelled, credential revoked)?")],
 ['auth', 'state machine', 'signed in'], 'backend')
E['health-step-aggregation'] = ('e', """HealthKit samples are intervals, and charts need per-day totals in the user's time zone. Grouping by `Calendar.startOfDay` is the key step, just as bucketing timestamps by local day in JS needs the right time zone.""",
 [('js', "Bucketing timestamps by day in JS with `toISOString().slice(0,10)` uses UTC. What goes wrong for a user in Tokyo?"),
  ('edge', "A sample spanning midnight: which day gets the steps? How does `HKStatisticsCollectionQuery` split it?"),
  ('contrast', "Aggregating samples yourself vs `HKStatisticsCollectionQuery`: which handles duplicate sources (watch + phone)?"),
  ('practice', "Travel across time zones: should history be shown in the zone where the steps happened?")],
 ['aggregate', 'per day', 'samples'], 'platform')
E['chart-binning'] = ('e', """Swift Charts draws what you give it, so binning values into histogram buckets is your job, like preparing data for Chart.js or D3's `d3.bin()`.""",
 [('js', "`d3.bin().thresholds(...)` vs hand-rolled binning: what edge conventions does D3 use (half-open)?"),
  ('edge', "Negative values and a value exactly on a bin edge: which bucket?"),
  ('contrast', "Precomputed bins vs `BarMark(x: .value(\"\", v), …)` with Swift Charts' own binning (`bins`, iOS 17+)?"),
  ('practice', "Where should binning happen for large datasets: on device or server?")],
 ['binning', 'histogram', 'charts'], 'platform')
E['image-cache-two-tier'] = ('c', """Memory cache first, then disk, then network, as an actor to coordinate concurrent requests. It's how Kingfisher/Nuke (and browser HTTP caches) work, with the actor serialising cache state.""",
 [('js', "The browser gives you memory + disk HTTP caches for free. What must an iOS app implement itself for decoded images?"),
  ('edge', "Disk cache growth: when and how do you evict (size limit, age)? Which folder (Caches) can iOS purge?"),
  ('contrast', "Your own cache vs `URLCache` vs Kingfisher/Nuke: when is rolling your own justified?"),
  ('practice', "Hash URLs for file names: why SHA-256 and not `hashValue`?")],
 ['image cache', 'disk', 'memory'], 'persistence')
E['accessibility-labels'] = ('c', """VoiceOver reads `accessibilityLabel`s, so a row showing `★★★★☆ 4.2 $19.99 🔥` needs a spoken label like \"Rated 4.2 out of 5, 19 dollars 99, popular\". It's ARIA `aria-label` for native views.""",
 [('js', "`aria-label` on a web element vs `.accessibilityLabel` in SwiftUI: what's `.accessibilityElement(children: .combine)` in ARIA terms?"),
  ('edge', "Emoji and symbols read aloud: what does VoiceOver say for \"🔥\" or \"★\"? Why override it?"),
  ('contrast', "Label vs value vs hint vs traits: which carries \"4.2 stars\", and which carries \"double-tap to buy\"?"),
  ('practice', "How do you test VoiceOver output without a device (Accessibility Inspector, XCUITest)?")],
 ['accessibility label', 'voiceover', 'aria'], 'swiftui-accessibility')
E['dispatch-group'] = ('e', """`DispatchGroup` with `enter`/`leave`/`wait` is pre-async fan-out/fan-in, like hand-counting outstanding callbacks before `Promise.all` existed. Task groups replace it in modern Swift.""",
 [('js', "Before `Promise.all`, JS devs counted callbacks with a counter. How is `DispatchGroup` the same idea?"),
  ('edge', "Forgetting a `leave()` or calling it twice: what happens?"),
  ('contrast', "`group.wait()` (blocks the thread) vs `group.notify(queue:)` vs `withTaskGroup`: which never blocks?"),
  ('practice', "Where does `DispatchGroup` still appear: legacy code, `XCTestExpectation`-style waiting?")],
 ['dispatchgroup', 'enter', 'leave'], 'concurrency')
E['predict-serial-queue-order'] = ('e', """A serial queue runs blocks one at a time in FIFO order. `async` enqueues and returns, and `sync` enqueues and waits. JS's event loop is one serial queue, so the ordering intuition carries over, but `sync` has no JS equivalent.""",
 [('js', "`setTimeout(f, 0)` is like `queue.async`. What would a blocking `queue.sync` mean on JS's single thread?"),
  ('edge', "`queue.sync` from inside a block already running on `queue`: why does it deadlock?"),
  ('contrast', "Serial vs concurrent queues: which gives ordering guarantees?"),
  ('practice', "`DispatchQueue.main.async` vs `@MainActor`: which should new code use?")],
 ['serial queue', 'sync', 'async'], 'concurrency')
E['unidirectional-store'] = ('c', """A TCA/Redux-style store: state is a struct, actions are an enum, a pure reducer mutates `inout` state and returns effects. It's Redux with value types, where `inout` replaces returning a new state object.""",
 [('js', "Redux reducers return new state. Swift reducers take `inout` state. Is that still pure? Why is it efficient?"),
  ('edge', "Effects that return actions: how do you cancel a long-running effect when the user leaves?"),
  ('contrast', "TCA vs MVVM with `@Observable`: which scales for a 50-screen app, and which is simpler for 5 screens?"),
  ('practice', "Testing a reducer: what do you assert (state after each action, emitted effects)?")],
 ['reducer', 'store', 'action'], 'architecture')
E['diffable-snapshot'] = ('c', """Diffable data sources describe the **whole** desired state by identifiers, and UIKit computes and animates the diff. It's React's reconciliation model brought to `UITableView`/`UICollectionView`.""",
 [('js', "React reconciles by `key`. Diffable data sources reconcile by item identifier. What's the equivalent of a duplicate key bug?"),
  ('edge', "`reloadItems` vs `reconfigureItems`: which keeps the cell and just updates its content?"),
  ('contrast', "Diffable snapshots vs `performBatchUpdates` with index paths: which crashes when counts don't match?"),
  ('practice', "Should item identifiers be the model objects or their IDs? What goes wrong with whole models?")],
 ['diffable', 'snapshot', 'identifier'], 'uikit')
E['sort-descriptors-swift'] = ('e', """`SortDescriptor(\\.score, order: .reverse)` arrays describe multi-key sorting as data, like a `sortBy: [{field, dir}]` config object in JS tables. They work on plain Swift types and SwiftData queries alike.""",
 [('js', "A table's `sortBy` config in JS drives a comparator. How do `[SortDescriptor]` make that config type-safe?"),
  ('edge', "`.localizedStandard` puts \"file2\" before \"file10\". What does plain `<` do?"),
  ('contrast', "`SortDescriptor` vs `KeyPathComparator` vs a closure: which can SwiftUI's `Table` bind to column headers?"),
  ('practice', "Persisting the user's chosen sort order: can `SortDescriptor` be `Codable`?")],
 ['sortdescriptor', 'sort', 'keypathcomparator'], 'foundation')
E['ab-test-bucketing'] = ('c', """Deterministic bucketing hashes `experiment:userID` with a stable hash (FNV-1a), because Swift's `Hasher` is reseeded every launch. JS has no randomised built-in hash, but the same stable-hash logic appears in every A/B SDK.""",
 [('js', "A JS A/B SDK hashes user IDs with murmurhash. Why can't Swift use `hashValue` for the same job?"),
  ('edge', "Changing the split from 50/50 to 90/10: do existing users switch buckets? Should they?"),
  ('contrast', "Client-side bucketing vs server-assigned variants: which works offline, and which is consistent across devices?"),
  ('practice', "Why salt with the experiment name? What correlation bug happens without it?")],
 ['bucketing', 'hash', 'experiment'], 'product')
E['review-prompt-rules'] = ('e', """Deciding *when* to call `requestReview()` is product logic: after successes, not after crashes, and rate-limited. It's like gating an NPS survey in a web app, except Apple also enforces 3 prompts per year.""",
 [('js', "An NPS survey gate in a web app vs `requestReview()`: what does Apple control that you don't (whether it shows at all)?"),
  ('edge', "Why must the logic handle \"prompt requested but system didn't show it\"? Can you even tell?"),
  ('contrast', "In-app review prompt vs a link to the App Store review page: when is each appropriate?"),
  ('practice', "Which user moments count as \"success\" in your app?")],
 ['review', 'prompt', 'rating'], 'product')
E['infinite-scroll'] = ('c', """Prefetching the next page when a row near the end appears, with `isLoading` and `hasMore` guards, is the same as an IntersectionObserver sentinel in JS infinite scroll.""",
 [('js', "IntersectionObserver on a sentinel vs `.onAppear` on the nth-from-last row: which is more robust to fast scrolling?"),
  ('edge', "The user scrolls up and down around the threshold: how does `isLoading` prevent duplicate page requests?"),
  ('contrast', "Offset paging vs cursor paging for infinite scroll: which avoids duplicates when new items arrive?"),
  ('practice', "Showing a loading row and a retry button on failure: where does that state live?")],
 ['infinite scroll', 'pagination', 'onappear'], 'product')
E['offline-sync-queue'] = ('c', """Offline-first: update local state now, queue mutations durably, and flush in order when online, coalescing where possible. It's the service-worker background-sync pattern in PWAs, done in-app on iOS.""",
 [('js', "PWA Background Sync + IndexedDB queue vs an iOS in-app queue: who retries when the app is closed?"),
  ('edge', "Two offline edits to the same record from two devices: last-write-wins, merge, or conflict UI?"),
  ('contrast', "Custom sync queue vs CloudKit sync (`NSPersistentCloudKitContainer`): what do you give up with each?"),
  ('practice', "Which iOS API tells you connectivity changed (`NWPathMonitor`)? Why not ping a server?")],
 ['offline', 'sync', 'queue'], 'product')
E['universal-link-matching'] = ('e', """Universal links open your app for `https://` URLs listed in your server's `apple-app-site-association`. It's like a PWA's scope and URL handling, but verified by Apple with ordered path patterns.""",
 [('js', "A PWA's manifest `scope` captures URLs. How is the AASA file's `components` list more fine-grained?"),
  ('edge', "Why must `exclude` rules come before broad patterns? What happens in the other order?"),
  ('contrast', "Universal links vs custom URL schemes: which can another app hijack?"),
  ('practice', "Links opened inside some in-app browsers don't open your app. Why, and what's the fallback?")],
 ['universal link', 'aasa', 'path'], 'product')
E['image-downsampling'] = ('c', """Decoded image memory is width × height × 4 bytes, whatever the JPEG's file size. Downsampling to display size with ImageIO before decoding is the iOS version of serving `srcset`-sized images on the web, except the device must do it.""",
 [('js', "On the web, `srcset` asks the server for the right size. What's the iOS equivalent when you only have the full-size photo?"),
  ('edge', "Why multiply display points by screen scale (@2x/@3x) before downsampling?"),
  ('contrast', "Downsampling with `CGImageSourceCreateThumbnailAtIndex` vs `UIImage.preparingThumbnail(of:)`: which is simpler?"),
  ('practice', "A photo grid crashes with memory warnings. How would Instruments' Allocations show this problem?")],
 ['downsample', 'thumbnail', 'memory'], 'performance')
E['cs193p-some-view-body'] = ('c', """`var body: some View` is a computed property returning one concrete (but hidden) view type. It's React's `render()` returning JSX, except the return **type** is fixed at compile time, which is what lets SwiftUI diff structurally.""",
 [('js', "A React component returns `ReactElement` (one runtime type). SwiftUI's `some View` is a specific compile-time type. What does SwiftUI gain from that?"),
  ('edge', "Why is `body` recomputed often and cheap? What must never happen inside it (side effects, heavy work)?"),
  ('contrast', "`some View` (opaque) vs `any View` vs `AnyView`: which does `body` use, and why not the others?"),
  ('practice', "CS193p calls views \"Lego\". When do you extract a subview vs a computed property vs a `@ViewBuilder` func?")],
 ['some view', 'body', 'computed property'], 'cs193p')
E['cs193p-match-count-where'] = ('e', """`matches.count(where: { $0 == .exact })` counts without building an intermediate array, like `arr.filter(p).length` in JS without the allocation. CS193p uses it to turn match results into peg counts.""",
 [('js', "`matches.filter(m => m === 'exact').length` vs `count(where:)`: which allocates?"),
  ('contrast', "Counting with `count(where:)` vs `reduce` vs a dictionary of counts per case: which for three categories?"),
  ('edge', "Is `count(where:)` available on every OS your app supports? (It's a compiler/stdlib feature from Swift 6.)"),
  ('practice', "Markers laid out in a grid of 2×2: where should the counts→layout logic live, model or view?")],
 ['count where', 'match', 'markers'], 'cs193p')
E['cs193p-mastermind-match'] = ('c', """Scoring a guess (exact first, then inexact with remaining counts) is the heart of CodeBreaker's model. The course's point: keep game logic in a **model** struct, UI-free and testable, just as you'd keep React components dumb and logic in pure functions.""",
 [('js', "In React you'd put `score(guess, master)` in a pure module. Why does CS193p insist on a separate Model even in SwiftUI?"),
  ('edge', "Duplicate colours in the guess and master: why must exact matches be removed before counting inexact ones?"),
  ('contrast', "Counting with a dictionary vs nested loops with a `used` array: which is easier to prove correct?"),
  ('practice', "How would you unit-test this model with Swift Testing's parameterised `@Test(arguments:)`?")],
 ['match', 'exact', 'inexact'], 'cs193p')
E['cs193p-code-kinds'] = ('e', """`enum Kind { case master(isHidden: Bool), guess, attempt([Match]), unknown }` stores data per case, a TS discriminated union carrying payloads. CS193p uses it so a `Code` knows what role it plays and what extra data it has.""",
 [('js', "Model `Kind` as a TS union. What does Swift's `mutating` switch on `self` let you do that TS needs a reducer for?"),
  ('contrast', "Associated values vs separate optional properties (`matches: [Match]?`): which prevents an attempt without matches?"),
  ('edge', "Can you compare `Kind` values with `==` automatically? When does synthesised `Equatable` work for payload enums?"),
  ('practice', "The course uses `typealias Peg = Color`. Why is a typealias useful while the design is still evolving?")],
 ['associated value', 'enum', 'kind'], 'cs193p')
E['cs193p-tap-to-cycle'] = ('e', """Tapping a peg slot cycles its colour through `choices` using `firstIndex(of:)` plus modular arithmetic, and a `mutating func` on the model. The React equivalent is a reducer case `CYCLE_PEG`.""",
 [('js', "React: `setPegs(p => p.map((c, i) => i === idx ? next(c) : c))`. Swift: `mutating func setGuessPeg`. Which is easier to read?"),
  ('edge', "The current colour isn't in `choices` (a missing peg): what should the next colour be?"),
  ('contrast', "Cycling by tap vs a chooser row (L6): which is more discoverable, and which is more accessible?"),
  ('practice', "Where does this mutation get triggered: the view calls the view model, which calls the model. Why the layers?")],
 ['cycle', 'mutating', 'firstindex'], 'cs193p')
E['cs193p-hstack-layout'] = ('c', """SwiftUI layout: the parent **offers** a size, the child **chooses** its size, and the parent places it. HStack offers space to the least flexible children first. It's close to flexbox's negotiation, but the rules are SwiftUI's own.""",
 [('js', "Flexbox distributes free space by `flex-grow`. How does HStack decide who gets space first?"),
  ('edge', "Two `Text`s that both want more than half: which one truncates? What does `layoutPriority` change?"),
  ('contrast', "`.frame(maxWidth: .infinity)` vs `Spacer()`: how does each express flexibility?"),
  ('practice', "A row with an icon, a title that should truncate, and a fixed-width price: which modifiers?")],
 ['hstack', 'layout', 'offer'], 'cs193p')
E['cs193p-functional-refactor'] = ('e', """CS193p L5 refactors `for` loops into `map` and shows closures capturing local values, the same move JS devs make from `for` to `.map()`, plus Swift's rule that captured locals are references to the variable.""",
 [('js', "Your `for` → `.map()` refactors in JS: do they change when captured values are read?"),
  ('edge', "A closure capturing a local `var` that changes later: which value does it see when it finally runs?"),
  ('contrast', "Loops vs `map`/`reduce`: which is more readable for building a view list?"),
  ('practice', "In SwiftUI, `ForEach` takes a closure. Does that closure capture the item or an index?")],
 ['map', 'closure', 'capture'], 'cs193p')
E['cs193p-color-gray-extension'] = ('e', """Extending `Color` with `static func gray(_:)` adds a convenience constructor to a framework type, like adding a helper to a theme object, but on the type itself. `CGFloat` vs `Double` shows the bridging between graphics and Swift numbers.""",
 [('js', "In JS you'd export `gray(b)` from a theme module. Why is `Color.gray(0.5)` nicer at call sites (`.foregroundStyle(.gray(0.5))`)?"),
  ('edge', "Why can `Color.gray` conflict with the built-in `.gray` property? How does Swift resolve `.gray` vs `.gray(0.5)`?"),
  ('contrast', "`CGFloat` vs `Double`: are they interchangeable now? When does the difference still show up?"),
  ('practice', "Design-system colours: extension on `Color`, asset catalog, or a `Theme` type in the environment?")],
 ['extension', 'color', 'cgfloat'], 'cs193p')
E['cs193p-generic-code-view'] = ('c', """Making `CodeView<AncillaryView: View>` generic with a `@ViewBuilder` closure parameter is exactly React's children/render-props pattern, but typed: the ancillary view's concrete type is part of `CodeView`'s type.""",
 [('js', "React `props.children` or a render prop vs a generic view with a `@ViewBuilder` parameter: what does Swift keep that React erases?"),
  ('edge', "Why store the ancillary view as a closure (`() -> AncillaryView`) vs a value? When is it built?"),
  ('contrast', "Generic view vs `AnyView` parameter: what do you lose with `AnyView`?"),
  ('practice', "Which of your components would become generic views (cards with custom trailing content)?")],
 ['generic', 'viewbuilder', 'ancillary'], 'cs193p')
E['cs193p-hide-master-code'] = ('e', """L8 warns that animation can **reveal hidden state**, like the master code flashing during a transition. The fix is to make the model decide what's visible, a lesson that also applies to React (don't render secrets and hide them with CSS).""",
 [('js', "Hiding a secret with `opacity: 0` in React still ships it in the DOM. What's the SwiftUI equivalent mistake?"),
  ('edge', "A restart animation interpolates from the old code to the new one. How can that leak the answer?"),
  ('contrast', "`if isHidden { … } else { … }` vs `.opacity(isHidden ? 0 : 1)`: which leaks during animation?"),
  ('practice', "Spoilers in a quiz app, prices before purchase: where else can transitions leak state?")],
 ['game over', 'hidden', 'animation'], 'cs193p')
E['cs193p-elapsed-time'] = ('e', """Tracking elapsed time with `startTime` + `elapsedBeforePause` survives pausing when the scene goes inactive. It's the same pattern as a JS stopwatch storing `Date.now()` deltas rather than counting `setInterval` ticks.""",
 [('js', "A JS stopwatch counting `setInterval` ticks drifts. Why does storing timestamps and computing deltas fix it?"),
  ('edge', "The user changes the device clock mid-game: does `Date()` jump? What clock is immune (`ContinuousClock`)?"),
  ('contrast', "`Text(date, style: .timer)` vs a `TimelineView` vs your own timer: which updates the UI without your code running every second?"),
  ('practice', "Where should pausing be triggered: `scenePhase` changes, `onDisappear`, or both?")],
 ['elapsed', 'pause', 'resume'], 'cs193p')
E['cs193p-foreach-identity'] = ('c', """CS193p's three rules for `ForEach` identity (unique, stable, and not the array index when items move) are React's rules for `key`, stated precisely.""",
 [('js', "React docs say keys must be unique and stable. Which of CS193p's three rules is the classic React index-as-key bug?"),
  ('edge', "Using `id: \\.self` on colours: what happens with two identical colours in one row?"),
  ('contrast', "`Identifiable` model vs `ForEach(indices, id: \\.self)`: when is iterating indices acceptable?"),
  ('practice', "How does a wrong identity show up visually: wrong animations, lost text field state, flicker?")],
 ['foreach', 'identity', 'unique'], 'cs193p')
E['cs193p-game-chooser'] = ('e', """Custom `Identifiable`/`Hashable` conformances for the game list decide what makes two games \"the same\". It's the same decision as choosing a React `key` and a memo equality function.""",
 [('js', "React `memo(Component, areEqual)` vs Swift `Hashable`/`Equatable`: which one affects list identity, and which affects re-rendering?"),
  ('edge', "Two games with the same name but different pegs: same `id`? What should editing do?"),
  ('contrast', "Custom `==` vs synthesised `==`: when would comparing only `id` be wrong for SwiftUI updates?"),
  ('practice', "Why might `NavigationLink(value:)` need the whole game to be `Hashable`?")],
 ['identifiable', 'hashable', 'chooser'], 'cs193p')
E['cs193p-split-view-columns'] = ('e', """`NavigationSplitView` shows 1–3 columns depending on the **horizontal size class** (compact on iPhone, regular on iPad). It's responsive design driven by an OS-provided breakpoint rather than CSS media queries.""",
 [('js', "CSS media queries use pixel breakpoints. What does a size class represent, and why is it more robust (split screen, Stage Manager)?"),
  ('edge', "iPad in Slide Over is compact width. What does your split view look like there?"),
  ('contrast', "`NavigationSplitView` vs `NavigationStack` + size-class `if`: which adapts automatically?"),
  ('practice', "Column visibility: when should the sidebar be hidden by default?")],
 ['navigationsplitview', 'size class', 'columns'], 'cs193p')
E['cs193p-peg-choices-editor'] = ('e', """One editor sheet for both create and edit: pass an `@Bindable` model (edit) or a fresh one (create), and commit or discard on Save/Cancel. It's the React pattern of a form with `initialValues` and an `onSubmit` callback.""",
 [('js', "React form: `initialValues` + `onSubmit`. SwiftUI: `@Bindable` edits the model live. How do you support Cancel if edits are live?"),
  ('edge', "Editing a SwiftData object directly: Cancel must roll back. How (a child context, a copy, `undo`)?"),
  ('contrast', "Editing a copy then committing vs editing live with undo: which is simpler with SwiftData?"),
  ('practice', "Validation before Save (empty name, too few pegs): where does it live?")],
 ['bindable', 'editor', 'sheet'], 'cs193p')
E['cs193p-swiftdata-model'] = ('c', """Converting CodeBreaker's structs to `@Model` classes shows the trade-off: persistence needs **reference** types with identity, so value-semantics habits (copying a game) now mean copying a database row.""",
 [('js', "Moving from plain JS objects to ORM entities changes what `===` and copying mean. What changes when structs become `@Model` classes?"),
  ('edge', "Why can't `@Model` store arbitrary enums with payloads or computed properties directly? How does the course work around it (Codable, raw storage)?"),
  ('contrast', "Keeping the struct model and mapping to `@Model` DTOs vs making the model itself `@Model`: which is cleaner?"),
  ('practice', "Schema changes after release: what's a `VersionedSchema` and migration plan?")],
 ['model', 'swiftdata', 'class'], 'cs193p')
E['cs193p-swiftdata-queries'] = ('e', """Predicates across relationships and query limits (no computed properties, careful with optionals) show where `#Predicate` stops being \"just Swift\". It's like an ORM's `where` that can't call your functions.""",
 [('js', "Prisma can't run your JS functions inside `where` either. Why is that fundamental (the query becomes SQL)?"),
  ('edge', "Filtering on a relationship's property (`game.attempts.count > 0`): which forms does `#Predicate` support?"),
  ('contrast', "Store a derived value as a real property vs compute it in memory after fetching: what are the costs?"),
  ('practice', "Sorting by \"last played\": which property would you add to the model?")],
 ['predicate', 'relationship', 'query'], 'cs193p')
E['cs193p-mainactor-background'] = ('c', """UI and view models live on the main actor, and heavy work must hop off it (`@concurrent` / nonisolated async functions) and come back with results. It's the web's \"don't block the main thread\" rule, with the compiler enforcing isolation.""",
 [('js', "In JS you'd move heavy work to a Web Worker and `postMessage` back. What's the Swift 6.2 equivalent, and what does the compiler check?"),
  ('edge', "With Swift 6.2's approachable concurrency, does a `nonisolated async` function run off the main actor by default? (`@concurrent` makes it explicit.)"),
  ('contrast', "`Task.detached` vs a `@concurrent` function vs an actor: which is the cleanest way to offload work?"),
  ('practice', "How do you prove the main thread isn't blocked (Instruments' Hangs, Time Profiler)?")],
 ['mainactor', 'background', 'concurrent'], 'cs193p')
E['cs193p-custom-shape-fit'] = ('e', """Custom `Shape`s plus `GeometryReader` sizing: compute the largest element that fits the offered space. It's the SwiftUI version of measuring a container with ResizeObserver and computing layout in JS.""",
 [('js', "ResizeObserver + JS layout maths vs `GeometryReader`: which one re-runs on size changes automatically?"),
  ('edge', "Why does `GeometryReader` take all offered space? What problems does that cause in stacks?"),
  ('contrast', "`GeometryReader` vs `Layout` protocol vs `containerRelativeFrame`: which for \"fit N items in the space\"?"),
  ('practice', "Card grids that must fit exactly on screen without scrolling (a game board): which approach?")],
 ['geometryreader', 'shape', 'fit'], 'cs193p')
E['cs193p-gesture-state'] = ('c', """Committed state (`zoom`, `pan`) plus in-flight `@GestureState` combined in the view is the standard multi-touch pattern. It's the same split as keeping a \"drag delta\" separate from the committed position in a JS drag handler.""",
 [('js', "A JS drag handler keeps `start` + `delta` and commits on `pointerup`. How does `@GestureState` automate the reset?"),
  ('edge', "A gesture cancelled by an incoming call: `@GestureState` resets. Does your committed state stay correct?"),
  ('contrast', "`.simultaneously(with:)` vs `.sequenced(before:)` vs `.exclusively(before:)`: which for pinch + drag?"),
  ('practice', "Zoom around the pinch centre rather than the view centre: what extra maths is needed?")],
 ['gesturestate', 'pinch', 'drag'], 'cs193p')
E['cs193p-file-persistence'] = ('c', """Encoding the model with `Codable` and writing it to the app's Documents directory is L16's alternative to SwiftData, the same as saving JSON to disk in Node or IndexedDB on the web, with atomic writes.""",
 [('js', "`fs.writeFileSync('games.json', JSON.stringify(games))` vs `try data.write(to: url, options: .atomic)`: what does `.atomic` add?"),
  ('edge', "Encoding fails (a non-Codable property sneaks in) or the file is from an older version: what should load do?"),
  ('contrast', "File persistence vs SwiftData: which is easier to export, sync, or query?"),
  ('practice', "Autosave triggers: every change, on background, or debounced? What does the course do?")],
 ['codable', 'file', 'persistence'], 'cs193p')
